SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER FUNCTION dbo.fn_NgayKinhDoanh(@UtcInstant DATETIME2(7))
RETURNS DATE
AS
BEGIN
    RETURN CONVERT(DATE, dbo.fn_GioRap(@UtcInstant));
END;
GO
