CREATE NONCLUSTERED INDEX [IX_HINHANH_RAPCHIEUPHIM_Rap_TrangThai_ThuTu] ON dbo.[HINHANH_RAPCHIEUPHIM] ([RapID] ASC, [TrangThai] ASC, [ThuTuHienThi] ASC, [HinhAnhRapID] ASC);
GO
CREATE UNIQUE NONCLUSTERED INDEX [UX_HINHANH_RAPCHIEUPHIM_Rap_Cover] ON dbo.[HINHANH_RAPCHIEUPHIM] ([RapID] ASC) WHERE ([LaAnhDaiDien]=(1));
GO
