CREATE NONCLUSTERED INDEX [IX_KHIEUNAI_DonDatVe] ON dbo.[KHIEUNAI] ([DonDatVeID] ASC) WHERE ([DonDatVeID] IS NOT NULL);
GO
CREATE NONCLUSTERED INDEX [IX_KHIEUNAI_NguoiDung] ON dbo.[KHIEUNAI] ([NguoiDungID] ASC, [TrangThai] ASC);
GO
CREATE NONCLUSTERED INDEX [IX_KHIEUNAI_TrangThai] ON dbo.[KHIEUNAI] ([TrangThai] ASC, [MucDoUuTien] ASC, [NgayTao] DESC);
GO
