CREATE NONCLUSTERED INDEX [IX_NGUOIDUNG_TrangThai] ON dbo.[NGUOIDUNG] ([TrangThai] ASC) INCLUDE ([HoTen], [Email]);
GO
CREATE NONCLUSTERED INDEX [IX_NGUOIDUNG_VaiTroID] ON dbo.[NGUOIDUNG] ([VaiTroID] ASC);
GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_NGUOIDUNG_SoDienThoai] ON dbo.[NGUOIDUNG] ([SoDienThoai] ASC) WHERE ([SoDienThoai] IS NOT NULL);
GO
