SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE dbo.sp_Admin_Actor_List
AS
BEGIN
    SET NOCOUNT ON;
    SELECT DienVienID, HoTen, NgaySinh, QuocTich FROM dbo.DIENVIEN ORDER BY HoTen;
END;
GO
