SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE dbo.sp_Admin_Role_List
AS
BEGIN
    SET NOCOUNT ON;
    SELECT VaiTroID, MaVaiTro, TenVaiTro, MoTa FROM dbo.VAITRO ORDER BY VaiTroID;
END;
GO
