SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER PROCEDURE dbo.sp_Admin_Permission_List
AS
BEGIN
    SET NOCOUNT ON;
    SELECT QuyenID, MaQuyen, TenQuyen, MoTa FROM dbo.QUYEN ORDER BY MaQuyen;
END;
GO
