-- One immutable compensation entry per order; written atomically with cancellation and points.
CREATE TABLE dbo.BOITHUONG_HUYSUAT (
    BoiThuongID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_BOITHUONG_HUYSUAT PRIMARY KEY,
    DonDatVeID INT NOT NULL CONSTRAINT UQ_BOITHUONG_HUYSUAT_Don UNIQUE,
    DiemBoiThuong INT NOT NULL,
    NgayBoiThuong DATETIME2 NOT NULL,
    GhiChu NVARCHAR(255) NULL,
    CONSTRAINT FK_BOITHUONG_HUYSUAT_Don FOREIGN KEY (DonDatVeID) REFERENCES dbo.DONDATVE(DonDatVeID),
    CONSTRAINT CK_BOITHUONG_HUYSUAT_Diem CHECK (DiemBoiThuong >= 0)
);
GO
