import assert from 'node:assert/strict';
import path from 'node:path';
import { disposable,database,env,root,connect,snapshot,summarize,read,write,evidenceRoot,batches } from './common.mjs';
import { createFixture,cleanupFixture,state,bulk,event,statuses,processing,updateStatus,assertLatest,preserved,cleanSession } from './fixtures.mjs';
disposable();Object.assign(process.env,env,{DB_DATABASE:database});process.chdir(path.join(root,'backend'));const {createApp}=await import('../../backend/src/app.js'),{closePool}=await import('../../backend/src/db/pool.js');const pool=await connect(),server=createApp().listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url=`http://127.0.0.1:${server.address().port}/api`,tokens={},e={database,startedAt:new Date().toISOString(),status:'RUNNING',requests:[],cases:[]};let f,removed=false;
async function api(role,method,route,body,expected=200){const response=await fetch(url+route,{method,headers:{'Content-Type':'application/json',...(tokens[role]?{Authorization:'Bearer '+tokens[role]}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(30000)}),result=await response.json();e.requests.push({role,method,route,status:response.status,expected,...(result.error?{error:result.error}:{})});assert.equal(response.status,expected,JSON.stringify(result));if(result.error)assert.ok(!/dbo\.|SELECT|THROW|stack|connection|51034|Disposable/i.test(JSON.stringify(result.error)));return result;}
const prefix=role=>role==='admin'?'/admin':'/support';
async function readers(id,owner='customer'){
 const actual=await state(pool,f),parent=actual.parents.find(x=>x.KhieuNaiID===id),history=actual.history.filter(x=>x.KhieuNaiID===id),out={};
 for(const role of ['support','admin',owner]){const r=(await api(role,'GET',role===owner?`/complaints/${id}`:`${prefix(role)}/complaints/${id}`)).complaint;assert.equal(r.status,parent.TrangThai);const h=role===owner?r.processingHistory:r.processings;assert.equal(h.length,history.length);assert.deepEqual(h.map(x=>x.id).sort((a,b)=>a-b),history.map(x=>x.XuLyID));for(const x of h){const y=history.find(y=>y.XuLyID===x.id);assert.equal(x.status,y.TrangThaiSauXuLy);assert.equal(x.content,y.NoiDungXuLy);}assert.ok(h.every((x,i)=>!i||Date.parse(h[i-1].processedAt)<=Date.parse(x.processedAt)));out[role]=r;}
 for(const role of ['support','admin',owner]){const result=await api(role,'GET',role===owner?'/complaints':`${prefix(role)}/complaints`),row=result.complaints.find(x=>x.id===id);assert.equal(row.status,parent.TrangThai);if(role!==owner){assert.equal(row.processingCount,history.length);assert.equal(row.lastProcessingContent,history.at(-1)?.NoiDungXuLy??null);}}
 return out;
}
async function reject(name,role,method,route,body,expected,code){const initial=await state(pool,f),before=await snapshot(pool),response=await api(role,method,route,body,expected);assert.equal(response.error.code,code);assert.deepEqual(await state(pool,f),initial);assert.deepEqual((await snapshot(pool)).data,before.data);e.cases.push({name,response,initial,final:await state(pool,f),status:'PASS'});}
try{
 const before=await snapshot(pool);f=await createFixture(pool);
 for(const role of ['support','admin','customer','otherCustomer','manager']){const user=f.users.find(x=>x.NguoiDungID===f[role]);tokens[role]=(await api(role,'POST','/auth/login',{Email:user.Email,MatKhau:'123456'},200)).token;}
 const created=await api('customer','POST','/complaints',{type:'R33 support',title:'R33 HTTP-created',content:'Actual customer complaint',orderId:null},201);f.ids.push(created.complaint.id);assert.equal(created.complaint.status,'Mới');e.cases.push({name:'customer-create-and-detail',response:created,reads:await readers(created.complaint.id),final:await state(pool,f),status:'PASS'});
 for(const role of ['support','admin'])for(const status of statuses){const id=role==='support'?f.ids[0]:f.ids[1],initial=await state(pool,f),response=await api(role,'POST',`${prefix(role)}/complaints/${id}/processings`,{content:`${role}-${status}`,nextStatus:status},role==='admin'?200:201),final=await state(pool,f);preserved(initial,final,[id]);assert.equal(final.history.length,initial.history.length+1);assertLatest(final,[id]);assert.equal(response.processing.KhieuNaiID,id);e.cases.push({name:'single-processing-'+role+'-'+status,response,initial,reads:await readers(id),final,status:'PASS'});}
 for(const role of ['support','admin']){const initial=await state(pool,f),id=f.ids[0],response=await api(role,'PUT',`${prefix(role)}/complaints/${id}/status`,{status:'Đang xử lý'}),final=await state(pool,f);assert.equal(final.history.length,initial.history.length+1);assert.equal(response.complaint.status,'Đang xử lý');preserved(initial,final,[id]);e.cases.push({name:'status-is-append-only-'+role,response,initial,reads:await readers(id),final,status:'PASS'});}
 const multiInitial=await state(pool,f),input=[event(f,f.ids[0],'Đã đóng','batch0'),event(f,f.ids[1],'Đang xử lý','batch1'),event(f,f.ids[0],'Từ chối','batch2'),event(f,f.ids[1],'Đã giải quyết','batch3')];await bulk(pool,input);const multiFinal=await state(pool,f);preserved(multiInitial,multiFinal,f.ids.slice(0,2));assert.equal(multiFinal.history.length,multiInitial.history.length+4);e.cases.push({name:'multi-row-SQL-with-real-HTTP-readers',input,initial:multiInitial,reads:[await readers(f.ids[0]),await readers(f.ids[1])],latest:assertLatest(multiFinal,f.ids.slice(0,2)),final:multiFinal,status:'PASS'});
 e.cases.push({name:'other-customer-own-complaint',reads:await readers(f.ids[4],'otherCustomer'),final:await state(pool,f),status:'PASS'});
 for(const role of ['support','admin']){const route=`${prefix(role)}/complaints/${f.ids[0]}/processings`,body={content:'valid',nextStatus:'Đã giải quyết'};
  for(const [name,b] of [['invalid-status',{...body,nextStatus:'Chờ phản hồi'}],['initial-status',{...body,nextStatus:'Mới'}],['omitted-content',{nextStatus:'Đã đóng'}],['null-status',{...body,nextStatus:null}]])await reject(name+'-'+role,role,'POST',route,b,400,'INVALID_REQUEST');
  await reject('spoof-actor-'+role,role,'POST',route,{...body,NguoiXuLyID:f.admin},400,'UNKNOWN_REQUEST_FIELD');await reject('wrong-role-'+role,'customer','POST',route,body,403,role==='admin'?'ADMIN_REQUIRED':'SUPPORT_REQUIRED');await reject('unauthenticated-'+role,'none','POST',route,body,401,'UNAUTHENTICATED');await reject('missing-complaint-'+role,role,'POST',`${prefix(role)}/complaints/2147483647/processings`,body,404,'COMPLAINT_NOT_FOUND');await reject('invalid-status-update-'+role,role,'PUT',`${prefix(role)}/complaints/${f.ids[0]}/status`,{status:'Mới'},400,'INVALID_REQUEST');
 }
 await reject('foreign-customer-detail','otherCustomer','GET',`/complaints/${f.ids[0]}`,undefined,404,'COMPLAINT_NOT_FOUND');await reject('manager-support','manager','GET','/support/complaints',undefined,403,'SUPPORT_REQUIRED');
 for(const role of ['support','admin'])for(const code of ['QL_KHIEUNAI','XULY_KHIEUNAI']){
  await pool.request().batch(`SELECT vq.* INTO #R33Grants FROM dbo.VAITRO_QUYEN vq JOIN dbo.NGUOIDUNG n ON n.VaiTroID=vq.VaiTroID JOIN dbo.QUYEN q ON q.QuyenID=vq.QuyenID WHERE n.NguoiDungID=${f[role]} AND q.MaQuyen='${code}';DELETE vq FROM dbo.VAITRO_QUYEN vq JOIN #R33Grants p ON p.VaiTroID=vq.VaiTroID AND p.QuyenID=vq.QuyenID;`);removed=true;
  try{await reject('live-permission-'+role+'-'+code,role,'POST',`${prefix(role)}/complaints/${f.ids[0]}/processings`,{content:'forbidden',nextStatus:'Đã đóng'},403,'FORBIDDEN');await reject('live-permission-status-'+role+'-'+code,role,'PUT',`${prefix(role)}/complaints/${f.ids[0]}/status`,{status:'Đã đóng'},403,'FORBIDDEN');await assert.rejects(processing(pool,f,role,f.ids[0],'Đã đóng'),r=>r.number===50302);await assert.rejects(updateStatus(pool,f,role,f.ids[0],'Đã đóng'),r=>r.number===50302);}
  finally{await pool.request().batch('INSERT dbo.VAITRO_QUYEN SELECT * FROM #R33Grants;DROP TABLE #R33Grants;');removed=false;}
 }
 const fault=read(path.join(root,'database/11_tests/complaints/processing_rollback.sql')).replace("TRY_CONVERT(INT,SESSION_CONTEXT(N'R33_Target'))",String(f.ids[0]));await batches(pool,fault);
 try{for(const role of ['support','admin'])for(const kind of ['processing','status']){const initial=await state(pool,f),reply=await api(role,kind==='processing'?'POST':'PUT',`${prefix(role)}/complaints/${f.ids[0]}/${kind==='processing'?'processings':'status'}`,kind==='processing'?{content:'after-update fault',nextStatus:'Đang xử lý'}:{status:'Đang xử lý'},500);assert.equal(reply.error.message,'Internal server error');assert.deepEqual(await state(pool,f),initial);e.cases.push({name:'safe-trigger-failure-'+role+'-'+kind,response:reply,initial,reads:await readers(f.ids[0]),final:await state(pool,f),status:'PASS'});}}
 finally{await pool.request().batch('DROP TRIGGER IF EXISTS dbo.R33_ParentFailure;');}
 for(const role of ['support','admin']){const r=await api(role,'GET',`${prefix(role)}/complaints/${f.ids[0]}/order-reference`);assert.equal(r.order,null);assert.ok(r.message);}
 await cleanupFixture(pool,f);f=null;const after=await snapshot(pool);assert.deepEqual(summarize(after),summarize(before));e.before=summarize(before);e.after=summarize(after);e.session=await cleanSession(pool);e.cleanup='PASS';e.status='PASS';
}catch(error){e.status='FAIL';e.error={message:error.message,number:error.number};throw error;}
finally{if(removed)await pool.request().batch('INSERT dbo.VAITRO_QUYEN SELECT * FROM #R33Grants;DROP TABLE #R33Grants;');await pool.request().batch('IF @@TRANCOUNT>0 ROLLBACK;DROP TRIGGER IF EXISTS dbo.R33_ParentFailure;');if(f)await cleanupFixture(pool,f);e.completedAt=new Date().toISOString();write(path.join(evidenceRoot,'api-tests.json'),e);await new Promise(r=>server.close(r));await closePool();await pool.close();}
console.log(`PASS complaint real API:${e.requests.length} requests,${e.cases.length} cases;CSKH/Admin writes,customer history/ownership,live RBAC,SQL multi-row readers,safe trigger failure;no drift.`);
