import assert from 'node:assert/strict';
import path from 'node:path';
import { root,evidenceRoot,read,write } from './common.mjs';
const previous=JSON.parse(read(path.join(root,'docs/evidence/r32/current-audit-status.json'))),{matrix,findings}=structuredClone(previous),issue=findings.issues.find(x=>x.id==='I-16');assert.equal(issue.status,'ACTIVE');
Object.assign(issue,{status:'RESOLVED R3.3',evidence:'docs/evidence/r33/{sql-tests,api-tests,complaint-concurrency,before-concurrency,checks,main-migration}.json',resolution:'Existing AFTER INSERT trigger locks affected parent resources, then ROW_NUMBER over full affected history PARTITION BY KhieuNaiID ORDER BY XuLyID DESC;rn=1 unique source. Real single/multi/mixed SQL,rollback,CSKH/Admin/customer API and delayed smaller-identity races pass;no schema/API/UI redesign.'});
const affected=['KH-14','CSKH-02','CSKH-03','CSKH-05','CSKH-06','ADM-15'];
for(const row of matrix.rows.filter(x=>affected.includes(x.uc))){assert.equal(row.status,'PARTIAL');row.issue=row.issue.replace(/I-16[^;.]*/g,'I-16 RESOLVED R3.3').replace('positive absent','positive complaint/status/history path verified R3.3').replace('chưa write','processing/status writes verified R3.3');row.issue+='; R3.3 deterministic status/history SQL/API/rollback/race evidence;broader UC acceptance remains PARTIAL.';row.evidence='docs/evidence/R3_COMPLAINT_TRIGGER_DETERMINISM.md';}
matrix.baseline.note='Incremental R3.3 after accepted R0/R1/R2/R3.1/R3.2;only I-16 resolved. All45 UC grades unchanged;stop before R4.';findings.severity={CRITICAL:0,HIGH:0,MEDIUM:0,LOW:0};for(const x of findings.issues.filter(x=>x.status==='ACTIVE'))findings.severity[x.severity]++;findings.baseline.active=findings.issues.filter(x=>x.status==='ACTIVE').length;findings.baseline.resolved=findings.issues.filter(x=>x.status.startsWith('RESOLVED')).length;
assert.equal(matrix.rows.length,45);assert.deepEqual(matrix.rows.map(x=>[x.uc,x.status]),previous.matrix.rows.map(x=>[x.uc,x.status]));for(const id of ['I-02','I-03','I-06','I-07','I-08','I-09'])assert.equal(findings.issues.find(x=>x.id===id).status,previous.findings.issues.find(x=>x.id===id).status);
write(path.join(evidenceRoot,'current-audit-status.json'),{at:new Date().toISOString(),phase:'R3.3',status:'PASS',base:'Accepted R0/R1/R2/R3.1/R3.2 artifacts immutable',changedUseCases:affected,resolvedIssues:['I-16'],matrix,findings});console.log('PASS audit: I16 resolved;all45 UC grades/prior issues preserved;stop before R4.');
