import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { root,evidenceRoot,read,write,env,normalizeModule } from './common.mjs';
import { walk } from '../db/lib.mjs';
import { latest } from './fixtures.mjs';
const r=n=>JSON.parse(read(path.join(evidenceRoot,n+'.json'))),sha=s=>crypto.createHash('sha256').update(s.replace(/\r\n/g,'\n')).digest('hex');
const frozen=r('preserved-before');for(const x of frozen.files)assert.equal(sha(fs.readFileSync(path.join(root,x.file),'utf8')),x.sha256,x.file);
const checks=r('checks'),database=checks.database;assert.equal(checks.status,'PASS');assert.equal(checks.checks.length,16);assert.ok(checks.checks.every(x=>x.status==='PASS'&&(x.skipped??0)===0));
for(const name of ['sql-tests','api-tests','complaint-concurrency','r1-regression','r21-regression','r22-regression','r31-regression','r32-regression','r11-sql','r11-concurrency','r12-sql','r12-nested','r12-concurrency','r21-sql','r21-api','r21-parents','r22-sql','r22-api','r22-promotion','r31-sql','r31-api','r31-concurrency','r32-sql','r32-api','r32-concurrency','r32-transactions','migration-replay']){assert.equal(r(name).status,'PASS',name);assert.equal(r(name).database,database,name);}
for(const name of ['source-parity','r22-browser','r31-browser','r32-browser','main-test-isolation','main-migration','main-readonly','main-complaints-before','current-audit-status','changed-files','before-probe','before-concurrency'])assert.equal(r(name).status,'PASS',name);
const trigger=read(path.join(root,'database/07_triggers/TRG_XuLyKhieuNai_CapNhatTrangThaiKhieuNai.sql')),body=trigger.replace(/--[^\n]*/g,'');assert.match(body,/ROW_NUMBER\s*\(\s*\)\s*OVER\s*\(PARTITION BY xl\.KhieuNaiID ORDER BY xl\.XuLyID DESC\)/);assert.match(body,/latest\.rn\s*=\s*1/);assert.match(body,/UPDLOCK, HOLDLOCK/);assert.ok(!/\bCURSOR\b|\bWHILE\b|\bNOLOCK\b|\bTOP\s+1\b/i.test(body));assert.match(body,/AFTER INSERT\s+AS/);assert.ok(!/AFTER INSERT\s*,\s*UPDATE/i.test(body));assert.ok(!/\bINSERT\s+INTO\b|\bDELETE\b|BEGIN TRAN|COMMIT TRAN/i.test(body));
const sql=r('sql-tests'),api=r('api-tests'),races=r('complaint-concurrency'),migration=r('main-migration');assert.equal(sql.cases.length,29);assert.equal(sql.cases.filter(x=>x.sqlError).length,7);assert.equal(sql.rollback.length,6);assert.equal(api.requests.length,158);assert.equal(api.cases.length,45);assert.equal(races.cases.length,10);assert.equal(races.delayed.length,2);
for(const name of ['single-direct-insert','new-single-preserves-existing-history','multiple-complaints-one-each','all-complaints-multiple-rows','mixed-single-and-multiple','identity-order-over-timestamp','empty-statement','legacy-alias'])assert.ok(sql.cases.some(x=>x.name===name&&x.status==='PASS'));
for(let i=0;i<8;i++)assert.ok(sql.cases.some(x=>x.name==='same-parent-input-order-'+i&&x.status==='PASS'));
for(const x of sql.cases){assert.equal(x.status,'PASS');if(x.sqlError)assert.deepEqual(x.final,x.initial);for(const y of x.latest??[])assert.equal(y.actualStatus,y.expectedStatus);assert.equal(x.session.trancount,0);assert.equal(x.session.xactState,0);}
for(const x of sql.rollback){assert.deepEqual(x.final,x.initial);assert.equal(x.session.trancount,0);assert.equal(x.session.xactState,0);}assert.deepEqual(sql.rollback[0].held,{trancount:1,xactState:1});assert.ok(sql.rollback[1].observed.every(x=>x.TrangThai==='Đã đóng'));
for(const x of [...races.cases,...races.delayed]){assert.equal(x.status,'PASS');assert.notEqual(x.spids.a,x.spids.b);for(const y of x.latest)assert.equal(y.expectedStatus,y.actualStatus);for(const s of Object.values(x.sessions)){assert.equal(s.trancount,0);assert.equal(s.xactState,0);}assert.match((x.blocking??x.gateBlocking).wait_type,/^LCK_M_/);}
for(const x of races.delayed){assert.equal(x.highCommittedBeforeLow,true);assert.equal(x.mismatch,false);assert.ok(x.first.success&&x.second.success);assert.equal(x.final.history.length,2);}
assert.ok(r('before-concurrency').delayed.every(x=>x.highCommittedBeforeLow&&x.mismatch&&x.first.success&&x.second.success));
for(const role of ['support','admin']){assert.ok(api.cases.some(x=>x.name==='status-is-append-only-'+role));for(const code of ['QL_KHIEUNAI','XULY_KHIEUNAI'])assert.ok(api.cases.some(x=>x.name==='live-permission-'+role+'-'+code&&x.response.error.code==='FORBIDDEN'));for(const kind of ['processing','status'])assert.ok(api.cases.some(x=>x.name==='safe-trigger-failure-'+role+'-'+kind&&x.response.error.message==='Internal server error'));}
assert.ok(api.cases.some(x=>x.name==='foreign-customer-detail'&&x.response.error.code==='COMPLAINT_NOT_FOUND'));assert.ok(api.cases.some(x=>x.name==='multi-row-SQL-with-real-HTTP-readers'&&x.reads.length===2));
assert.equal(r('r11-sql').cases.length,20);assert.equal(r('r11-concurrency').cases.length,10);assert.equal(r('r12-sql').cases.length,49);assert.equal(r('r12-nested').cases.length,14);assert.equal(r('r12-concurrency').stressRaces,125);
assert.equal(r('r21-sql').cases.length,30);assert.equal(r('r21-api').requests.length,107);assert.equal(r('r21-parents').cases.length,14);assert.equal(r('r21-api').concurrency.length,2);
assert.equal(r('r22-sql').cases.length,28);assert.equal(r('r22-sql').constraintCases.length,6);assert.equal(r('r22-api').requests.length,54);assert.equal(r('r22-api').concurrency.length,2);assert.equal(r('r22-promotion').lastQuota.length,2);assert.equal(r('r22-promotion').adminRaces.length,12);
assert.equal(r('r31-sql').positive.length,9);assert.equal(r('r31-sql').negative.length,30);assert.equal(r('r31-api').requests.length,59);assert.equal(r('r31-concurrency').replacements.length,4);assert.equal(r('r31-concurrency').actorDelete.length,4);assert.equal(r('r31-concurrency').movieDelete.length,2);
assert.equal(r('r32-sql').cases.length,108);assert.equal(r('r32-api').requests.length,240);assert.equal(r('r32-concurrency').cases.length,20);assert.equal(r('r32-transactions').cases.length,8);assert.equal(r('r32-browser').result.checks.length,24);assert.equal(r('r31-browser').result.checks.length,8);assert.equal(r('r22-browser').result.checks.length,10);
assert.equal(migration.sourceParity.modules,159);assert.equal(migration.backup.restoreVerifyOnly,'PASS');assert.ok(migration.backup.copyOnly&&migration.backup.checksum);assert.deepEqual(migration.changedModules,['TRG_XuLyKhieuNai_CapNhatTrangThaiKhieuNai']);assert.deepEqual(migration.before.data,migration.after.data);assert.deepEqual(migration.after.data,r('main-before-tests').state.data);assert.equal(migration.after.data.length,27);assert.deepEqual(r('main-readonly').complaintStatusAnomalies,r('main-complaints-before').anomalies);assert.equal(r('main-readonly').complaintCount,r('main-complaints-before').complaintCount);assert.equal(r('main-readonly').processingRowCount,r('main-complaints-before').processingRowCount);
const audit=r('current-audit-status'),oldAudit=JSON.parse(read(path.join(root,'docs/evidence/r32/current-audit-status.json')));assert.equal(audit.findings.issues.find(x=>x.id==='I-16').status,'RESOLVED R3.3');assert.deepEqual(audit.matrix.rows.map(x=>[x.uc,x.status]),oldAudit.matrix.rows.map(x=>[x.uc,x.status]));for(const id of ['I-02','I-03','I-06','I-07','I-08','I-09'])assert.equal(audit.findings.issues.find(x=>x.id===id).status,oldAudit.findings.issues.find(x=>x.id===id).status);
for(const file of walk(evidenceRoot))if(/\.(json|txt|md|patch|sql|js|jsx)$/.test(file)){const text=read(file);if(env.DB_PASSWORD)assert.ok(!text.includes(env.DB_PASSWORD),'Configured password in '+file);assert.ok(!/"token"\s*:\s*"eyJ/.test(text),'JWT in '+file);}
assert.ok(r('changed-files').modified.every(x=>frozen.mutable.some(y=>y.file===x.file)));execFileSync('git',['-c','core.safecrlf=false','diff','--check'],{cwd:root,encoding:'utf8'});
const criteria=[['Trace mọi complaint processing writer','trace-before.md'],['Root cause I-16 xác định','before-concurrency.json'],['Trigger set-based','source-changes.patch'],['Không cursor','source-changes.patch'],['Không WHILE/row-by-row','source-changes.patch'],['Không giả định INSERTED một row','sql-tests.json'],['ROW_NUMBER/PARTITION complaint/ORDER BY XuLyID DESC','source-changes.patch'],['Một latest row cho mỗi complaint','sql-tests.json'],['Parent bằng latest processing status','complaint-concurrency.json'],['Single-row không regression','api-tests.json'],['Multiple complaints một INSERT PASS','sql-tests.json'],['Multiple rows cùng complaint PASS','sql-tests.json'],['Mixed batch PASS','sql-tests.json'],['Các statuses khác nhau chính xác','sql-tests.json'],['Unrelated complaints giữ nguyên','sql-tests.json'],['Existing history giữ nguyên','api-tests.json'],['Rollback phục hồi parent','sql-tests.json'],['Rollback không giữ history mới','sql-tests.json'],['SQL positives PASS','sql-tests.json'],['SQL negatives PASS','sql-tests.json'],['Multi-row SQL integration PASS','api-tests.json'],['CSKH API flow PASS','api-tests.json'],['Customer read/timeline PASS','api-tests.json'],['Permission/authorization giữ nguyên','api-tests.json'],['Backend regression PASS','checks.json'],['No-SQL PASS','no-sql.txt'],['Prior phases regression PASS','checks.json'],['Source/schema parity PASS','source-parity.json'],['Không thêm bảng','main-migration.json'],['Không thêm LastProcessingID column','main-migration.json'],['Không redesign Frontend','preserved-before.json'],['Evidence final DB states thật','complaint-concurrency.json'],['I-16 RESOLVED','current-audit-status.json']].map(([criterion,evidence],i)=>({id:i+1,criterion,evidence,status:'PASS'}));assert.equal(criteria.length,33);
const report=read(path.join(root,'docs/evidence/R3_COMPLAINT_TRIGGER_DETERMINISM.md'));assert.equal((report.match(/^## \d+\./gm)??[]).length,29);assert.ok(report.includes('R3.3 DONE')&&report.includes('R4'));
write(path.join(evidenceRoot,'final-checks.json'),{at:new Date().toISOString(),database,status:'PASS',protectedFiles:frozen.files.length,checkGroups:16,sqlCases:29,sqlPositives:22,sqlNegatives:7,rollbackCases:6,apiRequests:158,apiCases:45,canonicalAndMixedRaces:10,delayedIdentityRaces:2,backendTests:checks.checks.find(x=>x.name==='backend').tests,frontendTests:checks.checks.find(x=>x.name==='frontend').tests,skipCount:0,priorRegression:'R1/R2/R3.1/R3.2 PASS',sourceParityModules:159,tablesPreserved:27,backendFrontendSourcesPreserved:'PASS',mainDataPreserved:'PASS',credentialsScan:'PASS',whitespace:'PASS',exitCriteria:criteria});write(path.join(evidenceRoot,'exit-criteria.md'),'| # | Exit criterion | Result | Evidence |\n|---|---|---|---|\n'+criteria.map(x=>`| ${x.id} | ${x.criterion} | PASS | [raw](${x.evidence}) |`).join('\n')+'\n');console.log(`PASS final R3.3:${frozen.files.length} prior files preserved;33/33 criteria;real SQL/API/batch/rollback/races;data27/modules159;stop before R4.`);
