import assert from 'node:assert/strict';
import path from 'node:path';
import { sql,disposable,database,connect,snapshot,summarize,batches,read,write,root,evidenceRoot } from './common.mjs';
import { createFixture,cleanupFixture,state,bulk,event,statuses,processing,updateStatus,assertLatest,preserved,cleanSession } from './fixtures.mjs';
disposable();const pool=await connect(),e={database,startedAt:new Date().toISOString(),status:'RUNNING',cases:[],rollback:[]};let f;
async function run(name,makeRows,prepare,errorNumber){
 f=await createFixture(pool);await processing(pool,f,'support',f.ids[3],'Đã đóng','unrelated history');if(prepare)await prepare(f);const initial=await state(pool,f),input=makeRows(f),affected=[...new Set(input.map(x=>x.complaint))],pre=errorNumber?await snapshot(pool):null;
 if(errorNumber)await assert.rejects(bulk(pool,input),r=>r.number===errorNumber);else await bulk(pool,input);const final=await state(pool,f);
 if(errorNumber){assert.deepEqual(final,initial);assert.deepEqual((await snapshot(pool)).data,pre.data);}else{preserved(initial,final,affected);assert.equal(final.history.length,initial.history.length+input.length);for(const x of input){const h=final.history.filter(r=>r.NoiDungXuLy===x.content);assert.equal(h.length,1);assert.equal(h[0].KhieuNaiID,x.complaint);assert.equal(h[0].TrangThaiSauXuLy,x.status);assert.equal(h[0].NguoiXuLyID,x.actor);}assertLatest(final,affected);}
 e.cases.push({name,input,...(errorNumber?{sqlError:errorNumber}:{}),initial,final,...(!errorNumber?{latest:assertLatest(final,affected)}:{}),session:await cleanSession(pool),status:'PASS'});await cleanupFixture(pool,f);f=null;
}
const previous=async f=>{await processing(pool,f,'support',f.ids[0],'Đã giải quyết','previous processing');await processing(pool,f,'admin',f.ids[1],'Đã đóng','previous other');};
try{
 const before=await snapshot(pool);
 for(const role of ['support','admin']){
  f=await createFixture(pool);const initial=await state(pool,f),steps=[];
  for(const status of statuses){const start=await state(pool,f),result=await processing(pool,f,role,f.ids[0],status,'single-'+status);const final=await state(pool,f);preserved(start,final,[f.ids[0]]);assert.equal(final.history.length,start.history.length+1);assert.equal(result.recordset[0].XuLyID,final.history.at(-1).XuLyID);steps.push({status,returned:result.recordset,final,latest:assertLatest(final,[f.ids[0]])});}
  await updateStatus(pool,f,role,f.ids[0],'Đang xử lý');const final=await state(pool,f);assert.equal(final.history.length,5);assertLatest(final,[f.ids[0]]);preserved(initial,final,[f.ids[0]]);e.cases.push({name:'canonical-single-and-status-'+role,initial,steps,final,session:await cleanSession(pool),status:'PASS'});await cleanupFixture(pool,f);f=null;
 }
 await run('single-direct-insert',f=>[event(f,f.ids[0],'Đang xử lý','single')]);
 await run('new-single-preserves-existing-history',f=>[event(f,f.ids[0],'Đã đóng','new')],previous);
 await run('multiple-complaints-one-each',f=>f.ids.slice(0,3).map((id,i)=>event(f,id,statuses[i],'separate-'+i)));
 for(let order=0;order<8;order++)await run('same-parent-input-order-'+order,f=>{const rows=statuses.map((status,i)=>event(f,f.ids[0],status,'multi-'+i));return order<4?[...rows.slice(order),...rows.slice(0,order)]:[...rows.slice(order-4),...rows.slice(0,order-4)].reverse();},previous);
 await run('all-complaints-multiple-rows',f=>f.ids.slice(0,3).flatMap((id,i)=>statuses.map((status,j)=>event(f,id,status,`all-${i}-${j}`))),previous);
 await run('mixed-single-and-multiple',f=>[event(f,f.ids[0],'Đang xử lý','mix0'),event(f,f.ids[1],'Đã đóng','mix1'),event(f,f.ids[0],'Đã giải quyết','mix2'),event(f,f.ids[2],'Từ chối','mix3'),event(f,f.ids[1],'Đang xử lý','mix4')],previous);
 for(const status of statuses)await run('same-status-'+status,f=>Array.from({length:4},(_,i)=>event(f,f.ids[i%2],status,'same-'+i)),previous);
 await run('identity-order-over-timestamp',f=>[event(f,f.ids[0],'Từ chối','timestamp-future',f.admin,'2099-01-01T00:00:00Z'),event(f,f.ids[0],'Đã giải quyết','timestamp-past',f.support,'2000-01-01T00:00:00Z')],previous);
 // Empty INSERTED must not touch any parent/history.
 f=await createFixture(pool);const emptyInitial=await state(pool,f);await pool.request().query(`INSERT dbo.XULY_KHIEUNAI(KhieuNaiID,NguoiXuLyID,NoiDungXuLy,NgayXuLy,TrangThaiSauXuLy) SELECT ${f.ids[0]},${f.support},N'empty',dbo.fn_BayGio(),N'Đang xử lý' WHERE 1=0;`);assert.deepEqual(await state(pool,f),emptyInitial);e.cases.push({name:'empty-statement',initial:emptyInitial,final:await state(pool,f),session:await cleanSession(pool),status:'PASS'});await cleanupFixture(pool,f);f=null;
 for(const [name,change,number] of [['missing-parent',()=>({complaint:2147483647}),547],['missing-actor',()=>({actor:2147483647}),547],['invalid-status',()=>({status:'Chờ phản hồi'}),547],['initial-status-forbidden',()=>({status:'Mới'}),547],['customer-actor',f=>({actor:f.customer}),50005],['manager-actor',f=>({actor:f.manager}),50005],['null-content',()=>({content:null}),515]])await run(name,f=>[event(f,f.ids[0],'Đang xử lý','valid'),{...event(f,f.ids[1],'Đã đóng','invalid'),...change(f)}],previous,number);
 // Alias delegates the same single-event flow; no processing UPDATE feature added.
 f=await createFixture(pool);const alias=await pool.request().input('NguoiDungID',sql.Int,f.support).input('KhieuNaiID',sql.Int,f.ids[0]).input('NoiDungXuLy',sql.NVarChar(sql.MAX),'legacy alias').input('TrangThaiSauXuLy',sql.NVarChar(50),'Đã giải quyết').execute('dbo.sp_XuLyKhieuNai');assertLatest(await state(pool,f),[f.ids[0]]);e.cases.push({name:'legacy-alias',returned:alias.recordset,final:await state(pool,f),session:await cleanSession(pool),status:'PASS'});await cleanupFixture(pool,f);f=null;
 // Observe actual new parent statuses under a caller transaction, then rollback.
 f=await createFixture(pool);await previous(f);let initial=await state(pool,f);await pool.request().batch('SET XACT_ABORT OFF;BEGIN TRANSACTION;');const input=f.ids.slice(0,3).flatMap((id,i)=>[event(f,id,'Đang xử lý','roll-'+i+'a'),event(f,id,'Đã đóng','roll-'+i+'b')]);await bulk(pool,input);const inside=await state(pool,f),held=(await pool.request().batch('DECLARE @T INT=@@TRANCOUNT,@X INT=XACT_STATE();SELECT @T trancount,@X xactState;')).recordset[0];assert.deepEqual(held,{trancount:1,xactState:1});assertLatest(inside,f.ids.slice(0,3));assert.equal(inside.history.length,initial.history.length+6);await pool.request().batch('ROLLBACK;');assert.deepEqual(await state(pool,f),initial);e.rollback.push({name:'caller-batch-rollback',input,initial,inside,held,final:await state(pool,f),session:await cleanSession(pool),status:'PASS'});
 await pool.request().batch(`EXEC sys.sp_set_session_context @key=N'R33_Target',@value=${f.ids[0]};`);await batches(pool,read(path.join(root,'database/11_tests/complaints/processing_rollback.sql')));
 try{
  await assert.rejects(bulk(pool,input),r=>r.number===51034);const observed=JSON.parse((await pool.request().query("SELECT CONVERT(NVARCHAR(4000),SESSION_CONTEXT(N'R33_Observed')) observed")).recordset[0].observed);assert.equal(observed.length,3);assert.ok(observed.every(x=>x.TrangThai==='Đã đóng'));assert.deepEqual(await state(pool,f),initial);e.rollback.push({name:'trigger-after-parent-update-batch-failure',sqlError:51034,observed,initial,final:await state(pool,f),session:await cleanSession(pool),status:'PASS'});
  for(const role of ['support','admin'])for(const kind of ['processing','status']){await pool.request().batch('SET XACT_ABORT OFF;BEGIN TRANSACTION;');await assert.rejects(kind==='processing'?processing(pool,f,role,f.ids[0],'Từ chối'):updateStatus(pool,f,role,f.ids[0],'Đã đóng'),r=>r.number===51034);assert.deepEqual(await state(pool,f),initial);e.rollback.push({name:'canonical-caller-trigger-failure-'+role+'-'+kind,sqlError:51034,initial,final:await state(pool,f),session:await cleanSession(pool),status:'PASS'});}
 }finally{await pool.request().batch('IF @@TRANCOUNT>0 ROLLBACK;DROP TRIGGER IF EXISTS dbo.R33_ParentFailure;');}
 await cleanupFixture(pool,f);f=null;const after=await snapshot(pool);assert.deepEqual(summarize(after),summarize(before));e.before=summarize(before);e.after=summarize(after);e.cleanup='PASS';e.status='PASS';
}catch(error){e.status='FAIL';e.error={message:error.message,number:error.number};throw error;}
finally{await pool.request().batch('IF @@TRANCOUNT>0 ROLLBACK;DROP TRIGGER IF EXISTS dbo.R33_ParentFailure;');if(f)await cleanupFixture(pool,f);e.completedAt=new Date().toISOString();write(path.join(evidenceRoot,'sql-tests.json'),e);await pool.close();}
console.log(`PASS complaint SQL:${e.cases.length} positive/negative cases,${e.rollback.length} actual rollback cases;all parents/history/27-table and schema cleanup verified.`);
