ALTER TABLE dbo.[BANGGIA] ADD CONSTRAINT [PK_BANGGIA] PRIMARY KEY CLUSTERED ([GiaID] ASC);
GO
ALTER TABLE dbo.[CHITIETDOAN] ADD CONSTRAINT [PK_CHITIETDOAN] PRIMARY KEY CLUSTERED ([ChiTietDoAnID] ASC);
GO
ALTER TABLE dbo.[CHITIETVE] ADD CONSTRAINT [PK_CHITIETVE] PRIMARY KEY CLUSTERED ([VeID] ASC);
GO
ALTER TABLE dbo.[DANHGIAPHIM] ADD CONSTRAINT [PK_DANHGIAPHIM] PRIMARY KEY CLUSTERED ([DanhGiaID] ASC);
GO
ALTER TABLE dbo.[DIENVIEN] ADD CONSTRAINT [PK_DIENVIEN] PRIMARY KEY CLUSTERED ([DienVienID] ASC);
GO
ALTER TABLE dbo.[DONDATVE] ADD CONSTRAINT [PK_DONDATVE] PRIMARY KEY CLUSTERED ([DonDatVeID] ASC);
GO
ALTER TABLE dbo.[GHE] ADD CONSTRAINT [PK_GHE] PRIMARY KEY CLUSTERED ([GheID] ASC);
GO
ALTER TABLE dbo.[HINHANH_RAPCHIEUPHIM] ADD CONSTRAINT [PK_HINHANH_RAPCHIEUPHIM] PRIMARY KEY CLUSTERED ([HinhAnhRapID] ASC);
GO
ALTER TABLE dbo.[HOSOKHACHHANG] ADD CONSTRAINT [PK_HOSOKHACHHANG] PRIMARY KEY CLUSTERED ([NguoiDungID] ASC);
GO
ALTER TABLE dbo.[KHIEUNAI] ADD CONSTRAINT [PK_KHIEUNAI] PRIMARY KEY CLUSTERED ([KhieuNaiID] ASC);
GO
ALTER TABLE dbo.[KHUYENMAI] ADD CONSTRAINT [PK_KHUYENMAI] PRIMARY KEY CLUSTERED ([KhuyenMaiID] ASC);
GO
ALTER TABLE dbo.[NGUOIDUNG] ADD CONSTRAINT [PK_NGUOIDUNG] PRIMARY KEY CLUSTERED ([NguoiDungID] ASC);
GO
ALTER TABLE dbo.[PHANCONG_RAP] ADD CONSTRAINT [PK_PHANCONG_RAP] PRIMARY KEY CLUSTERED ([PhanCongID] ASC);
GO
ALTER TABLE dbo.[PHIM] ADD CONSTRAINT [PK_PHIM] PRIMARY KEY CLUSTERED ([PhimID] ASC);
GO
ALTER TABLE dbo.[PHIM_DIENVIEN] ADD CONSTRAINT [PK_PHIM_DIENVIEN] PRIMARY KEY CLUSTERED ([PhimID] ASC, [DienVienID] ASC);
GO
ALTER TABLE dbo.[PHIM_THELOAI] ADD CONSTRAINT [PK_PHIM_THELOAI] PRIMARY KEY CLUSTERED ([PhimID] ASC, [TheLoaiID] ASC);
GO
ALTER TABLE dbo.[PHONGCHIEU] ADD CONSTRAINT [PK_PHONGCHIEU] PRIMARY KEY CLUSTERED ([PhongID] ASC);
GO
ALTER TABLE dbo.[QUYEN] ADD CONSTRAINT [PK_QUYEN] PRIMARY KEY CLUSTERED ([QuyenID] ASC);
GO
ALTER TABLE dbo.[RAPCHIEUPHIM] ADD CONSTRAINT [PK_RAPCHIEUPHIM] PRIMARY KEY CLUSTERED ([RapID] ASC);
GO
ALTER TABLE dbo.[SANPHAM] ADD CONSTRAINT [PK_SANPHAM] PRIMARY KEY CLUSTERED ([SanPhamID] ASC);
GO
ALTER TABLE dbo.[SUATCHIEU] ADD CONSTRAINT [PK_SUATCHIEU] PRIMARY KEY CLUSTERED ([SuatChieuID] ASC);
GO
ALTER TABLE dbo.[THANHTOAN] ADD CONSTRAINT [PK_THANHTOAN] PRIMARY KEY CLUSTERED ([ThanhToanID] ASC);
GO
ALTER TABLE dbo.[THELOAI] ADD CONSTRAINT [PK_THELOAI] PRIMARY KEY CLUSTERED ([TheLoaiID] ASC);
GO
ALTER TABLE dbo.[VAITRO] ADD CONSTRAINT [PK_VAITRO] PRIMARY KEY CLUSTERED ([VaiTroID] ASC);
GO
ALTER TABLE dbo.[VAITRO_QUYEN] ADD CONSTRAINT [PK_VAITRO_QUYEN] PRIMARY KEY CLUSTERED ([VaiTroID] ASC, [QuyenID] ASC);
GO
ALTER TABLE dbo.[XULY_KHIEUNAI] ADD CONSTRAINT [PK_XULY_KHIEUNAI] PRIMARY KEY CLUSTERED ([XuLyID] ASC);
GO
ALTER TABLE dbo.[CHITIETDOAN] ADD CONSTRAINT [UQ_CHITIETDOAN_Don_SanPham] UNIQUE NONCLUSTERED ([DonDatVeID] ASC, [SanPhamID] ASC);
GO
ALTER TABLE dbo.[CHITIETVE] ADD CONSTRAINT [UQ_CHITIETVE_MaVe] UNIQUE NONCLUSTERED ([MaVe] ASC);
GO
ALTER TABLE dbo.[DANHGIAPHIM] ADD CONSTRAINT [UQ_DANHGIAPHIM_Phim_User] UNIQUE NONCLUSTERED ([PhimID] ASC, [NguoiDungID] ASC);
GO
ALTER TABLE dbo.[GHE] ADD CONSTRAINT [UQ_GHE_ViTri] UNIQUE NONCLUSTERED ([PhongID] ASC, [HangGhe] ASC, [SoGhe] ASC);
GO
ALTER TABLE dbo.[KHUYENMAI] ADD CONSTRAINT [UQ_KHUYENMAI_MaCode] UNIQUE NONCLUSTERED ([MaCode] ASC);
GO
ALTER TABLE dbo.[NGUOIDUNG] ADD CONSTRAINT [UQ_NGUOIDUNG_Email] UNIQUE NONCLUSTERED ([Email] ASC);
GO
ALTER TABLE dbo.[PHONGCHIEU] ADD CONSTRAINT [UQ_PHONGCHIEU_TenPhong] UNIQUE NONCLUSTERED ([RapID] ASC, [TenPhong] ASC);
GO
ALTER TABLE dbo.[QUYEN] ADD CONSTRAINT [UQ_QUYEN_MaQuyen] UNIQUE NONCLUSTERED ([MaQuyen] ASC);
GO
ALTER TABLE dbo.[THELOAI] ADD CONSTRAINT [UQ_THELOAI_TenTheLoai] UNIQUE NONCLUSTERED ([TenTheLoai] ASC);
GO
ALTER TABLE dbo.[VAITRO] ADD CONSTRAINT [UQ_VAITRO_MaVaiTro] UNIQUE NONCLUSTERED ([MaVaiTro] ASC);
GO
