ALTER TABLE dbo.[BANGGIA] WITH CHECK ADD CONSTRAINT [FK_BANGGIA_Rap] FOREIGN KEY ([RapID]) REFERENCES dbo.[RAPCHIEUPHIM] ([RapID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[CHITIETDOAN] WITH CHECK ADD CONSTRAINT [FK_CHITIETDOAN_DonDatVe] FOREIGN KEY ([DonDatVeID]) REFERENCES dbo.[DONDATVE] ([DonDatVeID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[CHITIETDOAN] WITH CHECK ADD CONSTRAINT [FK_CHITIETDOAN_SanPham] FOREIGN KEY ([SanPhamID]) REFERENCES dbo.[SANPHAM] ([SanPhamID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[CHITIETVE] WITH CHECK ADD CONSTRAINT [FK_CHITIETVE_DonDatVe] FOREIGN KEY ([DonDatVeID]) REFERENCES dbo.[DONDATVE] ([DonDatVeID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[CHITIETVE] WITH CHECK ADD CONSTRAINT [FK_CHITIETVE_Ghe] FOREIGN KEY ([GheID]) REFERENCES dbo.[GHE] ([GheID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[DANHGIAPHIM] WITH CHECK ADD CONSTRAINT [FK_DANHGIAPHIM_NguoiDung] FOREIGN KEY ([NguoiDungID]) REFERENCES dbo.[NGUOIDUNG] ([NguoiDungID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[DANHGIAPHIM] WITH CHECK ADD CONSTRAINT [FK_DANHGIAPHIM_Phim] FOREIGN KEY ([PhimID]) REFERENCES dbo.[PHIM] ([PhimID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[DONDATVE] WITH CHECK ADD CONSTRAINT [FK_DONDATVE_KhuyenMai] FOREIGN KEY ([KhuyenMaiID]) REFERENCES dbo.[KHUYENMAI] ([KhuyenMaiID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[DONDATVE] WITH CHECK ADD CONSTRAINT [FK_DONDATVE_NguoiDung] FOREIGN KEY ([NguoiDungID]) REFERENCES dbo.[NGUOIDUNG] ([NguoiDungID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[DONDATVE] WITH CHECK ADD CONSTRAINT [FK_DONDATVE_SuatChieu] FOREIGN KEY ([SuatChieuID]) REFERENCES dbo.[SUATCHIEU] ([SuatChieuID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[GHE] WITH CHECK ADD CONSTRAINT [FK_GHE_Phong] FOREIGN KEY ([PhongID]) REFERENCES dbo.[PHONGCHIEU] ([PhongID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[HINHANH_RAPCHIEUPHIM] WITH CHECK ADD CONSTRAINT [FK_HINHANH_RAPCHIEUPHIM_Rap] FOREIGN KEY ([RapID]) REFERENCES dbo.[RAPCHIEUPHIM] ([RapID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[HOSOKHACHHANG] WITH CHECK ADD CONSTRAINT [FK_HOSOKHACHHANG_NguoiDung] FOREIGN KEY ([NguoiDungID]) REFERENCES dbo.[NGUOIDUNG] ([NguoiDungID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[KHIEUNAI] WITH CHECK ADD CONSTRAINT [FK_KHIEUNAI_DonDatVe] FOREIGN KEY ([DonDatVeID]) REFERENCES dbo.[DONDATVE] ([DonDatVeID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[KHIEUNAI] WITH CHECK ADD CONSTRAINT [FK_KHIEUNAI_NguoiDung] FOREIGN KEY ([NguoiDungID]) REFERENCES dbo.[NGUOIDUNG] ([NguoiDungID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[NGUOIDUNG] WITH CHECK ADD CONSTRAINT [FK_NGUOIDUNG_VaiTro] FOREIGN KEY ([VaiTroID]) REFERENCES dbo.[VAITRO] ([VaiTroID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[PHANCONG_RAP] WITH CHECK ADD CONSTRAINT [FK_PHANCONG_RAP_NguoiDung] FOREIGN KEY ([NguoiDungID]) REFERENCES dbo.[NGUOIDUNG] ([NguoiDungID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[PHANCONG_RAP] WITH CHECK ADD CONSTRAINT [FK_PHANCONG_RAP_Rap] FOREIGN KEY ([RapID]) REFERENCES dbo.[RAPCHIEUPHIM] ([RapID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[PHIM_DIENVIEN] WITH CHECK ADD CONSTRAINT [FK_PHIM_DIENVIEN_DienVien] FOREIGN KEY ([DienVienID]) REFERENCES dbo.[DIENVIEN] ([DienVienID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[PHIM_DIENVIEN] WITH CHECK ADD CONSTRAINT [FK_PHIM_DIENVIEN_Phim] FOREIGN KEY ([PhimID]) REFERENCES dbo.[PHIM] ([PhimID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[PHIM_THELOAI] WITH CHECK ADD CONSTRAINT [FK_PHIM_THELOAI_Phim] FOREIGN KEY ([PhimID]) REFERENCES dbo.[PHIM] ([PhimID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[PHIM_THELOAI] WITH CHECK ADD CONSTRAINT [FK_PHIM_THELOAI_TheLoai] FOREIGN KEY ([TheLoaiID]) REFERENCES dbo.[THELOAI] ([TheLoaiID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[PHONGCHIEU] WITH CHECK ADD CONSTRAINT [FK_PHONGCHIEU_Rap] FOREIGN KEY ([RapID]) REFERENCES dbo.[RAPCHIEUPHIM] ([RapID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[SUATCHIEU] WITH CHECK ADD CONSTRAINT [FK_SUATCHIEU_Phim] FOREIGN KEY ([PhimID]) REFERENCES dbo.[PHIM] ([PhimID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[SUATCHIEU] WITH CHECK ADD CONSTRAINT [FK_SUATCHIEU_Phong] FOREIGN KEY ([PhongID]) REFERENCES dbo.[PHONGCHIEU] ([PhongID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[THANHTOAN] WITH CHECK ADD CONSTRAINT [FK_THANHTOAN_DonDatVe] FOREIGN KEY ([DonDatVeID]) REFERENCES dbo.[DONDATVE] ([DonDatVeID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[VAITRO_QUYEN] WITH CHECK ADD CONSTRAINT [FK_VAITRO_QUYEN_Quyen] FOREIGN KEY ([QuyenID]) REFERENCES dbo.[QUYEN] ([QuyenID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[VAITRO_QUYEN] WITH CHECK ADD CONSTRAINT [FK_VAITRO_QUYEN_VaiTro] FOREIGN KEY ([VaiTroID]) REFERENCES dbo.[VAITRO] ([VaiTroID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[XULY_KHIEUNAI] WITH CHECK ADD CONSTRAINT [FK_XULY_KHIEUNAI_KhieuNai] FOREIGN KEY ([KhieuNaiID]) REFERENCES dbo.[KHIEUNAI] ([KhieuNaiID]) ON DELETE CASCADE ON UPDATE NO ACTION;
GO
ALTER TABLE dbo.[XULY_KHIEUNAI] WITH CHECK ADD CONSTRAINT [FK_XULY_KHIEUNAI_NguoiXuLy] FOREIGN KEY ([NguoiXuLyID]) REFERENCES dbo.[NGUOIDUNG] ([NguoiDungID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO
