import fs from 'node:fs';
import path from 'node:path';
import {root,out,save} from './collect.mjs';
import {PROCEDURES} from '../../backend/src/db/procedures.js';
const dir=path.dirname(out),read=n=>JSON.parse(fs.readFileSync(path.join(out,n),'utf8'));
const write=(name,body)=>fs.writeFileSync(path.join(dir,name),body);
const ev=n=>`[${n}](./evidence/${n})`;
const src=(file,needle)=>{if(!file)return '—';const s=fs.readFileSync(path.join(root,file),'utf8');const i=needle?s.indexOf(needle):-1;const line=i>=0?s.slice(0,i).split('\n').length:1;const target=`../../${file}#L${line}`;return `[${file}:${line}](${file.includes(' ')?'<'+target+'>':target})`;};
const table=(heads,rows)=>`| ${heads.join(' | ')} |\n| ${heads.map(()=> '---').join(' | ')} |\n${rows.map(r=>`| ${r.map(x=>String(x??'—').replaceAll('|','\\|').replaceAll('\n','<br>')).join(' | ')} |`).join('\n')}\n`;
const modules=read('complete-module-audit.json'),objects=read('live-objects.json'),columns=read('live-columns.json'),fks=read('live-foreign-keys.json'),checks=read('live-checks.json'),indexes=read('live-indexes.json'),fixtures=read('fixture-manifest.json'),chains=read('api-chain-inventory.json'),drift=read('module-drift.json');
const bugs=[];
function bug(id,title,severity,confidence,uc,layer,rule,expected,actual,steps,evidence,db,be,fe,rootCause,fix,tests,impact='Không chứng minh truy cập trái quyền.',data='Không chứng minh sửa dữ liệu cũ qua hành vi này.'){
 bugs.push({id,title,severity,confidence,uc,layer,rule,expected,actual,steps,evidence,db,be,fe,rootCause,fix,tests,impact,data});
}
bug('BUG-001','DateTime2 local và UTC lệch 7 giờ','P1','PROVEN','KH-05, KH-07, KH-10, QLR-04/05, ADM-12/14','DB / BE / Integration','Giờ chiếu và hạn giữ ghế phải cùng hợp đồng thời gian.','10:00 +07 được lưu/hiển thị 10:00; hạn giữ ghế là đúng 5 phút theo cùng múi giờ.','Suất 57 gửi 10:00 +07 nhưng API startTime=03:00. Suất 60 gửi 17:00 +07 nhưng trả 10:00. bookedAt/HanGiuCho lưu giờ Việt Nam nhưng JSON gắn Z; ví dụ order 40 tạo thực tế 06:41 UTC, hạn giữ trả 13:46Z.','Xem request audit-showtime-create, wall-clock-contract-check và real-five-minute-expiry-order; so sánh với đồng hồ SQL local/UTC.', ['integration-transcript.json','supplemental-transcript.json','live-environment.json'],['sp_Showtime_GetDetail','fn_BayGio','sp_Booking_Create'],['backend/src/services/adminService.js','backend/src/services/managerService.js','backend/src/config/database.js'],['frontend/src/pages/ManagerPortal.jsx','frontend/src/pages/BookingPreparation.jsx'],'new Date(offset) đổi sang UTC; driver useUTC mặc định truyền UTC components vào datetime2 mang nghĩa local; đọc local datetime2 như UTC.','Thống nhất UTC hoặc giờ rạp xuyên DB/driver/DTO; không sửa dữ liệu lịch sử hàng loạt trước khi xác định nguồn.','+07/Z/datetime-local, qua nửa đêm, hold 5 phút, promo start/end và payment cutoff.',undefined,'Có thể đóng đặt/thanh toán trước giờ dự kiến 7 giờ; timestamp phía FE sai nghĩa.');
bug('BUG-002','Manager không đóng bán được và enum sai gây 500','P2','PROVEN','QLR-05','BE / Integration','Trạng thái suất theo CK_SUATCHIEU_TrangThai.','Đóng bán được chấp nhận; Tạm ngừng trả 400.','Đóng bán trả 400; Tạm ngừng vượt validator rồi SQL CHECK lỗi, HTTP 500.','Gọi manager-close-correct-domain và manager-pause-wrong-domain trên suất audit 58.',['integration-transcript.json'],['CK_SUATCHIEU_TrangThai','sp_Manager_Showtime_Update'],['backend/src/validators/managerValidator.js','backend/src/services/managerService.js'],['frontend/src/pages/ManagerPortal.jsx'],'SHOWTIME_STATUSES chứa Tạm ngừng thay Đóng bán; thiếu mapping 547.','Đồng bộ domain và map CHECK thành lỗi client.','Toàn bộ enum hợp lệ/không hợp lệ và trạng thái null.');
bug('BUG-003','Lỗi lifecycle database mới không được map','P2','PROVEN','QLR-04/05, ADM-14','BE / Integration','Validation nghiệp vụ phải trả 400/409 với thông báo có thể xử lý.','Suất ngắn hơn phim bị từ chối bằng lỗi nghiệp vụ.','manager-short-duration trả 500 EREQUEST; live sp_Showtime_ValidateTimes có THROW mới mà service không xử lý.','POST suất dài 1 phút cho phim audit 90 phút.',['integration-transcript.json','live-objects.json'],['sp_Showtime_ValidateTimes'],['backend/src/services/managerService.js','backend/src/services/adminService.js'],['frontend/src/pages/ManagerPortal.jsx'],'BE của commit 7c3562 không có đầy đủ error contract của DB 014/015.','Chọn baseline đồng bộ trước, rồi khai báo và kiểm tra mapping theo flow.','Mọi THROW lifecycle; phân biệt lỗi nhập, 404, xung đột và 500.');
bug('BUG-004','Manager UI gửi trường roomId không được phép khi tạo ghế','P1','PROVEN','QLR-03','FE / Integration','UI phải gọi đúng contract createSeat(roomId, body).','Body chỉ row, number, type.','UI trải {...seat} chứa roomId; API trả 400 UNKNOWN_REQUEST_FIELD; ghế không tạo.','Chọn phòng audit ManagerRoom → Ghế → nhập hàng UI → Tạo ghế.',['browser-manager-seat-error.png','browser-manager-seat-error.txt','browser-network.json','integration-transcript.json'],['sp_Manager_Seat_Create'],['backend/src/validators/managerValidator.js'],['frontend/src/pages/ManagerPortal.jsx'],'Spread cả state routing field vào payload.','Tạo payload theo contract; bổ sung busy/refresh cho form ghế.','Browser tạo ghế thật và đọc lại DB; unknown-field âm.');
bug('BUG-005','Admin UI sửa ảnh rạp luôn gửi cover ngoài contract','P1','PROVEN','ADM-07','FE / Integration','Sửa metadata ảnh và set cover là hai API contract.','PUT metadata không có cover.','Lưu ảnh đã chọn trả 400 UNKNOWN_REQUEST_FIELD.','Admin → Ảnh rạp → chọn rạp audit → Sửa → Lưu.',['browser-admin-image-update-error.png','browser-network.json'],['usp_Admin_CinemaImage_Update'],['backend/src/validators/adminValidator.js'],['frontend/src/components/CinemaImageManager.jsx'],'Update dùng spread form chứa cover, trong khi cover là PATCH riêng.','Tách payload create/update/setCover theo contract hiện hành.','Sửa URL/mô tả/order/status, cover PATCH, cover đang ẩn.');
bug('BUG-006','9 form sửa Admin không nạp trạng thái ban đầu','P1','PROVEN','ADM-02/07/08/09/11/12/13/14','FE / Integration','Form edit phải nạp các trường editOnly của bản ghi đang chọn.','Trạng thái ban đầu phản ánh TrangThai hiện tại.','Tài khoản, rạp, phòng, ghế, phim, sản phẩm, khuyến mãi, bảng giá, suất đều có status rỗng; Lưu mặc định rạp trả 400.','Chọn Sửa/Trạng thái của các fixture ID trong browser-admin-extra-checks.',['browser-admin-extra-checks.json','browser-admin-cinema-edit-error.png','browser-network.json'],['Các SP update Admin','Các CHECK TrangThai'],['backend/src/validators/adminValidator.js'],['frontend/src/pages/AdminPortal.jsx'],'onSelect tính rowValues từ editableFields của render selected=null, trước khi setSelected có hiệu lực.','Tính trường edit trực tiếp từ definition và bản ghi; dùng enum/select.','9 resource: chọn edit → không đổi status → lưu trường khác → DB status giữ nguyên.');
bug('BUG-007','Sửa tên vai trò báo thành công nhưng không lưu','P1','PROVEN','ADM-03','FE / Integration','Thay tên/mô tả vai trò phải UPDATE VAITRO.','Tên mới được lưu qua role update.','Tên UiRole không đổi; UI báo Đã lưu thay đổi và chỉ gọi role-permissions.','Admin → Vai trò → chọn audit UiRole → đổi tên → Lưu → GET roles.',['browser-checks.json','browser-network.json'],['sp_Admin_Role_Update','sp_Admin_RolePermission_Set'],['backend/src/services/adminService.js'],['frontend/src/pages/AdminPortal.jsx'],'Nhánh permissionIds !== undefined luôn thắng nhánh update role sau onSelect.','Tách thao tác role metadata và permissions; không báo thành công khi bỏ qua thay đổi.','Sửa tên, mô tả, quyền độc lập và cùng lúc.');
bug('BUG-008','Admin UI không gỡ được toàn bộ quyền','P2','PROVEN','ADM-05','FE / Integration','Danh sách quyền trống phải thành [].','Input trống gửi permissionIds: [].','split empty → Number(\'\')=0 → [0], API trả 400. API trực tiếp [] hoạt động.','Xóa hết nội dung QuyenID cần gán rồi Lưu.',['browser-admin-role-permission-error.png','supplemental-transcript.json'],['sp_Admin_RolePermission_Set'],['backend/src/validators/adminValidator.js'],['frontend/src/pages/AdminPortal.jsx'],'Parser giữ số 0 vì Number.isSafeInteger(0) true.','Parse empty thành [] và kiểm tra ID > 0.','Empty, whitespace, trùng ID, ID âm/0, permission đang xóa.');
bug('BUG-009','ID vượt SQL INT được nhận rồi trả 500','P2','PROVEN','ADM-08 và các path dùng cùng validator','BE / Integration','ID phải nằm trong miền SQL INT.','2147483648 trả 400.','POST rooms cinemaId 2147483648 trả 500 EPARAM.','Gọi integer-overflow trong transcript.',['integration-transcript.json'],['@RapID INT'],['backend/src/validators/adminValidator.js','backend/src/services/adminService.js'],[], 'Number.isSafeInteger không bảo đảm miền int32; Admin không map numeric parameter error.','Giới hạn ID <=2147483647 và map lỗi parameter.','Biên int32 trên body/path/query, Infinity, số phân số và string.');
bug('BUG-010','Số ghế phân số bị làm thành số nguyên','P2','PROVEN','ADM-08','BE / DB / Integration','SoGhe là số nguyên dương.','1.5 trả 400 và không có ghế mới.','API nhận number 1.5, driver INT tạo ghế F1 (GheID 302).','POST fractional-seat, đọc response và danh sách ghế.',['integration-transcript.json'],['GHE','usp_Admin_Seat_Create'],['backend/src/validators/adminValidator.js','backend/src/services/adminService.js'],['frontend/src/pages/AdminPortal.jsx'],'Rule positive kiểm tra số >0 nhưng không Number.isInteger.','Dùng rule integer cho số ghế, duration, quantity và display order.','1.5/-1/0/maxint, xác nhận không sinh dòng khi bị từ chối.',undefined,'Request và giá trị được lưu khác nhau.');
bug('BUG-011','Giới hạn tên Admin không khớp SQL parameter','P2','PROVEN','ADM-02/03/04/07/08/10/11','BE / Integration','Độ dài phải khớp contract từng resource.','Tên phòng >100 bị từ chối 400 trước RPC.','Tên phòng 124 ký tự qua validator name<=255 rồi RPC trả 500; các name parameter 100/150 khác cùng rủi ro.','POST overlength-room-name.',['supplemental-transcript.json','backend-sp-contract-capture.json'],['@TenPhong NVARCHAR(100)'],['backend/src/validators/adminValidator.js','backend/src/services/adminService.js'],['frontend/src/pages/AdminPortal.jsx'],'Một fieldMax name=255 dùng chung cho parameter 100/150; nhiều field khác thiếu bound tương ứng.','Schema validation riêng theo resource, gồm độ dài nvarchar/varchar và byte encoding.','room100/101, product150/151, role100/101; text MAX và description500 hợp lệ.');
bug('BUG-012','Sửa rạp không tồn tại trả 200 null','P2','PROVEN','ADM-07','DB / BE','UPDATE resource không tồn tại phải 404.','Không cập nhật và trả CINEMA_NOT_FOUND.','PUT /admin/cinemas/2147483647 trả 200 {cinema:null}.','Gọi missing-cinema trong transcript.',['integration-transcript.json'],['sp_Admin_Cinema_Update'],['backend/src/controllers/adminController.js','backend/src/services/adminService.js'],['frontend/src/pages/AdminPortal.jsx'],'SP UPDATE không kiểm tra existence; service.write nhận null vẫn trả success.','Kiểm existence ở SP hoặc contract trả not-found rõ ràng.','Missing ID từng CRUD, xác nhận UI không hiện saved thành công.');
bug('BUG-013','Ngày sinh tương lai được ghi vào hồ sơ','P2','PROVEN','KH-03','BE / DB','Ngày sinh hợp lệ không được nằm trong tương lai.','2999-01-01 bị từ chối.','PUT /auth/me trả 200 và lưu birthday tương lai cho fixture user 26; dữ liệu cũ user17 cũng có cùng dạng lỗi.','Gọi future-birthday-profile.',['supplemental-transcript.json','data-invalid-born-dates.json'],['HOSOKHACHHANG','sp_User_UpdateProfile'],['backend/src/validators/authValidator.js'],['frontend/src/pages/auth/Profile.jsx'],'Validator chỉ kiểm tra calendar date; không giới hạn <= ngày hiện tại.','Áp business date rule ở BE/SP và xử lý dữ liệu cũ theo xác minh.','Today, tomorrow, leap date, giới hạn tuổi theo chính sách đã duyệt.',undefined,'Hồ sơ có thông tin ngày sinh không thực tế.');
bug('BUG-014','Admin tạo mật khẩu 73 byte không đăng nhập được bằng mật khẩu gốc','P1','PROVEN','ADM-02','BE / Security / Integration','Create/login/hash phải dùng cùng quy tắc mật khẩu bcrypt.','Từ chối >72 byte khi tạo hoặc hỗ trợ cùng hợp đồng xác thực.','Create user thành công; login mật khẩu gốc trả 400; login tiền tố 72 byte trả 200.','admin-73-byte-password-create → original-password-login → truncated-password-login.',['additional-transcript.json','additional-checks.json'],['sp_Admin_User_Create'],['backend/src/validators/adminValidator.js','backend/src/validators/authValidator.js','backend/src/utils/password.js'],['frontend/src/pages/AdminPortal.jsx'],'Admin chấp nhận 8..128 ký tự, bcrypt cắt 72 byte, Login từ chối >72 byte.','Dùng cùng validation 8..72 byte trên mọi đường tạo tài khoản.','72/73 ASCII byte, Unicode vượt byte dù ít ký tự, không trim password ngoài ý định.','Mật khẩu được chấp nhận khác mật khẩu người dùng đã đặt.','Không thay đổi profile; tài khoản nội bộ bị kẹt login.');
bug('BUG-015','Admin tạo tài khoản khách hàng thiếu hồ sơ mở rộng','P2','PROVEN','ADM-02, KH-03','DB / BE','Luồng Admin tạo nhân sự và luồng register customer có contract riêng.','Chặn KHACH_HANG trên create staff hoặc tạo đầy đủ HOSOKHACHHANG trong transaction.','roleId4 tạo user34 MaVaiTro KHACH_HANG nhưng không có HOSOKHACHHANG.','POST admin-customer-role-create; query customer-profile-missing-after.',['supplemental-transcript.json','customer-profile-missing-after.json'],['sp_Admin_User_Create','NGUOIDUNG','HOSOKHACHHANG'],['backend/src/validators/adminValidator.js','backend/src/services/adminService.js'],['frontend/src/pages/AdminPortal.jsx'],'SP tạo bất kỳ role tồn tại nhưng chỉ INSERT NGUOIDUNG.','Xác định rõ role được phép; tạo atomic hồ sơ nếu thực sự hỗ trợ customer.','Allowed staff roles, customer role, custom role, profile/points invariants.',undefined,'Customer mới không đủ aggregate hồ sơ.');
bug('BUG-016','Booking bỏ silently sản phẩm không tồn tại','P2','PROVEN','KH-07/08','DB / BE / Integration','Đơn hàng phải phản ánh các sản phẩm được chọn hoặc báo unavailable.','Sản phẩm ID không tồn tại bị từ chối và rollback.','POST unknown-product-booking trả 201 nhưng productTotal=0, không có sản phẩm yêu cầu. Preview promo cùng sản phẩm có validation chặn, create booking không chặn.','Đặt ghế audit với products=[{productId:2147483647,quantity:1}].',['additional-transcript.json'],['sp_Booking_Create','SANPHAM','CHITIETDOAN'],['backend/src/services/bookingService.js'],['frontend/src/pages/BookingPreparation.jsx'],'INNER JOIN SANPHAM + WHERE Đang bán loại dòng sai mà không kiểm đủ cardinality.','Kiểm toàn bộ requested products tồn tại/đang bán trong cùng transaction.','Unknown/inactive product, mất hiệu lực giữa preview và submit, không tạo order/ticket khi thất bại.',undefined,'Đơn thiếu mặt hàng khách đã chọn.');
bug('BUG-017','Hai request phân công giống nhau tạo hai dòng','P2','PROVEN','ADM-06','DB / Integration','Không nhân đôi một phân công hoàn toàn giống nhau.','Một row, request còn lại conflict/idempotent.','Hai POST đồng thời đều200; PhanCongID13/14 cùng manager29, rạp41, bắt đầu2026-11-02, Hiệu lực.','assignment-create-concurrency-0/1; query assignment-duplicates-after.',['additional-transcript.json','assignment-duplicates-after.json'],['PHANCONG_RAP','sp_Admin_Assignment_Create'],['backend/src/services/adminService.js'],['frontend/src/pages/AdminPortal.jsx'],'Không unique key/business guard cho cùng user/rap/khoảng; SP INSERT đơn.','Chốt semantics overlap/historical assignment, thêm guard transaction và key phù hợp.','Same duplicate concurrent, future/expired, overlapping periods nếu không cho phép.',undefined,'Phân công lặp; không chứng minh Manager vượt rạp khác.');
bug('BUG-018','Số lượt đánh giá phim bị nhân theo số suất chiếu','P2','PROVEN','KH-04','DB / BE / Integration','Số lượt đánh giá phải bằng COUNT DANHGIAPHIM của phim.','Một đánh giá của phim audit trả reviewCount=1.','vw_ThongKePhim JOIN DANHGIAPHIM và SUATCHIEU cùng lúc rồi COUNT(dg.DanhGiaID); API phim audit trả số nhân theo số suất. Có3phim sai trong query.','So COUNT trực tiếp với view, gọi GET /movies/14.',['movie-review-count-multiplication.json','aggregates-transcript.json'],['vw_ThongKePhim','sp_Movie_List','sp_Movie_GetDetail'],['backend/src/services/catalogService.js'],['frontend/src/pages/MovieDetail.jsx'],'JOIN hai quan hệ 1-n trước aggregate; AVG không đổi khi lặp đồng đều, COUNT bị nhân.','Pre-aggregate từng nhánh hoặc COUNT DISTINCT reviewID.','0/1/n reviews ×0/1/n showtimes, list và detail consistency.',undefined,'Sai dữ liệu thống kê trả ra, không tăng actual review rows.');
bug('BUG-019','Các Customer API không kiểm permission chức năng','P1','HIGH-CONFIDENCE','KH-07/10/13/14, ADM-05','BE / Security','VAITRO_QUYEN xác định quyền chức năng theo thiết kế §1.1.','Thu hồi DAT_VE/THANH_TOAN/DANH_GIA/GUI_KHIEU_NAI phải chặn API tương ứng.','Routes chỉ authenticate + requireCustomer; SP booking kiểm active account, không kiểm DAT_VE. Chưa thu hồi quyền của role KHACH_HANG dùng chung để thử trên DB thật.','Đọc route compositions và core SP; không gọi kết quả là runtime bypass đã chứng minh.',['api-chain-inventory.json','live-objects.json'],['sp_Booking_Create','sp_Payment_CreateAttempt','sp_Review_Create'],['backend/src/routes/bookingRoutes.js','backend/src/routes/orderRoutes.js','backend/src/routes/movieRoutes.js','backend/src/routes/complaintRoutes.js'],['frontend/src/constants/roles.js'],'Customer role guard được dùng thay functional permission guard.','Định nghĩa permission từng endpoint, kiểm ở BE và SP có identity khi phù hợp.','Fresh isolated RBAC role: revoke permission→oldJWT denied; giữ role unchanged.','Rủi ro thu hồi quyền không có hiệu lực ở API customer; chưa chứng minh khai thác real DB.');
bug('BUG-020','FE chặn cả portal bằng một permission đại diện','P2','HIGH-CONFIDENCE','ADM-03..16, QLR-03..09, KH-10/14','FE / Security','Quyền từng chức năng độc lập với quyền vào một phân hệ khác.','User giữ quyền chức năng được vào màn hình tương ứng.','Orders/payment/complaints đều gated DAT_VE; Manager toàn portal QL_PHONG; Admin toàn portal QL_NGUOIDUNG. Không chạy đổi seeded permissions.','Đọc routes/ROLE_AREAS/RequireRole và so endpoint permission matrix.',['api-chain-inventory.json'],['VAITRO_QUYEN'],['backend/src/routes/adminRoutes.js','backend/src/routes/managerRoutes.js'],['frontend/src/routes/index.jsx','frontend/src/constants/roles.js'],'Area permission coarse được gán cho nhiều chức năng có permission khác.','Guard/chọn navigation theo từng function; server vẫn là authority.','Khách chỉ có GUI_KHIEU_NAI; Manager chỉ QL_SUATCHIEU; Admin chỉ report/role.');

save('findings-bugs.json',bugs);
write('FINDINGS.md','# Findings — audit only\n\nKhông áp dụng bất kỳ fix nào. PROVEN là có reproduction/evidence; HIGH-CONFIDENCE là source/metadata; SUSPECTED và BLOCKED không được xem là lỗi đã tái hiện.\n\n'+bugs.map(b=>`## ${b.id}\n\n**Title:** ${b.title}\n\n**Severity:** ${b.severity}\n\n**Confidence:** ${b.confidence}\n\n**Affected UC:** ${b.uc}\n\n**Layer:** ${b.layer}\n\n**Business Rule:** ${b.rule}\n\n**Expected:** ${b.expected}\n\n**Actual:** ${b.actual}\n\n**Steps to Reproduce:** ${b.steps}\n\n**Evidence:** ${b.evidence.map(ev).join(', ')}\n\n**DB Objects:** ${b.db.join(', ')||'—'}\n\n**Backend Files:** ${b.be.map(f=>src(f)).join(', ')||'—'}\n\n**Frontend Files:** ${b.fe.map(f=>src(f)).join(', ')||'—'}\n\n**Affected Data:** Chỉ các fixture mới dùng cho reproduction; các dòng tồn tại trước audit được ghi riêng trong DATA findings.\n\n**Security Impact:** ${b.impact}\n\n**Data Integrity Impact:** ${b.data}\n\n**Root Cause:** ${b.rootCause}\n\n**Recommended Fix:** ${b.fix}\n\n**Regression Tests Required:** ${b.tests}\n\n**DO NOT FIX IN THIS TASK.**\n`).join('\n'));

const gaps=[
 ['GAP-001','QLR-05','UI sửa suất chiếu','COMPLETE','PARTIAL','MISSING','VERIFIED','Không có action/form sửa; BE có route nhưng enum BUG-002.','P1','PROVEN','browser-checks.json'],
 ['GAP-002','QLR-02/03','Sửa tên/loại phòng và loại ghế theo đặc tả','COMPLETE','COMPLETE','PARTIAL','VERIFIED','UI chỉ đổi trạng thái phòng/ghế; tạo ghế còn BUG-004.','P2','PROVEN','browser-manager-seat-error.txt'],
 ['GAP-003','QLR-07','Chọn loại ngày, định dạng, ngày kết thúc và sửa phụ thu','COMPLETE','COMPLETE','PARTIAL','VERIFIED','UI chỉ expose seatType/surcharge/start; dayType=Ngày thường, format=2D cố định, endsOn rỗng; update chỉ toggle status.','P2','HIGH-CONFIDENCE','browser-checks.json'],
 ['GAP-004','QLR-09','Chọn khoảng ngày báo cáo','COMPLETE','COMPLETE','MISSING','VERIFIED','Manager UI không có date filter; API đã hỗ trợ range.','P2','PROVEN','browser-checks.json'],
 ['GAP-005','CSKH-04','Đối chiếu đầy đủ đơn tham chiếu: tiền, suất, ghế, giao dịch','PARTIAL','PARTIAL','PARTIAL','VERIFIED','API trả row view với money/seat summary; không recordsets tickets/payments. CSKH UI chỉ id và status.','P2','PROVEN','browser-support-detail.txt'],
 ['GAP-006','ADM-07 / KH-05','Public gallery ảnh rạp','COMPLETE','COMPLETE','MISSING','VERIFIED','API GET cinema/images có dữ liệu thật; FE public chỉ cover/fallback, export getCinemaImages không có component gallery sử dụng.','P2','HIGH-CONFIDENCE','integration-transcript.json'],
 ['GAP-007','Nhiều UC','Real DB/browser regression suite trong repo','PARTIAL','PARTIAL','PARTIAL','NOT VERIFIED','116 test có sẵn chủ yếu stub/source assertion/SSR. SQL suites có direct INSERT và stress sweeper không phù hợp database đang dùng; không chạy nguyên bản.','P2','PROVEN','backend-tests.txt'],
];
save('findings-gaps.json',gaps);
fs.appendFileSync(path.join(dir,'FINDINGS.md'),'\n# Functional gaps\n\n'+gaps.map(g=>`## ${g[0]}\n\n**Severity / Confidence:** ${g[8]} / ${g[9]}\n\n**UC:** ${g[1]}\n\n**Required feature:** ${g[2]}\n\n**DB:** ${g[3]}\n\n**Backend:** ${g[4]}\n\n**Frontend:** ${g[5]}\n\n**Integration:** ${g[6]}\n\n**Impact:** ${g[7]}\n\n**Evidence:** ${ev(g[10])}\n`).join('\n'));
const conflicts=[
 ['CONFLICT-001','KH-10 / QLR-06 / ADM-14: không refund, không hủy đơn đã thanh toán','sp_Showtime_CancelCascade hủy paid order, đổi payment Thành công→Đã hoàn tiền, giảm points.','BE commit7c3562 cho phép gọi cancel wrapper DB mới và trả200.','Confirmation nói active hold sẽ từ chối; order/payment DTO không giải thích refund lifecycle mới.','KH-10 hiện hành nói không refund; source013 cancel guard. Đoạn mô hình §3.6 có nhắc refund, tự mâu thuẫn.','Test hủy suất57 đã paid order36 trả200; payment lịch sử bị đổi trạng thái.','Theo scope hiện hành và KH-10: không hủy paid order, không refund; nếu thay đổi phải cập nhật thiết kế và bảo toàn event lịch sử.','P1','PROVEN','integration-transcript.json'],
 ['CONFLICT-002','KH-10: success đến muộn được ghi nhận nếu ghế còn trống/suất còn mở','Live sp_Payment_UpdateResult014 từ chối mọi late success với50111.','Map409 ORDER_HOLD_EXPIRED.','Khách không hoàn tất attempt đã bắt đầu trước hạn.','KH-10 nêu rõ cho phép late success có kiểm seat collision; source002 có policy này.','Order40 attempt18 trước hạn; callback sau hơn5phút nhận409 dù ghế chưa bán cho người khác.','Áp policy late callback hiện hành hoặc sửa scope có quyết định rõ ràng; mô phỏng hiện tại không phải gateway thật.','P1','PROVEN','additional-transcript.json'],
 ['CONFLICT-003','Baseline source phải phản ánh database deploy','35module khác và6DB-only,2cột order mới.','BE/source dừng migration013, DB definitions ghi014/015.','Portal/form/enum theo contract trước.','DeployCommon chỉ001..013,007 intentionally absent.','Git rollback chỉ rollback code; không rollback SQL Server.','Chọn version DB tương ứng commit hoặc khôi phục migration mới qua task riêng có review; audit không deploy/reset DB.','P1','PROVEN','module-drift.json'],
 ['CONFLICT-004','45 UC, ADM-17 đã bị gỡ','Không CAUHINH_HE_THONG hoặc sp_Admin_Config.','Không route config.','Không mục Cấu hình hệ thống.','Actor overview §2.1 vẫn có mục thứ17; UCtables và roadmap45. README mô tả Phase2/3 và portal còn là tương lai.','Documentation chậm hơn implementation và scope.','45UC; bỏ mục obsolete trong task docs riêng, giữ lời giải thích removal.','P3','PROVEN','documentation-inventory.json'],
 ['CONFLICT-005','Phân quyền theo VAITRO_QUYEN và vai trò','fn_KiemTraQuyenNguoiDung cho ADMIN bypass; nhiều Admin SP không nhận actor id.','HTTP Admin vẫn requirePermission, Customer thiếu permission guard (BUG-019).','Coarse area permission (BUG-020).','Thiết kế §1.1 xác định permission chức năng; Admin global nghĩa phạm vi tất cả rạp, chưa đồng nghĩa bypass mọi functional permission.','Ba tầng không có một policy thống nhất với partial grants.','Chốt semantics Admin bypass và functional grant; kiểm cả API và DB caller theo policy đã duyệt.','P2','HIGH-CONFIDENCE','api-chain-inventory.json'],
];
save('findings-conflicts.json',conflicts);
fs.appendFileSync(path.join(dir,'FINDINGS.md'),'\n# Business rule conflicts\n\n'+conflicts.map(c=>`## ${c[0]}\n\n**Severity / Confidence:** ${c[8]} / ${c[9]}\n\n**Rule:** ${c[1]}\n\n**DB behavior:** ${c[2]}\n\n**Backend behavior:** ${c[3]}\n\n**Frontend behavior:** ${c[4]}\n\n**Documentation:** ${c[5]}\n\n**Conflict:** ${c[6]}\n\n**Correct rule based on current design:** ${c[7]}\n\n**Impact:** Sai lifecycle/scope hoặc không thể xác nhận tương thích deployment.\n\n**Evidence:** ${ev(c[10])}\n`).join('\n'));
const data=[
 ['DATA-001','DONDATVE','1 dòng: DonDatVeID20 (đã tồn tại trước audit)','80,000+0−120,000 = −40,000','0<=discount<=subtotal, tổng dương','Không đủ evidence xác định nguồn; current SP có clamp99% nhưng CHECK chỉ từng cột.','KH-07/09/10/11/12','P0','PROVEN','Giá trị tài chính không hợp lệ; order hiện đã Hết hạn, chưa chứng minh đã thu tiền âm.','Đối chiếu chứng từ/log trước khi sửa; không tự sửa discount lịch sử.','data-order-totals.json'],
 ['DATA-002','DONDATVE/SUATCHIEU','3 dòng cũ: orders26,27,28; show34','Paid orders gắn show Đã hủy','Không hủy suất có paid order theo KH-10','Nguồn chưa chứng minh; rollback source không đổi DB/data.','KH-10/12, QLR-06, ADM-14','P1','PROVEN','Vé đã bán của lịch hủy; lifecycle và report không nhất quán.','Đối chiếu từng transaction; xác định chính sách xử lý trước khi sửa.','data-paid-cancelled-showtime.json'],
 ['DATA-003','SUATCHIEU/PHIM','15 dòng cũ: IDs6,7,8,28,33,34,35,36,39,40,41,43,44,45,48','Dài ngắn hơn ThoiLuong phim; có cả cancelled/history và Mở bán','Rule duration theo live ValidateTimes/đặc tả lịch chiếu','Seed/test cũ hoặc thay đổi phim; chưa có mutation log.','KH-05, QLR-04/05, ADM-14','P2','PROVEN','Lịch đang mở có thể không đủ thời lượng; đừng sửa cancelled history như lịch tương lai.','Phân loại current/history, xác minh duration đúng và lineage trước sửa.','data-showtime-duration.json'],
 ['DATA-004','SUATCHIEU/PHIM','4 dòng cũ: IDs6,7,8,43','Chiếu ngoài releaseDate/endDate','Ngày chiếu trong thời gian phát hành theo live validator','Chưa xác định;3show đã hủy và1show ngoài thời gian phim.','KH-05, QLR-04/05, ADM-14','P2','PROVEN','Dữ liệu lịch không hợp lệ theo rule mới.','Đánh giá riêng lịch đã hủy và lịch còn mở, giữ evidence lịch sử.','data-showtime-movie-dates.json'],
 ['DATA-005','HOSOKHACHHANG','1 dòng cũ user17;1fixture user26 được API chấp nhận','Ngày sinh2999-01-01','Ngày sinh<=ngày hiện tại','BUG-013 tái hiện qua API; nguồn user17 chưa xác định.','KH-03','P2','PROVEN','Hồ sơ sai ngày sinh.','Xác minh chủ hồ sơ; không tự suy diễn ngày đúng.','data-invalid-born-dates.json'],
 ['DATA-006','NGUOIDUNG/HOSOKHACHHANG','2dòng lúc kết thúc: user21ngoài manifest và user34fixture','Role KHACH_HANG không có profile','Customer aggregate có HOSOKHACHHANG','User34: Admincreate trực tiếp role4, BUG-015; user21nguồn chưa xác định.','ADM-02, KH-03','P2','PROVEN','Profile/loyalty thiếu; account21đã có trước run này theo ID/email khác prefix.','Đối chiếu luồng tạo tài khoản và thông tin profile trước backfill.','customer-profile-missing-after.json'],
 ['DATA-007','PHANCONG_RAP','1nhóm activefixture gồm13/14;1nhóm cancelledcũ user3/rap3 cũng lặp hoàn toàn','Cùng user,cinema,start,end,status hai dòng','Không duplicate cùng assignment identity','Activefixture chứng minh BUG-017; nhóm cancelled cũ không nằm trong query active baseline.','ADM-06, QLR-01..09','P2','PROVEN','List/scope có dữ liệu lặp; chưa chứng minh breach phạm vi.','Chốt identity/overlap semantics rồi hợp nhất có lưu audit trail.','assignment-duplicates-after.json'],
 ['DATA-008','KHUYENMAI','3dòng cũ:1counter16vs2orders;2counter20vs0;3counter5vs0','Counter khác số đơn hiện lưu','Phải giải thích được counter theo lifetime usage/seed/history','Seed đã có counters5/20; currentRows không chứng minh toàn bộ lifetime usage.','KH-09, ADM-12','P3','SUSPECTED','Chưa đủ bằng chứng gọi là counter corrupt.','Đối chiếu seed, expired/cancelled policy và history; không reset counter theo COUNT hiện tại.','data-promotion-counter.json'],
 ['DATA-009','SUATCHIEU','6dòng cũ đã qua giờ kết thúc vẫn Mở bán','Lifecycle status chưa đóng lịch cũ','Phân biệt sale availability với status materialized','Booking có time guard nên vẫn chặn; không có job hoàn tất suất tương ứng.','KH-05, QLR-08, ADM-14','P3','PROVEN','Stale trạng thái; chưa chứng minh vẫn bán được suất quá giờ.','Quyết định materialized lifecycle/derived availability và bảo toàn lịch sử.','data-stale-open-showtimes.json'],
];
save('findings-data.json',data);
fs.appendFileSync(path.join(dir,'FINDINGS.md'),'\n# Data defects and observations\n\n'+data.map(d=>`## ${d[0]}\n\n**Severity / Confidence:** ${d[7]} / ${d[8]}\n\n**Table:** ${d[1]}\n\n**Rows affected:** ${d[2]}\n\n**Invalid condition:** ${d[3]}\n\n**Expected rule:** ${d[4]}\n\n**Likely source:** ${d[5]}\n\n**Affected UC:** ${d[6]}\n\n**Risk:** ${d[9]}\n\n**Suggested remediation:** ${d[10]}\n\n**Evidence:** ${ev(d[11])}\n`).join('\n'));

const schemaBody=objects.filter(o=>o.type.trim()==='U').map(o=>{const cs=columns.filter(c=>c.tableName===o.name),ix=indexes.filter(i=>i.tableName===o.name);return`## ${o.name}\n\n${table(['Column','Type','Nullable','Identity/computed','Default'],cs.map(c=>[c.name,c.typeName+(c.max_length===-1?'(MAX)':/char/.test(c.typeName)?`(${c.typeName.startsWith('n')?c.max_length/2:c.max_length})`:/decimal/.test(c.typeName)?`(${c.precision},${c.scale})`:''),c.is_nullable,c.is_identity?'IDENTITY':c.is_computed?'COMPUTED':'—',c.defaultDefinition??c.computedDefinition]))}\n**FK:** ${fks.filter(f=>f.childTable===o.name).map(f=>`${f.name}: ${f.childColumn}→${f.parentTable}.${f.parentColumn}; DELETE ${f.delete_referential_action_desc}; trusted=${!f.is_not_trusted}`).join('; ')||'—'}\n\n**CHECK:** ${checks.filter(c=>c.tableName===o.name).map(c=>`${c.name}: ${c.definition}`).join('; ')||'—'}\n\n**Indexes:** ${[...new Set(ix.map(i=>i.name))].map(n=>{const list=ix.filter(i=>i.name===n);return`${n} (${list.filter(i=>!i.is_included_column).map(i=>i.columnName).join(',')})${list[0].is_unique?' UNIQUE':''}${list[0].filter_definition?' WHERE '+list[0].filter_definition:''}; INCLUDE ${list.filter(i=>i.is_included_column).map(i=>i.columnName).join(',')||'—'}`;}).join('; ')}\n`;}).join('\n');
write('DATABASE_INVENTORY.md','# Database inventory\n\nMetadata từ CinemaBookingDB thật. Định nghĩa source/live nằm trong evidence; không deploy.\n\n'+schemaBody+'\n## Principals / roles / grants\n\n'+ev('live-security.json')+', '+ev('live-role-memberships.json')+', '+ev('live-server-role-memberships.json')+', '+ev('live-schemas.json')+'\n');
write('MODULE_AUDIT.md','# Complete SQL module audit\n\nInventory tất cả 154 deployed modules. `STATIC/PARTIAL` có nghĩa đã đọc contract/dependency, không chứng nhận mọi branch runtime. Signature capture 110 service methods là stub inspection, không phải real DB PASS. Legacy alias không có app caller chưa đủ để xóa.\n\n'+modules.map(m=>`## ${m.name}\n\n**Type / source sync:** ${m.type} / ${m.sourceStatus}; ${m.source?src(m.source):'DB ONLY'}\n\n**Parameters:** ${m.parameters.map(p=>`${p.name||'RETURN'} ${p.typeName}${/char/.test(p.typeName)?'('+ (p.max_length===-1?'MAX':p.typeName.startsWith('n')?p.max_length/2:p.max_length)+')':''}${p.is_output?' OUTPUT':''}`).join(', ')||'none'}\n\n**Dependencies:** ${m.references.join(', ')||'—'}\n\n**SQL callers:** ${m.callers.join(', ')||'—'}\n\n**Backend callers:** ${m.backendCallers.join(', ')||'—'}\n\n**Transaction / savepoint / TRY-CATCH / XACT_ABORT:** ${m.transaction} / ${m.savepoint} / ${m.tryCatch} / ${m.xactAbort}\n\n**Locks:** ${m.locks.join(', ')||'none explicit'}\n\n**THROW:** ${m.throwNumbers.join(', ')||'—'}\n\n**Verification:** ${m.verification}; ${m.multirowReview??'—'}\n`).join('\n'));
write('API_MATRIX.md','# API → Controller → Service → SP inventory\n\n118 endpoint; 117 có SP qua service/middleware hoặc DB-health. /health là liveness không gọi DB. Dependencies là trực tiếp; traversal đầy đủ trong MODULE_AUDIT. Cột guard gồm middleware dùng chung của router và handlers riêng từng endpoint.\n\n'+table(['Method / API','Guard / handlers','Controller','Validator','Service → SP','DB dependencies'],chains.map(c=>[`${c.method} ${c.path}`,(c.globalGuards??[]).join('; ')+'; '+c.handlers,c.controller,c.validators.join(', '),c.serviceMethods.join(', ')+' → '+c.procedures.join(', '),c.tablesAndDependencies.join(', ')])));
write('FIXTURE_MANIFEST.md','# Audit fixtures\n\nRun `mus0s7zc`; tạo bằng API/SP, không direct INSERT. Dữ liệu fixture được giữ lại để review. Một số fixture rỗng mới tạo đã được xóa qua API để kiểm DELETE; `deleted:true` chỉ các dòng của audit. Không tự cleanup dữ liệu cũ. Manifest machine-readable: '+ev('fixture-manifest.json')+'\n\n'+Object.entries(fixtures).filter(([,v])=>Array.isArray(v)).map(([n,rows])=>`## ${n}\n\n${table(['Entry','Details'],rows.map((r,i)=>[i+1,JSON.stringify(r)]))}`).join('\n'));
// Full 45-row traceability. Status is conservative: PASS requires end-to-end and negative evidence.
const rows=[
 ['KH-01','Đăng ký','auth/Register.jsx','POST /auth/register','AUTH_REGISTER_CUSTOMER','NGUOIDUNG,HOSOKHACHHANG','PARTIAL','PASS','PASS','VERIFIED','PARTIAL','Validation DOB tương lai chưa thử registration; profile BUG-013'],
 ['KH-02','Đăng nhập','auth/Login.jsx','POST /auth/login','AUTH_LOGIN','NGUOIDUNG,VAITRO,VAITRO_QUYEN,QUYEN','PASS','PASS','PASS','VERIFIED','PASS','Register/login/browser; sai password và duplicate account'],
 ['KH-03','Hồ sơ','auth/Profile.jsx','GET/PUT /auth/me','USER_GET_CURRENT,USER_UPDATE_PROFILE','NGUOIDUNG,HOSOKHACHHANG','ISSUES','ISSUES','PARTIAL','VERIFIED','FAIL','BUG-013, DATA-006'],
 ['KH-04','Phim & chi tiết','MovieDetail.jsx','GET /movies; GET /movies/:movieId','MOVIE_LIST,MOVIE_GET_DETAIL','PHIM,PHIM_THELOAI,PHIM_DIENVIEN,DANHGIAPHIM','ISSUES','ISSUES','PASS','VERIFIED','FAIL','BUG-018 reviewCount'],
 ['KH-05','Lịch chiếu','MovieDetail.jsx','GET /movies/:movieId/showtimes','SHOWTIME_LIST_BY_MOVIE','SUATCHIEU,PHONGCHIEU,RAPCHIEUPHIM','ISSUES','ISSUES','ISSUES','VERIFIED','FAIL','BUG-001 clock'],
 ['KH-06','Chọn ghế','BookingPreparation.jsx','GET /showtimes/:showtimeId/seats','SEAT_LIST_BY_SHOWTIME','GHE,CHITIETVE,DONDATVE','PASS','PASS','PASS','VERIFIED','PASS','Seatmap browser; sai phòng/xung đột và2seat atomic'],
 ['KH-07','Đặt vé','BookingPreparation.jsx','POST /bookings','BOOKING_CREATE','DONDATVE,CHITIETVE,CHITIETDOAN,KHUYENMAI','PARTIAL','ISSUES','PARTIAL','VERIFIED','FAIL','BUG-001/016/019; giới hạn10/3 vàrace được kiểm'],
 ['KH-08','Đồ ăn','BookingPreparation.jsx','GET /products; POST /bookings','PRODUCT_LIST_ACTIVE,BOOKING_CREATE','SANPHAM,CHITIETDOAN','ISSUES','ISSUES','PASS','VERIFIED','FAIL','BUG-016 unknown product silently dropped'],
 ['KH-09','Khuyến mãi','BookingPreparation.jsx','POST /promotions/validate; POST /bookings','PROMOTION_VALIDATE,BOOKING_CREATE','KHUYENMAI,DONDATVE','PARTIAL','PASS','PASS','VERIFIED','PARTIAL','Preview/browser/lastuse pass; time admin vàcounter lineage còn vấn đề'],
 ['KH-10','Thanh toán','PaymentPage.jsx','POST /orders/:orderId/payments; POST /orders/:orderId/payments/:paymentId/result','PAYMENT_CREATE_ATTEMPT,PAYMENT_UPDATE_RESULT','THANHTOAN,DONDATVE,HOSOKHACHHANG','ISSUES','ISSUES','PASS','VERIFIED','FAIL','CONFLICT-001/002;retry/idempotence pass'],
 ['KH-11','Lịch sử đơn','Orders.jsx','GET /orders','ORDER_LIST_BY_CUSTOMER','DONDATVE,SUATCHIEU,PHIM','PASS','PASS','PASS','VERIFIED','PASS','Browser + real own-only list'],
 ['KH-12','Chi tiết đơn','OrderDetail.jsx','GET /orders/:orderId','ORDER_GET_DETAIL_BY_CUSTOMER','DONDATVE,CHITIETVE,CHITIETDOAN,THANHTOAN','PARTIAL','PASS','PASS','VERIFIED','PARTIAL','Snapshot tiền pass; cancellation overwrites payment history'],
 ['KH-13','Đánh giá','MovieDetail.jsx','POST /movies/:movieId/reviews','REVIEW_CREATE','DANHGIAPHIM,DONDATVE,SUATCHIEU','PASS','PARTIAL','PASS','VERIFIED','PARTIAL','Watched + duplicate + unwatched pass; permission BUG-019'],
 ['KH-14','Khiếu nại','Complaints.jsx','POST/GET /complaints; GET /complaints/:complaintId','COMPLAINT_CREATE,COMPLAINT_LIST_BY_CUSTOMER,COMPLAINT_GET_BY_CUSTOMER','KHIEUNAI,XULY_KHIEUNAI,DONDATVE','PASS','PARTIAL','PASS','VERIFIED','PARTIAL','Browser ownorder/null/API foreign denied; permission BUG-019'],
 ['QLR-01','Đăng nhập quản lý','auth/Login.jsx','POST /auth/login','AUTH_LOGIN','NGUOIDUNG,PHANCONG_RAP','PASS','PASS','PASS','VERIFIED','PASS','Real manager login & oldtoken khóa/revoke denied'],
 ['QLR-02','Phòng trong scope','ManagerPortal.jsx','CRUD /manager/cinemas/:cinemaId/rooms; /manager/rooms/:roomId','MANAGER_ROOM_LIST,MANAGER_ROOM_CREATE,MANAGER_ROOM_UPDATE,MANAGER_ROOM_DELETE','PHONGCHIEU,PHANCONG_RAP','PASS','PASS','PARTIAL','VERIFIED','FAIL','GAP-002, foreign403'],
 ['QLR-03','Ghế trong scope','ManagerPortal.jsx','CRUD /manager/rooms/:roomId/seats; /manager/seats/:seatId','MANAGER_SEAT_LIST_BY_ROOM,MANAGER_SEAT_CREATE,MANAGER_SEAT_UPDATE','GHE,CHITIETVE,PHANCONG_RAP','PARTIAL','PASS','ISSUES','VERIFIED','FAIL','BUG-004 +GAP-002'],
 ['QLR-04','Tạo suất','ManagerPortal.jsx','POST /manager/showtimes','MANAGER_SHOWTIME_CREATE','SUATCHIEU,PHIM,PHONGCHIEU','PASS','ISSUES','ISSUES','VERIFIED','FAIL','BUG-001/003'],
 ['QLR-05','Sửa suất','ManagerPortal.jsx','PUT /manager/showtimes/:showtimeId','MANAGER_SHOWTIME_UPDATE','SUATCHIEU,PHANCONG_RAP','PARTIAL','ISSUES','MISSING','VERIFIED','FAIL','BUG-002;GAP-001'],
 ['QLR-06','Hủy suất','ManagerPortal.jsx','POST /manager/showtimes/:showtimeId/cancel','MANAGER_SHOWTIME_CANCEL','SUATCHIEU,DONDATVE,THANHTOAN','ISSUES','PARTIAL','PARTIAL','VERIFIED','FAIL','Emptyshow happy; lifecycle paid conflict'],
 ['QLR-07','Bảng giá scope','ManagerPortal.jsx','CRUD /manager/cinemas/:cinemaId/pricing; /manager/pricing/:pricingId','MANAGER_PRICING_CREATE,MANAGER_PRICING_UPDATE','BANGGIA,PHANCONG_RAP','PASS','PASS','PARTIAL','VERIFIED','FAIL','GAP-003; overlap400/409'],
 ['QLR-08','Dashboard scope','ManagerPortal.jsx','GET /manager/cinemas/:cinemaId/dashboard','MANAGER_DASHBOARD','PHONGCHIEU,GHE,SUATCHIEU,DONDATVE','PARTIAL','PASS','PASS','VERIFIED','PARTIAL','Real dashboard/foreign403; all metric boundaries chưa đủ'],
 ['QLR-09','Doanh thu scope','ManagerPortal.jsx','GET /manager/cinemas/:cinemaId/revenue','MANAGER_REVENUE','THANHTOAN,DONDATVE,PHONGCHIEU','PASS','PASS','MISSING','VERIFIED','FAIL','GAP-004'],
 ['CSKH-01','Đăng nhập support','auth/Login.jsx','POST /auth/login','AUTH_LOGIN','NGUOIDUNG,VAITRO_QUYEN','PASS','PASS','PASS','VERIFIED','PASS','Real login +role guard'],
 ['CSKH-02','Danh sách khiếu nại','SupportPortal.jsx','GET /support/complaints','SUPPORT_COMPLAINT_LIST','KHIEUNAI,NGUOIDUNG','PASS','PASS','PASS','VERIFIED','PARTIAL','Queue real; exhaustive filter combinations chưa chạy browser'],
 ['CSKH-03','Chi tiết khiếu nại','SupportPortal.jsx','GET /support/complaints/:complaintId','SUPPORT_COMPLAINT_GET_DETAIL','KHIEUNAI,XULY_KHIEUNAI','PASS','PASS','PASS','VERIFIED','PARTIAL','Positive/history real; browser404 flow chưa chạy'],
 ['CSKH-04','Đơn tham chiếu','SupportPortal.jsx','GET /support/complaints/:complaintId/order-reference','SUPPORT_COMPLAINT_GET_ORDER_REFERENCE','vw_ChiTietDonDatVe','PARTIAL','PARTIAL','PARTIAL','VERIFIED','FAIL','GAP-005'],
 ['CSKH-05','Ghi xử lý','SupportPortal.jsx','POST /support/complaints/:complaintId/processings','SUPPORT_COMPLAINT_ADD_PROCESSING','XULY_KHIEUNAI,KHIEUNAI','PASS','PASS','PASS','VERIFIED','PASS','2concurrentPOST201,history vàbrowser append;customer403'],
 ['CSKH-06','Trạng thái khiếu nại','SupportPortal.jsx','PUT /support/complaints/:complaintId/status','SUPPORT_COMPLAINT_UPDATE_STATUS','KHIEUNAI,XULY_KHIEUNAI','PASS','PASS','PASS','VERIFIED','PARTIAL','Admin dùng chung SP đã PUT real; support browser riêng chưa trọn'],
 ['ADM-01','Đăng nhập Admin','auth/Login.jsx','POST /auth/login','AUTH_LOGIN','NGUOIDUNG,VAITRO','PASS','PASS','PASS','VERIFIED','PASS','Real Admin/browser;nonAdmin403'],
 ['ADM-02','Người dùng','AdminPortal.jsx','POST/GET /admin/users; PUT /admin/users/:userId/status','ADMIN_USER_CREATE,ADMIN_USER_UPDATE_STATUS','NGUOIDUNG,HOSOKHACHHANG','ISSUES','ISSUES','ISSUES','VERIFIED','FAIL','BUG-006/014/015; lock/unlockoldtoken tested'],
 ['ADM-03','Vai trò','AdminPortal.jsx','CRUD /admin/roles','ADMIN_ROLE_CREATE,ADMIN_ROLE_UPDATE,ADMIN_ROLE_DELETE','VAITRO','PASS','PASS','ISSUES','VERIFIED','FAIL','BUG-007'],
 ['ADM-04','Danh mục quyền','AdminPortal.jsx','CRUD /admin/permissions','ADMIN_PERMISSION_CREATE,ADMIN_PERMISSION_UPDATE,ADMIN_PERMISSION_DELETE','QUYEN','PASS','PASS','PASS','VERIFIED','PARTIAL','BrowserCRUD +negativeauth; deleteinuse chưa real trên own fixture'],
 ['ADM-05','Gán quyền','AdminPortal.jsx','PUT/GET /admin/roles/:roleId/permissions','ADMIN_ROLE_PERMISSION_SET,ADMIN_ROLE_PERMISSION_LIST','VAITRO_QUYEN','PASS','PASS','ISSUES','VERIFIED','FAIL','BUG-008;functionalRBAC mismatch'],
 ['ADM-06','Phân công','AdminPortal.jsx','POST/GET /admin/assignments; PUT /admin/assignments/:assignmentId','ADMIN_ASSIGNMENT_CREATE,ADMIN_ASSIGNMENT_UPDATE','PHANCONG_RAP,NGUOIDUNG','ISSUES','PASS','PARTIAL','VERIFIED','FAIL','BUG-017;role/time/revoke tested'],
 ['ADM-07','Rạp + ảnh','AdminPortal.jsx','CRUD /admin/cinemas; /admin/cinemas/:cinemaId/images','ADMIN_CINEMA_CREATE,ADMIN_CINEMA_UPDATE,ADMIN_CINEMA_IMAGE_CREATE,ADMIN_CINEMA_IMAGE_UPDATE,ADMIN_CINEMA_IMAGE_SET_COVER','RAPCHIEUPHIM,HINHANH_RAPCHIEUPHIM','PARTIAL','ISSUES','ISSUES','VERIFIED','FAIL','BUG-005/006/012;GAP-006'],
 ['ADM-08','Phòng + ghế global','AdminPortal.jsx','CRUD /admin/rooms; /admin/seats','ADMIN_ROOM_CREATE,ADMIN_SEAT_CREATE,ADMIN_ROOM_UPDATE,ADMIN_SEAT_UPDATE','PHONGCHIEU,GHE','PARTIAL','ISSUES','ISSUES','VERIFIED','FAIL','BUG-006/009/010/011'],
 ['ADM-09','Phim global','AdminPortal.jsx','CRUD /admin/movies; PUT /admin/movies/:movieId/actors','ADMIN_MOVIE_CREATE,ADMIN_MOVIE_UPDATE,ADMIN_MOVIE_ACTOR_SET','PHIM,PHIM_THELOAI,PHIM_DIENVIEN','PARTIAL','PARTIAL','ISSUES','VERIFIED','FAIL','BUG-006;cast/genreset real'],
 ['ADM-10','Thể loại','AdminPortal.jsx','CRUD /admin/genres','ADMIN_GENRE_CREATE,ADMIN_GENRE_UPDATE,ADMIN_GENRE_DELETE','THELOAI,PHIM_THELOAI','PASS','PASS','PASS','VERIFIED','PARTIAL','Browser CRUD real; missing/delete-inuse branch chưa trọn'],
 ['ADM-11','Sản phẩm','AdminPortal.jsx','CRUD /admin/products','ADMIN_PRODUCT_CREATE,ADMIN_PRODUCT_UPDATE,ADMIN_PRODUCT_DELETE','SANPHAM,CHITIETDOAN','PASS','PARTIAL','ISSUES','VERIFIED','FAIL','BUG-006/011;price snapshot &deleteinuse real'],
 ['ADM-12','Khuyến mãi','AdminPortal.jsx','CRUD /admin/promotions','ADMIN_PROMOTION_CREATE,ADMIN_PROMOTION_UPDATE','KHUYENMAI,DONDATVE','PARTIAL','ISSUES','ISSUES','VERIFIED','FAIL','BUG-001/006;99% andlastuse tested'],
 ['ADM-13','Bảng giá global','AdminPortal.jsx','CRUD /admin/pricing','ADMIN_PRICING_CREATE,ADMIN_PRICING_UPDATE','BANGGIA','PASS','PASS','ISSUES','VERIFIED','FAIL','BUG-006;overlap/snapshot tested'],
 ['ADM-14','Suất global','AdminPortal.jsx','CRUD /admin/showtimes; POST /admin/showtimes/:showtimeId/cancel','ADMIN_SHOWTIME_CREATE,ADMIN_SHOWTIME_UPDATE,ADMIN_SHOWTIME_CANCEL','SUATCHIEU,DONDATVE,THANHTOAN','ISSUES','ISSUES','ISSUES','VERIFIED','FAIL','BUG-001/006,CONFLICT-001;overlaprace denied'],
 ['ADM-15','Xử lý khiếu nại','AdminPortal.jsx','/admin/complaints/:complaintId/processings; /status','SUPPORT_COMPLAINT_ADD_PROCESSING,SUPPORT_COMPLAINT_UPDATE_STATUS','KHIEUNAI,XULY_KHIEUNAI','PASS','PASS','PARTIAL','VERIFIED','PARTIAL','Admin real status/history; full browserAdmin processing chưa chạy'],
 ['ADM-16','Doanh thu global','AdminPortal.jsx','GET /admin/reports/revenue','ADMIN_REPORT_REVENUE','THANHTOAN,DONDATVE,PHONGCHIEU','PASS','PASS','PASS','VERIFIED','PARTIAL','Nonzero92000 image invariant +browser datefilter; multi-day boundaries chưa đầy đủ'],
];
save('45-uc-final-matrix.json',rows.map(r=>({UC:r[0],name:r[1],DB:r[6],BE:r[7],FE:r[8],INT:r[9],STATUS:r[10],note:r[11]})));
const dependencyClosure=(names,seen=new Set())=>{for(const n of names){if(seen.has(n))continue;seen.add(n);const m=modules.find(m=>m.name===n);if(m)dependencyClosure(m.references,seen);}return[...seen];};
write('TRACEABILITY_45_UC.md','# Traceability — 45 use cases\n\nDB/BE/FE: PASS/PARTIAL/ISSUES/MISSING. INT=VERIFIED chỉ nghĩa có real DB evidence cho nhánh đã chạy; không đồng nghĩa toàn bộ UC PASS. Final status áp tiêu chí nghiêm ngặt của yêu cầu; thiếu negative/boundary/browser path được giữ PARTIAL.\n\n'+table(['UC','Tên / Requirement','FE','API','SP','DB objects / rules','DB','BE','FE','INT','STATUS','Evidence / issue'],rows.map(r=>{const sp=r[4].split(',').map(k=>PROCEDURES[k]).filter(Boolean);return[r[0],r[1]+'; '+src('Phân Tích _ Thiết Kế.md',`| **Mã Use Case** | ${r[0]}`),src('frontend/src/pages/'+r[2]),r[3],sp.join(', '),dependencyClosure(sp.map(s=>s.replace('dbo.',''))).join(', '),...r.slice(6,12)];}))+'\n## Evidence mapping\n\nTất cả route/controller/validator/service/param được liệt kê tại [API_MATRIX](./API_MATRIX.md) và '+ev('api-chain-inventory.json')+'. Tables/PK/FK/CHECK/default/index tại [DATABASE_INVENTORY](./DATABASE_INVENTORY.md). Final database fixture state tại '+ev('fixture-final-tickets.json')+', '+ev('fixture-final-payments.json')+', '+ev('fixture-final-complaints.json')+', '+ev('fixture-final-covers.json')+'. Request/response và browser snapshots nằm trong evidence index.\n');
const ucCounts=Object.fromEntries(['PASS','PARTIAL','FAIL','NOT VERIFIED'].map(status=>[status,rows.filter(r=>r[10]===status).length]));
const auditSummary=read('normalized-audit-summary.json');
const stats=table(['Type','Count'],[['Tables',26],['Columns',columns.length],['PK',26],['FK',30],['UNIQUE constraints',10],['CHECK',55],['DEFAULT',36],['Indexes (including PK/UQ)',61],['Views',6],['Functions',17],['Triggers',7],['Stored Procedures',124],['Schemas',13]]);
const score=(pairs)=>table(['Hạng mục','Status / evidence'],pairs);
const report=`# FULL SYSTEM DEEP AUDIT — CinemaBookingDB

**Ngày:** 2026-10-03, Asia/Ho_Chi_Minh. **Mode:** AUDIT ONLY. **Source HEAD:** 7c35624274a9dce7b5a97ee7f9c7f34013daf77b.

## 1. Executive Summary

**AUDIT FOUND ISSUES – FIX REQUIRED.** Đã audit database thật, source sau rollback, 118 endpoint, 154 SQL module, 45 UC và browser cho bốn role. Phát hiện **20 BUG, 9 DATA observations/defects, 7 GAP, 5 CONFLICT**; không cộng các nhãn này thành số root cause độc lập vì một số findings cùng nguồn lỗi. BUG có18PROVEN và2HIGH-CONFIDENCE. DATA-008 là SUSPECTED, không được gọi là corruption đã chứng minh.

Ưu tiên: DATA-001 tổng tiền âm trong dữ liệu cũ; BUG-001 lệch múi giờ; CONFLICT-001/002 lifecycle thanh toán khác thiết kế; BUG-004/005/006/007 làm hỏng thao tác Manager/Admin; BUG-014 mật khẩu Admin; BUG-018 JOIN nhân số review. Chưa tái hiện double booking, cross-customer read, Manager vượt rạp hoặc non-Admin vào Admin API trong các trường hợp đã thử.

Test có sẵn: BE90/90, FE26/26, lint/build PASS. Audit riêng sau sửa kỳ vọng test sai: **${auditSummary.PASS} PASS, ${auditSummary.FAIL} FAIL, ${auditSummary.BLOCKED} BLOCKED trên ${auditSummary.rawChecks} assertions**. Hai BLOCKED là setup concurrency ban đầu dùng suất đã bị hủy, đã có rerun trên suất mới PASS; không đánh đồng với double booking. Các assertion này không phải số UC PASS. UC final: ${Object.entries(ucCounts).map(([k,v])=>`${k}=${v}`).join(', ')}.

Không sửa BE/FE/SP/trigger/view/function/migration. ${ev('source-preservation.json')} xác nhận203baselinefiles không đổi; ${ev('database-object-preservation.json')} xác nhận337objects không thêm/xóa, modify_date và definitions bỏ khoảng trắng không đổi. Export SQL ban đầu mất indentation ở2module, đã ghi rõ parser correction. Hai file docs bị xóa từ trước audit được giữ nguyên trạng thái. Fixtures được tạo bằng API/SP và giữ để review: [manifest](./FIXTURE_MANIFEST.md).

## 2. Environment

${score([['Workspace / shell','D:\\DBMS_DO_AN / PowerShell'],['Branch','main, behind origin/main1commit; không fetch/pull/reset trong audit'],['SQL instance','localhost:1433; @@SERVERNAME=DESKTOP-E67DPCV'],['Database','CinemaBookingDB — dữ liệu đang có; không disposable clone'],['SQL version / collation','17.0.1000.7 Standard Developer Edition64bit; Vietnamese_CI_AS; RCSI ON'],['Inspector','Windows DESKTOP-E67DPCV\\Admin (sysadmin) cho SELECT/DBCC metadata'],['Runtime account','CinemaAppUser, db_executor; không db_owner/sysadmin'],['BE','development, PORT4000, .env DB_DATABASE= CinemaBookingDB'],['FE','Vite5173, default /api proxy localhost4000; không .env frontend'],['Node / libraries','Node24.21.0, Express5.2.1, mssql12.7.2, React19.2.8, Vite8.3.1'],['Browser','Microsoft Edge headless/CDP9223, profile audit riêng']])}
${ev('live-environment.json')}, ${ev('environment-redacted.json')}, ${ev('browser-version.json')}. Password/JWT không in trong evidence. Audit server dùng createApp thật; không bật global expire-job để tránh đổi đơn cũ ngoài fixture. SP vẫn kiểm hold theo đồng hồ DB; job startup production được đọc source. Timestamps baseline SQL local13:27 và UTC06:27 chênh7giờ.

## 3. Current Scope

KH14, QLR9, CSKH6, Admin16: **45 UC**. Ảnh rạp là extension ADM-07, không UC mới. **ADM-17: ABSENT trong schema/SP/API/UI; FOUND obsolete mention trong actor overview thiết kế (§2.1).** Tài liệu giải thích ADM-17 đã gỡ không tính là regression. Thiết kế §1.4 nói25bảng nhưng ERD §3.3 nói26; sau ảnh rạp actual26 đúng extension.

## 4. Traceability Matrix

[Ma trận45UC đầy đủ](./TRACEABILITY_45_UC.md): requirement → FE → API → service/SP → dependencies/function/view/trigger/table/constraint → DB/BE/FE/INT/STATUS. [API_MATRIX](./API_MATRIX.md) chứa toàn118endpoint, controller, validator và guards; [MODULE_AUDIT](./MODULE_AUDIT.md) chứa dependency/callers/params/transaction/locks mọi module. Final state: ${ev('fixture-final-tickets.json')}, ${ev('fixture-final-payments.json')}, ${ev('fixture-final-complaints.json')}, ${ev('fixture-final-covers.json')}.

## 5. Database Inventory

${stats}
[Schema26tables và index/constraint đầy đủ](./DATABASE_INVENTORY.md). Metadata lấy từ sys.objects/sys.sql_modules/sys.parameters/sys.foreign_keys/sys.check_constraints/sys.indexes và database/server role memberships. Index không disabled; FK/CHECK inspected đều enabled/trusted; 55predicate scans không vi phạm. Runtime user dùng db_executor, DENY table SELECT/INSERT/UPDATE/DELETE qua role; ownership chain cho EXECUTE SP. Không phải DBowner. Inspector sysadmin là account audit, không phải account ứng dụng.

## 6. Source vs Deployed DB

Source replay cuối có148module; live154: **113MATCH,35DIFFERENT,6DB_ONLY,0SOURCE_ONLY** sau normalization comments/whitespace/CREATE OR ALTER. ${ev('module-drift.json')}. Đây là module comparison, không chứng nhận schema toàn bộ tương đương.

DB-only: fn_BayGio, fn_HomNay, fn_GheCoVeHieuLucSuatTuongLai, sp_Clock_GetNow, sp_Showtime_ValidateTimes, sp_Showtime_CancelCascade. DONDATVE live có LyDoHuy/ThongBaoHuy ngoài source baseline. Defaults/module definitions dùng fn_BayGio và header014/015; repo deploy chỉ001..013. Migration007 intentionally absent, không đánh dấu lỗi numbering. [CONFLICT-003](./FINDINGS.md#conflict-003). Không có migration ledger để khẳng định từng migration đã được apply chỉ từ tên file; đối chiếu definitions cho thấy drift thật.

Deployability/re-run chỉ đọc dependency/order và additive009..013, không redeploy vào DB đang dùng. Fresh install toàn bộ source và upgrade/re-run trên clone **NOT VERIFIED**. Các source-only lịch sửa paid show/seat history guard khác live được xem HIGH-CONFIDENCE risk của redeploy, không gọi là bug runtime live đã chứng minh.

## 7. Schema Audit

Normalization: entities và bảng n-n tách rõ; order/ticket/product prices là snapshot có chủ đích. PK/FK/UNIQUE review không có orphan hoặc duplicate key trong scans. CHECK chỉ là local guard; tổng discount<=subtotal, futureDOB và assignment identity chưa được bảo vệ đủ. DATA-001/005/006/007 chứng minh constraint xanh không bảo đảm nghiệp vụ.

DECIMAL18,2 dùng cho tiền; CHAR/VARCHAR IDs/codes và NVARCHAR text phù hợp nhìn chung. Validation generic name<=255 sai với SP100/150 (BUG-011); số positive chưa integer (BUG-010). FK ngăn xóa parent có lịch sử; API delete audit cinema có room/history, product đã bán, seat có vé đều409; chỉ xóa fixture mới rỗng qua API.

## 8. Current Data Audit

Baseline lấy trước fixtures: ${ev('live-rowcounts.json')}, ${ev('data-scan-summary.json')}. 30FK orphan probes=0; unique index duplicate groups=0; active seat duplicate=0; wrong room seat=0; overlapping showtime=0; payment amount/status mismatch=0; complaint owner/history mismatch=0; assignment sai role=0; pricing overlap=0; required text blank=0.

Có order20 total−40,000;3paidorder của show34đãhủy;15show ngắn hơn phim;4show ngoài phát hành;user17birthday2999;6show staleMởbán. Counterpromo3rows khác retained-orderCOUNT nhưng seed/history chưa đủ để kết luận corrupt. Missing profile query cuối cóuser21cũ vàuser34fixture. Assignment duplicate cuối phân biệt groupcancelledcũ và13/14fixture.

[DATA-001..009](./FINDINGS.md#data-001) ghi table/ID/count/condition/source confidence/remediation. Không tự sửa dữ liệu cũ. DBCC CHECKDB và CHECKCONSTRAINTS exit0: ${ev('dbcc-health.txt')}; đó là kiểm tra physical/declared constraints, không bác bỏ DATA findings.

## 9. Cinema Image Audit

Schema HINHANH_RAPCHIEUPHIM: identity PK, RapID FK, URLnv500nonempty, MoTanm255nullable, coverBITdefault0, displayOrderINT>=0default0, statusHoạtđộng/Tạmẩn, createdAtdatetime2. Unique filtered UX_HINHANH_RAPCHIEUPHIM_Rap_Cover(RapID) WHERE cover1; lookup(RapID,TrangThai,ThuTu,HinhAnhID). Stable public ordering ThuTu then ID; cùng thứ tự không mặc nhiên là duplicate business key.

Baseline ảnh0rows: orphan/cover checks trên baseline chưa đủ meaningful. Fixtures3ảnh thật một rạp:12setCover requests đều200, final1cover; hide ảnh clearcover; setcoverinactive409; wrongRap update404; invalidjavascriptURL400. Publiclist mỗi rạp1row với OUTER APPLY TOP1cover; gallery API returns3trước hide. Revenue thực92000 không đổi khi 3→2active images; test nonzero tránh kết luận từ0. ${ev('integration-transcript.json')}, ${ev('supplemental-transcript.json')}, ${ev('fixture-final-covers.json')}.

FE cover/fallback thật có browser screenshot; public gallery UI thiếu GAP-006. Admin image update UI FAIL BUG-005 dù API PUT đúng hoạt động. Không thấy N+1cover request: list đã trả coverURL, FE không loop images API. Update/SetCover có same key-range lock theo011; cover-onlyrace đã chạy, mixed Create/Update/Delete/SetCover stress dài **NOT VERIFIED**. Không kết luận hoàn toàn không deadlock.

## 10. Stored Procedure Audit

[MODULE_AUDIT](./MODULE_AUDIT.md) có124SPlive, phân biệt public/auth/customer/manager/support/admin/system theo caller và inventory. Capture110service methods/118RPC call contracts không có unknown input/output name, nhưng đây là injected stub inspection, không phải real DB resultset proof. ${ev('backend-sp-contract-capture.json')}. Database time/error/enum/length contract vẫn có bugs.

Core Booking tính snapshot từ DB; không nhận client price; giữ account→showtime→seat locks và savepoint, max10seat/product quantity10, max3hold. Invalid seat rollback, unknownproduct bị bỏ qua BUG-016. Payment nhiều attempts, finalresult idempotent và contradictoryresult409; live late success policy conflict. Complaint support/admin actor truyền vào SP, transaction append/history locks; NULLorder supported. Admin global SP có nhiều helper CRUD và chưa nhận actor identity ở mọi operation. Missingcinema200null BUG-012; assignment duplicate BUG-017.

${ev('procedure-inventory.json')} đánh9SP POSSIBLY DEAD (aliases và legacy helpers); đã tìm internal/backend callers. Không có app caller không đủ chứng minh dead vì SQL tests/docs/compatibility có thể gọi. Chưa xóa. Resultsetshape kiểm bằng API thật trên luồng chạy; toàn bộ optional/null/error branch chưa được execute.

## 11. View / Function / Trigger Audit

6views,17functions,7triggers đã inventory/đọc dependency. vw_ThongKePhim COUNTreview nhân theo SUATCHIEU: BUG-018 đã SELECT+API chứng minh. Revenueviews/SP aggregate từngorder/payment trước join rạp; không joinimages. LichSuDatVe/ChiTietDon derive expired display theo clock và snapshotmoney; detail vẫn cần history lifecycle thống nhất.

fn_TinhGiaVe cộng các surcharge phù hợp; weekday/weekend và99%cap functions thuộc012/013. Source013 giải thích DATEFIRST independent/weekendSatSun. Không sửa sessionclock; review naturalfuturefixture sau1phút chứng minh watched/duplicate branch. Full matrix all DATEFIRST7values và decimalrounding large range **NOT VERIFIED** trongrun này.

Trigger ghế/suất/review/role dùng EXISTS/INSERTED set-based;2seat booking đã chạy multi-row positive. SHOWTIMEtrigger có check với bảng và internalINSERTED. XULY status trigger JOININSERTED có lựa chọn không xác định nếu một statementinsert nhiều histories của cùng complaint; SP hiện tại tạo1row/statement, concurrency paths đã serialize. Đây là **SUSPECTED / batch not exercised**, không xác nhận bug reachable quaAPI. TRG_BANGGIA locksrap nhưng comment nói lock order; plan chưa chứng minh deterministic nhiềuRap ordering. Multi-row fail/sameparent historybatch blocked bởi yêu cầu không directINSERT và không có bulkSP phù hợp.

## 12. Transaction Audit

Core Booking, Payment, CinemaImage và complaint có TRY/CATCH, @@TRANCOUNT ownership/savepoint, rollback khi lỗi. Multi-seat loser409 không sinh đơn/vé partial; receipts/final tickets có2vé của winner và không vé lẻ loser. Duplicate payment callback không cộng điểm lần2 theo source locking và stateidempotence; finalmoney/historyretained kiểm thực. ${ev('fixture-final-payments.json')}.

SP nhỏ1statement không bắt buộcBEGINTRAN. Role-permission replacement và movie-genre/cast multi-step đã đọc transaction; capture/APIpositive có evidence. Exhaustive forcedmidstatementfailure/savepoint/XACT_STATE, retrydeadlock và nested callertransaction **NOT VERIFIED**. Audit không tiêm lỗi/sửa production SP. Cancellation014 transaction có tính nguyên tử nhưng vẫn vi phạm rule scope và đổi payment history (CONFLICT-001).

## 13. Concurrency Audit

${score([['Booking cùng ghế','PASS trong race đã thử:1×201+1×409 SEAT_CONFLICT'],['Multi-seat chồng1ghế','PASS:1atomicwinner,1conflict; freshshow60'],['Promotionlastuse cùngsuất','PASS:1discountedorder,1full-price; fallback KH-09 hợp lệ'],['Promotionlastuse khácsuất','PASS quan sát:2×201, chỉ1discount; controlled6sread-onlylock trên ownpromo'],['Payment duplicate samefinal','PASS2×200;2failedattempts giữ nguyên'],['Complaint append đồng thời','PASS2×201; đủhistory; cuối state khớp lịch sử'],['Assignment giống nhau','FAIL2×200,2rows — BUG-017'],['Cover','PASS12×200,1cover;3images'],['Showtime overlap2sessions','PASS:SPfirstuncommitted +APIsecond409;1rowcuối'],['Pricing overlap','PASS negative409; concurrent pricingwriters không chạy riêng'],['Heavy load / deadlock rate','NOT VERIFIED; không suy rộng từ2sessions']])}
${ev('supplemental-checks.json')}, ${ev('promotion-race-checks.json')}, ${ev('showtime-race-checks.json')}, ${ev('additional-checks.json')}. Read-only locks chỉ ownpromo/ownshow transaction, chờ6s, không sửa clock/schema. SPinsert show qua officialusp, không directINSERT. Các harness lỗi setup ban đầu được giữ evidence và corrected trong normalized checks; không tính bỏskipthànhPASS.

## 14. Backend Architecture Audit

Route→controller→validator→service→procedureClient rõ; 110factorymethods captured. Whitelist procedure names không lấy từ request, typed .input và .execute. Không production query()/batch() trong backend src: ${ev('raw-sql-manual-review.json')}. Root noSQL scanner FAIL falsepositives do regex INSERT|UPDATE|... trong error-parser/EnglishSelect vàtestassertions; không gọi scannerFAIL là backend chạy rawSQL.

Pool shared max10,min0,idle30s, connectfailure resetpoolPromise; đọc closePool/server shutdown source. Auth refresh DB user/permissions cho request, assignmentoldJWT thay đổi ngay đã proven. Express5 asynchandlers catch→next; Helmet,CORS configured. Logger observed không password/JWT/requestbody; error500 messagegeneric nhưng codeEREQUEST/EPARAM. error503 trả rawerr.message có rủi ro disclosehost/login theo source (**SUSPECTED**, không tắtDB đểrepro). No appsource fix.

## 15. API / Auth / RBAC Audit

[118route matrix](./API_MATRIX.md). Auth trả bcrypt-hash từDB vào service nhưng DTO không lộhash raAPI; JWTsub là identity, profile/bookingunknownauthorityfields400. Roleboundary401/403, wrongpassword401, lockedoldtoken401. Customer book/pay/review/complaint chỉroleguard, thiếufunctionalpermission BUG-019 HIGH-CONFIDENCE. FE area permissions BUG-020. Permission seededrole không bị thay đổi vì sẽ ảnh hưởng tất cả người dùng; fullpermission-revocation realDB **NOT VERIFIED**. Owncustomrole/permission create/update/grant/clear/delete quaAPI chạy; clearUIfail riêng.

AdminDatabaseglobal khác ManagerScope: Admin wrappers không dựa currentcinema context. DBroleEXECUTEallschema choappuser cần BEauthority; nhiềuAdminSPkhông actorparam là kiến trúc chưa có secondRBACbarrier, không phải đã chứng minh HTTPprivilegeescalation. No SQL/procedure-name injection path tìm thấy. Massassignment user/role/price bịchặn.

## 16. Manager Scope Audit

ManagerA28 córap40, ManagerB29 initiallynone. GET foreignrooms/showtimes/pricing/dashboard/revenue403; foreignroomseats403; writeforeignroom403. Scope derive rap từ room/seat/show/pricing; API truyền req.user.userId xuống SP; fn_KiemTraQuanLyRapScope kiểm assignmentstatus/date/accountactive. Futureassignment của29rap41 deniednow403; ownassignmentrevoked→oldtoken403; ownuserlock→oldtoken401; restoredquaAPI đúng trước kết thúc. Expireddateinclusive/exclusive boundary toànma trận ngày **NOT VERIFIED**; source dùng <=endDATE.

Không chứng minh Manager vượtscope. Rolewrongassignmentcustomer400; DBassignmentrolebaseline0violation. Không cótriggerassignmentrole chuyên biệt; SPcreate/updatecheckrole. Duplicateassignmentđúngrole vẫn tạo2rows BUG-017. ManagerUI thiếu/broken nhiềucrud GAP-001..004, BUG-004.

## 17. Admin Global Audit

16adminreadfamilies200 trênDBthật; APIs tạo cảrapA/B không cầnassignment; room/seat/movie/cast/genre/product/promo/pricing/show/users/roles/permissions/assignment tạo quaAPI. Update pricing/product/promo bảo toàn oldmoney; dependencydeletes409. Ownemptycinema vàownbrowsergenre/permission deletedquaAPI đểtestCRUD.

Browser Admin đã reproduce9statusformsblank, ảnhPUT400, role rename ignored, clearpermissions400; browsergenre/permissioncreate-update-deletePASS, revenue datefilterrenderPASS. Không coi toànAdminE2EPASS. Admin cancellation200paidshow vi phạmKH-10. Staffcreate longpassword vàcustomerrole khôngprofile đãproven. Missingcinema/update404contract vàvalidationerrorsFAIL.

## 18. Customer Ownership Audit

CustomerB không xem/pay/resultOrder củaA/extra:404; foreigncomplaintdetail404; foreignordercomplaint404. Ownnullreference complaint hỗ trợ; browsercomplaint ownpaidordercreated. ClientuserId/role/totalspoof400; DB chọn order theo useridentity truyền từauth. PaymentSPkhônguserparam nhưng BE gọi detail ownership trước và kiểmattempt nằmtrongorder. Không chứng minh TOCTOUownership exploit; ownership không cóAPItransfer owner.

**Cross-customer access: NO trong probes đã thử**; không tuyên bố exhaustivepenetrationPASS. Sessionuserstatus/assignment không trustedJWTrolecache; revoked/lockedoldtoken phản ánh ngay. Functionalpermissionrevocation chưa tested (BUG-019).

## 19. Frontend Functional Audit

Public /movies /movies/:id /cinemas /booking/:showtime, auth/login/register/profile, customerorders/detail/payment/complaints, manager/support/adminportal đãinventory. /customer placeholder tồn tại nhưng flow chính chạy qua /orders, không có mock bookingdata. FEapiClient dùngfetchbearer/sessionStorage;401expire,403forbidden,signalAbort. Movie/catalog pages cóloading/empty/error, poster/coverfallback. No businessSQL trongFE; technicalIDs yêu cầu nhập trongAdminforms làmUXdễsai nhưngvisualpolish ngoàiaudit.

Mainflow data thật; frontendtestsSSRloading không chứng minh allmutations. Static no businessmock arrays/fixture IDs dùng mainflow; demo credentials/technical defaults vàforminputIDs khác mockdata. Generic Admin table lộ tênfieldDB/JSON là UX/architecture concern, không gọi là securityleak khiroleauthorized. Bug/gaps quan trọng:004..008,020 vàGAP001..006.

Manager/Admin/support mutations không có sharedbusyflag đầy đủ; source cho phép duplicateclick (**HIGH-CONFIDENCE risk**, chưa coi là bug duplicate data ngoài BUG-017 APIrace). Request stale response/rapidcinemaswitch là **SUSPECTED**, không có browserraceđủ. Keyboard/mobile/visual polish ngoàiscope đãyêu cầu.

## 20. Full E2E Results

${score([['Customer','VERIFIED happychain:browserregister→login→profileload→movie/seat→booking→payment→history/detail; thêmfood/promo→owncomplaint→reviewnaturalclock→duplicateblocked. OverallFAIL/PARTIAL do timezone/latepayment/unknownfood/permission.'],['Manager','Real login/assignment/dashboard, API room/seat/createupdatecancel/pricing/revenue vàforeignscope negatives. Browser ghếcreateFAIL; sửasuấtkhôngUI; reportfiltermissing. OverallFAIL.'],['CSKH','Browserlogin/queue/detail→appendprocessing persisted; API concurrentappend/status/nullreference. OrderreferenceUI thiếudetails. OverallFAIL/PARTIAL.'],['Admin','Browserlogin vàbugrepros; genre/permissionCRUD/revenuefilter; APIallmodulefixtures/reads. ManyeditformsFAIL, role/image flowsFAIL. OverallFAIL.']])}
BrowserPNG/text/network là thật từVite5173→Express4000→CinemaBookingDB. [Evidence index](./EVIDENCE_INDEX.md). Không screenshotmock hoặc chỉcomponentrender. FullmatrixmọiCRUDnegative của45UC chưaexhaustive; report giữPARTIAL thay chứng nhận45PASS.

## 21. Cross-Module Results

${score([['CinemaImage ↔ Cinema','PASS:cover/fallback/no duplicate cinema'],['CinemaImage ↔ Revenue','PASS nonzero92000 invariant3→2images'],['CinemaImage ↔ Showtime/Rooms','PARTIAL:source không joinimages; inventory/plan; khôngstressmọicombination'],['Seat ↔ Booking','PASS probes same-seat/multiseat/wrongroom/10limit'],['Pricing ↔ Ticket','PASS oldticket85000khôngđổi sau surcharge5000→12000;overlapdenied'],['Product ↔ Order','ISSUES:oldfoodsnapshot50000khôngđổi sau25000→30000;unknownproductbịloại'],['Promotion ↔ Booking','PARTIAL:old13500discountgiữsau10→20%;lastuse/cap pass;counterlineage/time'],['Payment ↔ Order','ISSUES:retries/idempotentpass;late/refundconflict'],['Complaint ↔ Order','PASS own/null;foreigndenied;SupportUIgap'],['Complaint ↔ Support','PASSappend/history/finalstatusprobes;batchsameparentnotverified'],['Admin ↔ Manager','PARTIAL:global/scopereadcorrect;Admineditsbroken'],['Assignment ↔ Scope','ISSUES:revoke/futurecorrect;duplicateassignment'],['RBAC ↔ APIs','ISSUES/HIGH-CONFIDENCE:customgrantsetpass,customerfunctionalguardmissing']])}

## 22. Security Findings

[BUG-014](./FINDINGS.md#bug-014), [BUG-019](./FINDINGS.md#bug-019), [BUG-020](./FINDINGS.md#bug-020), [CONFLICT-005](./FINDINGS.md#conflict-005). Không chứng minh P0cross-account/privilegeescalation trongrun. Scope đã thử: cross-customerNO; cross-cinemaManagerNO; nonAdminAdminAPI NO; nonCSKHsupportmodificationNO; role/userID/price spoofNO; procedureinjectionNO; rawSQLBackendNO. Sensitiveleak: NO trongresponses/logsđãxem;503source rawmessage riskSUSPECTED chưarepro. Rolepermissionrevocation trênseededrole NOT VERIFIED. Appuserkhôngdboowner vàkhôngsysadmin.

## 23. Data Integrity Findings

[DATA-001..009](./FINDINGS.md#data-001). Baseline/finalprobes: duplicateactiveseatNO; overlapsNO; invalidordertotalYES;paymentamountmismatchNO;historicalpricesnapshotcorruptionNO trongtestconfigupdate; oldpaymenthistoryoverwrittenYES khihủyownpaidshow (CONFLICT001);complainthistorymismatchNO;wrongroleassignmentNO, duplicateassignmentYES;imageorphanNO;multiplecoversNO;revenuemultipliedbyimagesNO;otherFKorphansNO. Các câuNO chỉcóphạmvivàevidenceđãkiểm, không phủđịnhunexercisedpaths.

## 24. Functional Gaps

[GAP-001..007](./FINDINGS.md#gap-001): Manager showtimeeditmissing;room/seateditpartial;pricingfields/feeeditmissing;revenuefiltermissing;Supportorderdetailsmissing;publicgallerymissing;regressiontestcoveragepartial. DB/BE/FE/INTstatus riêng trong mỗi finding.

## 25. Business Rule Conflicts

[CONFLICT-001..005](./FINDINGS.md#conflict-001): noRefundvslivecancelcascade, latecallbackvsliveexpiryrejection, source013vsDB014/015,45UCvsobsoleteactoritem, permissionpolicy giữaDB/BE/FE. Mỗi conflict ghi behavior từngtầng/document và rule hiện hành đềxuất; không áp fix hoặc tựchọn lifecycle mới.

## 26. Performance Risks

11estimatedexecutionplans đã lấy với SHOWPLAN_XML ON, không execute write: ${ev('query-plan-summary.json')}. 0missingindexgroups trongsample;9PlanAffectingConvertwarnings ởmovielist/seatmap/orderdetail. Scans ởsmalldata không tựxemlàbug. FORMAT/scalarUDF/correlatedsubqueries trongcatalog vàSPreports cóchi phí cầnbenchmarkdữliệulớn. List APIs chưapagination rõ, Adminrenderfulltable; authreq thường2..3SP nênpoolmax10 cóbottleneck underload (**HIGH-CONFIDENCE performance risk, latencyloadNOT VERIFIED**).

Images cover trả tronglist, không requestN+1publicFE;galleryAPI seek/index cóplan. Complaintview lấylatest3correlatedsubqueries; cầnso plan/IO khihistorylớn. ReportdaterangeHAVINGMAX sauaggregate cókhả năngscanthanh toánnhiều. Noindexadded. Actualplans,STATISTICS IO/TIME,100+sessions/load/lockescalation/deadlockrate chưađo; khôngkết luận systemperformancePASS.

## 27. Test Gaps

${score([['Backend npm test','PASS90,skip0;stub/services/validators/routes majority'],['Frontend npm test','PASS26,skip0;SSR/source assertions major'],['Frontend lint / build','PASS;76modulesbuild, JS347.93KB/gzip102.84KB'],['Root noSQL scanner','FAIL falsepositives20;manualproductionquery/batchcalls0'],['SQLtests08..16','SKIPPED9files:directINSERTbusinessfixture vàmột sốDDL khôngtuân thủaudit-only rule'],['Stress/deploy isolated scripts','SKIPPED:requiredisposableDB/cleanupZZ_STRESS;đangtargetCinemaBookingDBthật'],['Custom API/browser audit','161assertions sau thêmAdmin/form vàaggregate; summaryfile làsốthực saufinal snapshot'],['Harnessexpectations corrected','ComplaintPOST201;promofallbackorderallowed;initialcancelledshowconcurrencyBLOCKED'],['Not exercised','Full freshdeploy/re-run;wholeRBACgrantmatrix;allmultirotriggerfailure;midtxn faultinjection;heavyload;everyCRUDboundary;paymentconflictingattemptsrace'],['Browserharness blockers','Resolved setupselectors/resume;retainblockerfilesforaudittrail;khônggọi resolvedharnesserror thànhproductbug']])}
${ev('backend-tests.txt')}, ${ev('frontend-tests.txt')}, ${ev('frontend-lint.txt')}, ${ev('frontend-build.txt')}, ${ev('normalized-audit-checks.json')}. Không skip→PASS. Assertions PASS không nângUC nếu cònissue hoặc thiếubranch.

## 28. Database Scorecard

${score([['Schema /Data','PARTIAL / ISSUES'],['PK/FK / Constraints','PASS inspected / PARTIAL businessguards'],['Indexes','PARTIAL,enabled/correctlookup;loadnotverified'],['Views','ISSUES BUG-018'],['Functions','PARTIAL clockcontract/DATEFIRSTmatrix'],['Triggers','PARTIAL runtimebatchnotcomplete'],['Stored Procedures','ISSUES'],['Transactions','PARTIAL;observedatomicpathsPASS'],['Concurrency','PARTIAL;assignmentFAIL,otherprobesPASS'],['RBAC','PARTIAL/ISSUES functionalpolicy'],['Ownership','PASS probes'],['Manager Scope','PASSprobes/PARTIALdateboundarymatrix'],['Admin Global','PASSscope/ISSUESoperation'],['Cinema Images','PARTIAL crosslayer;DBcoverprobesPASS'],['Migration Sync','ISSUES'],['Security','PARTIAL'],['Performance','NOT VERIFIED underload']])}

## 29. Backend Scorecard

${score([['Routing /Controllers','PASSinventory/PARTIALexhaustivebranches'],['Auth','ISSUES Adminpassword;ordinaryloginPASS'],['RBAC /Permission','PARTIAL / ISSUES'],['Scope','PASSprobes/PARTIALboundaries'],['Validation','ISSUES'],['Services /SPMapping /DTO','ISSUES semanticcontracts;paramnamesPASS'],['Procedure Client','PASS whitelist/typedexecute'],['Error Mapping','ISSUES lifecycle/547/range'],['Transactions','PARTIALdelegatedDB'],['No-SQL','PASSmanualproductionreview'],['Security','PARTIAL'],['Logging','PASSobservedredaction/PARTIAL503risk'],['Connection Pool','PARTIALsourcecorrect;loadNOT VERIFIED'],['Tests','PARTIAL despite90PASS'],['Real DB','VERIFIEDpaths,ISSUES']])}

## 30. Frontend Scorecard

${score([['45UCcoverage /CRUD /Forms','ISSUES'],['Routes /Navigation','PARTIALfunctionscope'],['Auth /Roleguards','PASSobserved'],['Permissionguards','ISSUEScoarsearea'],['APIintegration','ISSUESfieldcontracts'],['Mutationrefresh','PARTIAL;happycustomerworks;internalbugs'],['Loading /Empty /Errors','PARTIAL inspected/SSR;notallruntimefailurestates'],['409handling','PASSsource/probes,notallbrowserraces'],['Mocks','PASS mainflowusesrealAPI'],['HardcodedIDs','PASSno seededbusinessIDsusedtogenerateflow;AdminmanualIDinputs'],['CinemaImages','ISSUESupdate/gallery'],['Tests','PARTIAL26SSR/sourcechecks'],['Lint /Build','PASS'],['Visualpolish','NOT PART OF AUDIT']])}

## 31. Cinema Image Scorecard

${score([['Table /FK RapID /Noorphan','PASS inspectedandfixture'],['Cover uniqueness','PASSuniqueindex+12race'],['Displayorder /Status','PASSschema/API;fractionalorderedgeNOT VERIFIED'],['AdminCRUD','PARTIALAPI/P1UIupdateFAIL'],['SetCover /Publiccover','PASSprobes'],['Gallery','API PASS / FE MISSING'],['No-imagecase','PASSbrowserfallback'],['No-listduplication /Norevenuemultiplication','PASSnonzerofixture'],['NoN+1','PASSpubliccoversource/network'],['RealDBintegration','VERIFIEDobservedpaths'],['Mixedmutationdeadlockstress','NOT VERIFIED']])}

## 32. 45 UC Final Status

${table(['Status','Count'],Object.entries(ucCounts))}
${table(['UC','DB','BE','FE','INT','STATUS','Reason'],rows.map(r=>[r[0],...r.slice(6,12)]))}
NOT VERIFIED UC count0 nghĩa mỗi UC cóít nhấtsource/traces vàmộtnhánh integration tươngứng; vẫn cóPARTIAL cho paths chưađủ. Không suyra0NOT VERIFIED=fullcoverage.

## 33. Critical Questions

${score([['Can two customers buy same seat?','NO trongrace1seat/overlapmulti đã thử;1winner+409;fullloadNOT VERIFIED.'],['Can Manager access foreign cinema?','NO trongread/writeprobes;future/revoked/lockeddenied.'],['Can Customer access another order?','NO GET/pay/result/complaintreferenceprobes404.'],['Can Client manipulate price?','NO totalspoof400;DBtựtính. CóDATA-001oldnegativeorder khôngchứngminhclientexploit.'],['Can wrong role be assigned to cinema?','NO customerassignment400;baselinesairole0. AdmincreateCustomerroleBUG-015 làvấnđềkhác.'],['Can complaint reference another customer order?','NO foreignreference404;NULLsupported.'],['Can historical ticket price change?','NO khiđổiBANGGIA/product/promo trongtest;oldvalues85000/50000/13500giữ. Rename/schedule/casthistoryimmutabilitynotexhaustive.'],['Can old payment history be overwritten?','YES livecancelcascadeđổiThànhcông→Đãhoàntiền củaownorder36;CONFLICT001. NormalattemptretryappendPASS.'],['Can cinema have more than one cover?','NO unique filteredindex và12concurrentrequestsfinal1;zeroisallowed.'],['Can cinema images duplicate revenue rows?','NO trongsource vànonzerotest92000invariant;khôngJOINimages. Reviewviewkhác cómultiplyBUG018.'],['Does any main frontend flow still use mock data?','NO found;browserusesrealAPIs/DB. /customerplaceholderkhôngphảimockbookingflow.'],['Does any Backend business flow execute raw SQL?','NO productionbackendquery/batchcalls;executeProcedurewhitelist. AuditSELECTscripts khôngphảibusinesscode.']])}

## 34. Prioritized Fix Plan

**FIX-P0:** DATA-001: bảo toàn evidence và đối chiếu order20tổng âm, xác định lineage rồi lập remediation córeview. Không tựtính lại lịch sử từpricehiện tại. Chưa cóP0HTTPsecurity/doublebookingexploitproven.

**FIX-P1:** Chọn source/DBbaseline (CONFLICT003); thống nhất timezoneBUG001; xác nhận noRefund/latecallbackpolicy (CONFLICT001/002) và ledger/history; sửaManagerseatUI004, imageupdate005,Adminstatus006, roleedit007, Adminpassword014; permission enforcement019 cầnproveisolatedRBACmatrix trước release.

**FIX-P2:** Enum/error/validation002/003/009/010/011/012/013; profile015; unknownfood016; duplicateassignment017; reviewCOUNT018; permissionarea020; GAP001..006. Mỗifix cầnbrowser/API/SP/finalDBregression theo [FINDINGS](./FINDINGS.md), gồmnegative/concurrency vàkhôngpháhistory/crossmodule.

**FIX-P3:** Cleanupdocs45UC/ADM17 vàphaseREADME; làm rõcounterhistoricalusage/stalestatus; sửanoSQLscannerfalsepositive; bổsungtestharnessisolatedSPfixtures/protectedcleanup. Performancefix chỉsauactualplan/IO/loadmeasurement.

Các mục này là đềxuất. **KHÔNG APPLY FIX TRONG TASK NÀY.**

## 35. Final Verdict

**AUDIT FOUND ISSUES – FIX REQUIRED**

Có lỗi tái hiện trênDB/API/browser, sai dữ liệu tài chính cũ vàsource/deploymentdrift. Testxanh không chứngminh45UCconsistent; finalmatrix giữFAIL/PARTIAL theo bằngchứng. Môi trường thật hoạt động, nênverdict chọnFOUNDISSUES; phầnchưađượcverify được công bố riêng trongtestgaps, không phải lời chứngnhậnexhaustivePASS.

Đã xuấtreport vàevidence; dừng ởaudit. Khôngfix,commit,push,rollbackDB,alterobjects hoặcxóadữliệucũ. Fixtures cùngmanifest được giữ đểtaskfixreview/reproduce sau này. Các audit scripts tạo dữ liệu khi chạy, không idempotent tấtcả; khôngrerun mù vàoDB đang dùng.
`;
write('REPORT.md',report);
const evidenceNames=fs.readdirSync(out).sort();write('EVIDENCE_INDEX.md','# Evidence index\n\nJSON transcripts redact JWT/password. Raw error/blocker files là audit trail, một số harness issue đã resolved; normalized checks là bản phân loại đã đối chiếu. Metadata baseline/live-after là hai thời điểm khác nhau; không ghi đè baseline data scans.\n\n'+evidenceNames.map(n=>`- ${ev(n)}`).join('\n')+'\n');
console.log(JSON.stringify({bugs:bugs.length,data:data.length,gaps:gaps.length,conflicts:conflicts.length,UC:rows.length,status:ucCounts,evidenceFiles:evidenceNames.length,report:path.join(dir,'REPORT.md')},null,2));
