import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { root,evidenceRoot,read,write,env } from './common.mjs';
import { walk } from '../db/lib.mjs';
const sha=s=>crypto.createHash('sha256').update(s.replace(/\r\n/g,'\n')).digest('hex'),r=n=>JSON.parse(read(path.join(evidenceRoot,n+'.json')));
// The pre-task freeze used readFileSync, including a UTF-8 BOM if present.
// Use exactly that reader here; common.read intentionally strips BOM for SQL.
const preserved=r('preserved-before');for(const row of preserved.files)assert.equal(sha(fs.readFileSync(path.join(root,row.file),'utf8')),row.sha256,row.file);
const checks=r('checks'),database=checks.database;assert.equal(checks.status,'PASS');assert.equal(checks.checks.length,15);assert.ok(checks.checks.every(row=>row.status==='PASS'&&(row.skipped??0)===0));
for(const n of ['sql-tests','api-tests','movie-actor-concurrency','r22-regression','r21-regression','r1-regression','r11-sql','r11-concurrency','r12-sql','r12-nested','r12-concurrency','r21-sql','r21-api','r21-parents','r22-sql','r22-api','r22-promotion','migration-replay']){assert.equal(r(n).status,'PASS',n);assert.equal(r(n).database,database,n);}
for(const n of ['browser','r22-browser','main-test-isolation','main-migration','main-readonly','source-parity','current-audit-status'])assert.equal(r(n).status,'PASS',n);
assert.equal(r('r22-browser').result.checks.length,10);
const sql=r('sql-tests'),api=r('api-tests'),races=r('movie-actor-concurrency'),migration=r('main-migration');
assert.equal(sql.positive.length,9);assert.equal(sql.negative.length,30);assert.deepEqual(sql.rollbackInjection.observed,{oldRemaining:0,newInserted:2});assert.deepEqual(sql.rollbackInjection.final,sql.rollbackInjection.initial);assert.deepEqual(sql.outerSuccess.session,{trancount:1,xactState:1});assert.equal(sql.outerDoomedFailure.session.trancount,0);assert.equal(sql.outerTriggerFailure.session.trancount,0);
assert.equal(api.cases.length,19);assert.equal(api.requests.length,59);assert.equal(races.replacements.length,4);assert.equal(races.actorDelete.length,4);assert.equal(races.movieDelete.length,2);
for(const row of [...races.replacements,...races.actorDelete,...races.movieDelete]){assert.match(row.blocking.wait_type,/^LCK_M_/);assert.notEqual(row.spids.a,row.spids.b);for(const session of Object.values(row.sessions)){assert.equal(session.trancount,0);assert.equal(session.xactState,0);}}
assert.equal(r('r22-sql').cases.length,28);assert.equal(r('r22-api').requests.length,54);assert.equal(r('r22-promotion').lastQuota.length,2);assert.equal(r('r22-promotion').adminRaces.length,12);
assert.equal(r('r21-sql').cases.length,30);assert.equal(r('r21-api').requests.length,107);assert.equal(r('r21-parents').cases.length,14);assert.equal(r('r12-concurrency').stressRaces,125);
assert.equal(migration.sourceParity.modules,159);assert.equal(migration.backup.restoreVerifyOnly,'PASS');assert.deepEqual(migration.before.data,migration.after.data);assert.deepEqual(migration.after.data,r('main-before-tests').state.data);assert.deepEqual([...migration.changedModules].sort(),['sp_Admin_Actor_Delete','sp_Admin_MovieActor_Set']);assert.equal(migration.after.data.length,27);
assert.equal(r('current-audit-status').matrix.rows.find(row=>row.uc==='ADM-09').status,'PARTIAL');
for(const file of walk(path.join(root,'backend/src')))if(/\.(js|mjs)$/.test(file))assert.ok(!/new\s+(?:sql\.)?Transaction\b|\.transaction\s*\(|new\s+Mutex\b|scripts\/r31/.test(read(file)),file);
for(const file of walk(evidenceRoot))if(/\.(json|txt|md|patch|sql|js|jsx)$/.test(file)){const source=read(file);if(env.DB_PASSWORD)assert.ok(!source.includes(env.DB_PASSWORD),'Configured password in '+file);assert.ok(!/"token"\s*:\s*"eyJ/.test(source),'JWT in '+file);}
execFileSync('git',['-c','core.safecrlf=false','diff','--check'],{cwd:root,encoding:'utf8'});
const criteria=[
 ['Trace canonical writers','trace-before.md'],['Root cause I08','trace-before.md'],['Safe JSON parsing','sql-tests.json'],['Malformed differs from empty','sql-tests.json'],['Duplicate contract enforced','sql-tests.json'],['Movie validated','sql-tests.json'],['All references before DELETE','sql-tests.json'],['One invalid fails whole request','api-tests.json'],['No silent omission','sql-tests.json'],['No auto-created actor','sql-tests.json'],['SQL-owned transaction','sql-tests.json'],['TRY/CATCH rollback convention','sql-tests.json'],['No partial insert','sql-tests.json'],['Old cast retained on validation failure','sql-tests.json'],['Write-phase failure rolls back','sql-tests.json'],['Explicit [] clears;null/omitted reject','api-tests.json'],['Only target movie changes','sql-tests.json'],['Backend mapping correct','api-tests.json'],['Admin RBAC preserved','api-tests.json'],['SQL positives PASS','sql-tests.json'],['SQL negatives PASS','sql-tests.json'],['Rollback injection PASS','sql-tests.json'],['Real API PASS','api-tests.json'],['Concurrent replacement has no mixed cast','movie-actor-concurrency.json'],['Backend regression PASS','checks.json'],['SQL regression PASS','sql-regression-detail.txt'],['No-SQL audit PASS','no-sql.txt'],['Source/schema parity PASS','source-parity.json'],['No added table','main-migration.json'],['PHIM_DIENVIEN schema preserved','main-migration.json'],['No business SQL in backend','no-sql.txt'],['No frontend redesign','browser.json'],['Real persisted state evidence','api-tests.json'],['I08 RESOLVED with evidence','current-audit-status.json']
].map(([criterion,evidence],i)=>({id:i+1,criterion,evidence,status:'PASS'}));assert.equal(criteria.length,34);
write(path.join(evidenceRoot,'final-checks.json'),{at:new Date().toISOString(),database,status:'PASS',acceptedArtifactsPreserved:preserved.files.length,sqlPositives:9,sqlNegatives:30,apiCases:19,apiRequests:59,replacementRaces:4,actorDeleteRaces:4,movieDeleteRaces:2,browserChecks:r('browser').result.checks.length,backendTests:129,frontendTests:49,skipCount:0,r1Regression:'PASS',r21Regression:'PASS',r22Regression:'PASS',sourceParityModules:159,tablesPreserved:27,mainDataPreserved:'PASS',credentialsScan:'PASS',runtimeTransactionScan:'PASS',diffWhitespace:'PASS',exitCriteria:criteria});
console.log(`PASS final R3.1: ${preserved.files.length} accepted artifacts preserved;34/34 criteria;real SQL/API/rollback/races;data27/modules159;stop before R3.2.`);
