-- R3B: in-place module update. No table/permission/role/grant DML or schema changes.
-- Execute through scripts/r3b/deploy.mjs for atomic application, backup and data preservation.
:on error exit
:r ./05_functions/fn_KiemTraQuanLyRapScope.sql
:r ./05_functions/fn_KiemTraQuyenNguoiDung.sql
:r ./08_procedures/admin/sp_Admin_Actor_Create.sql
:r ./08_procedures/admin/sp_Admin_Actor_Delete.sql
:r ./08_procedures/admin/sp_Admin_Actor_List.sql
:r ./08_procedures/admin/sp_Admin_Actor_Update.sql
:r ./08_procedures/admin/sp_Admin_Assignment_Create.sql
:r ./08_procedures/admin/sp_Admin_Assignment_List.sql
:r ./08_procedures/admin/sp_Admin_Cinema_Create.sql
:r ./08_procedures/admin/sp_Admin_Cinema_Delete.sql
:r ./08_procedures/admin/sp_Admin_Cinema_Update.sql
:r ./08_procedures/admin/sp_Admin_Dashboard.sql
:r ./08_procedures/admin/sp_Admin_Genre_Create.sql
:r ./08_procedures/admin/sp_Admin_Genre_Delete.sql
:r ./08_procedures/admin/sp_Admin_Genre_Update.sql
:r ./08_procedures/admin/sp_Admin_Movie_Create.sql
:r ./08_procedures/admin/sp_Admin_Movie_Delete.sql
:r ./08_procedures/admin/sp_Admin_Movie_Update.sql
:r ./08_procedures/admin/sp_Admin_MovieActor_Set.sql
:r ./08_procedures/admin/sp_Admin_Permission_Create.sql
:r ./08_procedures/admin/sp_Admin_Permission_Delete.sql
:r ./08_procedures/admin/sp_Admin_Permission_List.sql
:r ./08_procedures/admin/sp_Admin_Permission_Update.sql
:r ./08_procedures/admin/sp_Admin_Product_Create.sql
:r ./08_procedures/admin/sp_Admin_Product_Delete.sql
:r ./08_procedures/admin/sp_Admin_Product_Update.sql
:r ./08_procedures/admin/sp_Admin_Promotion_Create.sql
:r ./08_procedures/admin/sp_Admin_Promotion_Delete.sql
:r ./08_procedures/admin/sp_Admin_Promotion_List.sql
:r ./08_procedures/admin/sp_Admin_Promotion_Update.sql
:r ./08_procedures/admin/sp_Admin_Report_Revenue.sql
:r ./08_procedures/admin/sp_Admin_Role_Create.sql
:r ./08_procedures/admin/sp_Admin_Role_Delete.sql
:r ./08_procedures/admin/sp_Admin_Role_List.sql
:r ./08_procedures/admin/sp_Admin_Role_Update.sql
:r ./08_procedures/admin/sp_Admin_RolePermission_Set.sql
:r ./08_procedures/admin/sp_Admin_User_Create.sql
:r ./08_procedures/admin/sp_Admin_User_List.sql
:r ./08_procedures/admin/sp_Admin_User_UpdateStatus.sql
:r ./08_procedures/booking/sp_Booking_Create.sql
:r ./08_procedures/customer/sp_Complaint_Create.sql
:r ./08_procedures/customer/sp_Complaint_GetByCustomer.sql
:r ./08_procedures/customer/sp_Complaint_ListByCustomer.sql
:r ./08_procedures/manager/sp_Manager_Dashboard.sql
:r ./08_procedures/manager/sp_Manager_ListAssignedCinemas.sql
:r ./08_procedures/manager/sp_Manager_Pricing_Create.sql
:r ./08_procedures/manager/sp_Manager_Pricing_List.sql
:r ./08_procedures/manager/sp_Manager_Pricing_Update.sql
:r ./08_procedures/manager/sp_Manager_Revenue.sql
:r ./08_procedures/manager/sp_Manager_Room_Create.sql
:r ./08_procedures/manager/sp_Manager_Room_Delete.sql
:r ./08_procedures/manager/sp_Manager_Room_List.sql
:r ./08_procedures/manager/sp_Manager_Room_Update.sql
:r ./08_procedures/manager/sp_Manager_Seat_BatchCreate.sql
:r ./08_procedures/manager/sp_Manager_Seat_Create.sql
:r ./08_procedures/manager/sp_Manager_Seat_Delete.sql
:r ./08_procedures/manager/sp_Manager_Seat_ListByRoom.sql
:r ./08_procedures/manager/sp_Manager_Seat_Update.sql
:r ./08_procedures/manager/sp_Manager_Showtime_Cancel.sql
:r ./08_procedures/manager/sp_Manager_Showtime_Create.sql
:r ./08_procedures/manager/sp_Manager_Showtime_List.sql
:r ./08_procedures/manager/sp_Manager_Showtime_Update.sql
:r ./08_procedures/customer/sp_Order_GetDetailByCustomer.sql
:r ./08_procedures/customer/sp_Order_ListByCustomer.sql
:r ./08_procedures/payment/sp_Payment_CreateAttempt.sql
:r ./08_procedures/payment/sp_Payment_UpdateResult.sql
:r ./08_procedures/public/sp_Promotion_Validate.sql
:r ./08_procedures/system/sp_PhanCongQuanLyRap.sql
:r ./08_procedures/customer/sp_Review_Create.sql
:r ./08_procedures/system/sp_Showtime_CancelCascade.sql
:r ./08_procedures/support/sp_Support_Complaint_AddProcessing.sql
:r ./08_procedures/support/sp_Support_Complaint_GetDetail.sql
:r ./08_procedures/support/sp_Support_Complaint_GetOrderReference.sql
:r ./08_procedures/support/sp_Support_Complaint_List.sql
:r ./08_procedures/support/sp_Support_Complaint_UpdateStatus.sql
:r ./08_procedures/payment/sp_XuLyThanhToan.sql
:r ./08_procedures/admin/usp_Admin_Assignment_Update.sql
:r ./08_procedures/admin/usp_Admin_Cinema_List.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_Create.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_Delete.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_List.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_SetCover.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_Update.sql
:r ./08_procedures/admin/usp_Admin_Movie_List.sql
:r ./08_procedures/admin/usp_Admin_Pricing_Create.sql
:r ./08_procedures/admin/usp_Admin_Pricing_List.sql
:r ./08_procedures/admin/usp_Admin_Pricing_Update.sql
:r ./08_procedures/admin/usp_Admin_Product_List.sql
:r ./08_procedures/admin/usp_Admin_RolePermission_List.sql
:r ./08_procedures/admin/usp_Admin_Room_Create.sql
:r ./08_procedures/admin/usp_Admin_Room_Delete.sql
:r ./08_procedures/admin/usp_Admin_Room_List.sql
:r ./08_procedures/admin/usp_Admin_Room_Update.sql
:r ./08_procedures/admin/usp_Admin_Seat_Create.sql
:r ./08_procedures/admin/usp_Admin_Seat_Delete.sql
:r ./08_procedures/admin/usp_Admin_Seat_List.sql
:r ./08_procedures/admin/usp_Admin_Seat_Update.sql
:r ./08_procedures/admin/usp_Admin_Showtime_Cancel.sql
:r ./08_procedures/admin/usp_Admin_Showtime_Create.sql
:r ./08_procedures/admin/usp_Admin_Showtime_List.sql
:r ./08_procedures/admin/usp_Admin_Showtime_Update.sql
:r ./08_procedures/admin/sp_Admin_Genre_List.sql
