import {createJourney} from './journey-fixture.mjs';
import {helpers} from './journey-helpers.mjs';
import {customer} from './customer.mjs';
export async function run(t){
 const f=await createJourney(t),h=helpers(t);await customer(t,h,f);
 const {assert,check,go,navigate,fill,labeled,click,until,evaluate,pause,fault,query,sqlCheck}=t;
 const waitText=text=>until(`document.body.innerText.includes(${JSON.stringify(text)})`);
 const [b]=(await query('SELECT TOP(1) KhieuNaiID id,TieuDe title FROM dbo.KHIEUNAI WHERE DonDatVeID IS NULL ORDER BY KhieuNaiID;')).recordset;
 await check('CRITICAL-I21-CUSTOMER-STATUS-NETWORK-RETRY',['KH-14'],'CONTROLLED_TRANSPORT',async()=>{
  for(const config of [{status:403},{status:404},{status:503},{fail:'InternetDisconnected'}]){
   const rule=fault('/api/orders',{...config,times:20});await go('/complaints?orderId='+f.order);await until("document.querySelector('[role=alert]')");assert.ok(await evaluate("document.querySelector('select').disabled"));await pause(100);rule.remaining=0;await click('Thử lại');await until(`!document.querySelector('[role=alert]')&&document.querySelector('select').value==='${f.order}'`);
  }
 });
 await check('CRITICAL-CUSTOMER-UNLINKED-CREATE',['KH-14'],'REAL_BROWSER_SQL',async()=>{
  await go('/complaints');await until("document.querySelector('select')&&!document.querySelector('select').disabled");for(const [label,value]of [['Loại khiếu nại','R82 unlinked'],['Tiêu đề','R82 Browser Unlinked'],['Nội dung','R82 unlinked body']])await labeled(label,value);await click('Gửi khiếu nại');await waitText('Đã gửi khiếu nại.');await sqlCheck('SQL-UNLINKED-CREATE',"SELECT DonDatVeID orderId,NguoiDungID owner FROM dbo.KHIEUNAI WHERE TieuDe=N'R82 Browser Unlinked';",{},r=>{assert.equal(r.length,1);assert.equal(r[0].orderId,null);assert.equal(r[0].owner,f.customer);});
 });
 await t.login('ADMIN');await click('Khiếu nại');await waitText('R82 Journey Complaint');
 await check('CRITICAL-I11-LATE-REFERENCE',['ADM-15'],'CONTROLLED_TRANSPORT',async()=>{
  fault(`/admin/complaints/${f.complaint}/order-reference`,{delay:800});await click(`Mở khiếu nại #${f.complaint} · R82 Journey Complaint`);await until(`document.querySelector('h3')?.textContent.startsWith('#${f.complaint} ')`);await pause(100);await click(`Mở khiếu nại #${b.id} · ${b.title}`);await waitText('không gắn với đơn đặt vé');await pause(1000);assert.ok(!(await t.visible()).includes('R82 Journey Snack'));assert.ok((await evaluate("document.querySelector('h3').textContent")).startsWith('#'+b.id+' '));
 });
 await check('CRITICAL-I21-ADMIN-STATUS-NETWORK-RETRY',['ADM-15'],'CONTROLLED_TRANSPORT',async()=>{
  for(const config of [{status:403},{status:404},{status:503},{fail:'InternetDisconnected'}]){fault(`/admin/complaints/${f.complaint}/order-reference`,config);await click(`Mở khiếu nại #${f.complaint} · R82 Journey Complaint`);await until("document.querySelector('[role=alert]')");assert.ok(!(await t.visible()).includes('R82 Journey Snack'));await click('Thử lại');await waitText('R82 Journey Snack');assert.ok(!await evaluate("document.querySelector('[role=alert]')"));}
 });
 await t.login('CSKH');await waitText('R82 Journey Complaint');
 const supportOpen=id=>evaluate(`(()=>{const b=[...document.querySelectorAll('.catalog-list button')].find(n=>n.innerText.includes('#${id} ·'));if(!b)throw Error('Missing complaint');b.click()})()`);
 await check('CRITICAL-I15-STALE-ERROR-AFTER-SUCCESS',['CSKH-02'],'CONTROLLED_TRANSPORT',async()=>{
  fault('/support/complaints?search=',{delay:800,status:500});await fill('input[aria-label="Tìm khiếu nại"]','R82 Journey Complaint');await pause(120);await fill('input[aria-label="Tìm khiếu nại"]',b.title);await until(`document.querySelector('.catalog-list')?.innerText.includes(${JSON.stringify(b.title)})`);await pause(1000);assert.ok(!await evaluate("document.querySelector('[role=alert]')"));assert.ok((await evaluate("document.querySelector('.catalog-list').innerText")).includes(b.title));
 });
 await check('CRITICAL-CSKH-EXISTING-REFERENCE-GUARD',['CSKH-03','CSKH-04'],'CONTROLLED_TRANSPORT',async()=>{
  await fill('input[aria-label="Tìm khiếu nại"]','');await waitText('R82 Journey Complaint');fault(`/support/complaints/${f.complaint}/order-reference`,{delay:800,status:500});await supportOpen(f.complaint);await waitText('R82 owned linked complaint');await pause(100);await supportOpen(b.id);await waitText('không gắn với đơn đặt vé');await pause(1000);assert.ok(!await evaluate("document.querySelector('[role=alert]')"));assert.ok(!(await t.visible()).includes('R82 Journey Snack'));
 });
 await check('CRITICAL-CSKH-PENDING-WRITES-CURRENT-FILTER',['CSKH-02','CSKH-03','CSKH-05','CSKH-06'],'CONTROLLED_TRANSPORT',async()=>{
  await fill('input[aria-label="Tìm khiếu nại"]','R82 Journey Complaint');await waitText('R82 Journey Complaint');await supportOpen(f.complaint);await waitText('R82 owned linked complaint');await fill('textarea[aria-label="Nội dung xử lý"]','R82 current-filter processing');
  fault(`/support/complaints/${f.complaint}/processings`,{method:'POST',delay:700});await evaluate("(()=>{const b=[...document.querySelectorAll('button')].find(n=>n.textContent==='Ghi diễn biến');b.click();b.click()})()");await fill('input[aria-label="Tìm khiếu nại"]',b.title);await until(`document.querySelector('.catalog-list')?.innerText.includes(${JSON.stringify(b.title)})`);await supportOpen(b.id);await waitText('không gắn với đơn đặt vé');await pause(1000);assert.equal(await evaluate("document.querySelector('input[aria-label=\"Tìm khiếu nại\"]').value"),b.title);assert.ok((await evaluate("document.querySelector('h2').textContent")).startsWith('#'+b.id+' '));
  await fill('select[aria-label="Trạng thái mới"]','Đã giải quyết');fault(`/support/complaints/${b.id}/status`,{method:'PUT',delay:700});await evaluate("(()=>{const b=[...document.querySelectorAll('button')].find(n=>n.textContent==='Cập nhật trạng thái');b.click();b.click()})()");await fill('input[aria-label="Tìm khiếu nại"]','R82 Journey Complaint');await until("document.querySelector('.catalog-list')?.innerText.includes('R82 Journey Complaint')");await supportOpen(f.complaint);await waitText('R82 current-filter processing');await pause(1000);assert.equal(await evaluate("document.querySelector('input[aria-label=\"Tìm khiếu nại\"]').value"),'R82 Journey Complaint');assert.ok((await evaluate("document.querySelector('h2').textContent")).startsWith('#'+f.complaint+' '));
  await sqlCheck('SQL-CSKH-PENDING-EXACT-TARGETS',"SELECT k.KhieuNaiID id,k.TrangThai status,COUNT(x.XuLyID) events FROM dbo.KHIEUNAI k LEFT JOIN dbo.XULY_KHIEUNAI x ON x.KhieuNaiID=k.KhieuNaiID WHERE k.KhieuNaiID IN(@A,@B) GROUP BY k.KhieuNaiID,k.TrangThai ORDER BY k.KhieuNaiID;",{A:f.complaint,B:b.id},r=>{assert.equal(r.length,2);assert.ok(r.every(row=>row.events===1));assert.equal(r.find(row=>row.id===b.id).status,'Đã giải quyết');});
 });
 await t.resume('KHACH_HANG');
 await check('CRITICAL-I19-A-B-A-PRODUCTS-PENDING',['KH-05','KH-06','KH-08','KH-09'],'CONTROLLED_TRANSPORT',async()=>{
  const shows=(await query('SELECT TOP(2) SuatChieuID id FROM dbo.vw_LichChieuChiTiet WHERE IsBookable=1 AND PhongID<>@Room ORDER BY SuatChieuID;',{Room:f.room})).recordset;assert.equal(shows.length,2);
  await go('/booking/'+shows[0].id);await until("document.querySelector('.booking-product input')&&document.querySelector('.seat-button:not(:disabled)')");await evaluate("document.querySelector('.seat-button:not(:disabled)').click()");await fill('.booking-product input',3);await labeled('Mã khuyến mãi',f.code);fault('/api/products',{delay:800,times:2});await navigate('/booking/'+shows[1].id);await pause(100);await navigate('/booking/'+shows[0].id);await until("document.querySelector('.booking-product input')");await pause(1000);assert.ok(await evaluate("[...document.querySelectorAll('.booking-product input')].every(n=>n.value==='0')"));assert.equal(await evaluate("document.querySelectorAll('.seat-button[aria-pressed=true]').length"),0);assert.equal(await evaluate("document.querySelector('input[maxlength=\"50\"]').value"),'');
 });
 await check('CRITICAL-PROMOTION-EDIT-WHILE-PENDING',['KH-09'],'CONTROLLED_TRANSPORT',async()=>{
  await go('/booking/'+f.showB);await until("document.querySelector('.seat-button[aria-label^=\"A4 —\"]')");await evaluate("document.querySelector('.seat-button[aria-label^=\"A4 —\"]').click()");await pause(80);await labeled('Mã khuyến mãi',f.code);fault('/promotions/validate',{method:'POST',delay:800});await click('Áp dụng');await labeled('Mã khuyến mãi','R82INVALID');await pause(1000);assert.ok(!(await t.visible()).includes('Giảm tạm tính:'));await click('Áp dụng');await until("document.querySelector('#promotion-heading').parentElement.querySelector('[role=status]')");assert.ok(!(await t.visible()).includes('Giảm tạm tính:'));
 });
 await check('CRITICAL-REGISTER-DUPLICATE-PHONE',['KH-01'],'REAL_BROWSER_SQL',()=>h.noWrite('register-duplicate-phone',async()=>{
  const phone=(await query('SELECT SoDienThoai phone FROM dbo.NGUOIDUNG WHERE NguoiDungID=@ID;',{ID:f.customer})).recordset[0].phone;assert.ok(phone);
  await go('/register');await until("document.querySelector('input[type=email]')");for(const [label,value]of [['Họ tên *','R82 Duplicate Phone'],['Email *','r82.duplicate.phone@example.invalid'],['Mật khẩu *',t.actors[0].password],['Số điện thoại',phone]])await labeled(label,value);await h.submit('.auth-card form');await waitText('Số điện thoại đã được sử dụng.');
 }));
 await check('CRITICAL-MANAGER-METRIC-SEMANTICS',['QLR-01','QLR-08'],'REAL_BROWSER_SQL',async()=>{
  await query("DECLARE @Room int,@Start datetime2=DATEADD(HOUR,1,dbo.fn_BayGio());INSERT dbo.PHONGCHIEU(RapID,TenPhong,LoaiPhong,TrangThai) VALUES(@Cinema,N'R82 Inactive Metrics Room',N'2D',N'Ngưng hoạt động');SET @Room=SCOPE_IDENTITY();INSERT dbo.GHE(PhongID,HangGhe,SoGhe,LoaiGhe,TrangThai) SELECT @Room,'M',n,N'Thường',N'Hoạt động' FROM(VALUES(1),(2),(3),(4))v(n);INSERT dbo.SUATCHIEU(PhimID,PhongID,ThoiGianBatDau,ThoiGianKetThuc,DinhDang,GiaVeCoBan,TrangThai) VALUES(@Movie,@Room,@Start,DATEADD(MINUTE,90,@Start),N'2D',100,N'Mở bán'),(@Movie,@Room,DATEADD(HOUR,3,@Start),DATEADD(MINUTE,270,@Start),N'2D',100,N'Đã hủy');",{Cinema:f.cinema,Movie:f.movie});
  t.save('metric-semantics-fixture.json',{scope:'TEST_ONLY_FIXTURE',cinema:f.cinema,operation:'Four active seats in inactive room; one today show and one canceled today show; existing genuinely paid order'});
  await t.login('QUAN_LY_RAP');await fill('select[aria-label="Rạp hiện tại"]',f.cinema);await waitText('R82 Inactive Metrics Room');
  const rows=await sqlCheck('SQL-METRIC-INDEPENDENT',"SELECT (SELECT COUNT(*) FROM dbo.PHONGCHIEU WHERE RapID=@Cinema AND TrangThai=N'Hoạt động') rooms,(SELECT COUNT(*) FROM dbo.GHE g JOIN dbo.PHONGCHIEU r ON r.PhongID=g.PhongID WHERE r.RapID=@Cinema AND g.TrangThai=N'Hoạt động') seats,(SELECT COUNT(*) FROM dbo.SUATCHIEU s JOIN dbo.PHONGCHIEU r ON r.PhongID=s.PhongID WHERE r.RapID=@Cinema AND dbo.fn_NgayKinhDoanh(s.ThoiGianBatDau)=dbo.fn_HomNay() AND s.TrangThai<>N'Đã hủy') shows;",{Cinema:f.cinema},r=>{assert.equal(r[0].rooms,1);assert.equal(r[0].seats,14);assert.equal(r[0].shows,2);});const text=await t.visible();assert.ok(text.includes('Phòng hoạt động: '+rows[0].rooms));assert.ok(text.includes('Ghế: '+rows[0].seats));assert.ok(text.includes('Suất hôm nay: '+rows[0].shows));assert.ok(text.includes('Đơn đã thanh toán hôm nay: 1'));
 });
 await check('CRITICAL-REPORT-UTC7-FAILED-RECEIPT',['QLR-08','QLR-09','ADM-16'],'REAL_BROWSER_SQL',async()=>{
  const originals=(await query('SELECT ThanhToanID id,CONVERT(varchar(33),NgayThanhToan,126) paidAt FROM dbo.THANHTOAN WHERE DonDatVeID=@Order;',{Order:f.order})).recordset;
  await query("UPDATE dbo.THANHTOAN SET NgayThanhToan=DATEADD(MINUTE,-1,DATEADD(HOUR,-7,CONVERT(datetime2,dbo.fn_HomNay()))) WHERE DonDatVeID=@Order;INSERT dbo.THANHTOAN(DonDatVeID,PhuongThuc,SoTien,NgayTao,NgayThanhToan,TrangThai) VALUES(@Order,'MOMO',777777,dbo.fn_BayGio(),dbo.fn_BayGio(),N'Thất bại');",{Order:f.order});
  const day=(await query('SELECT CONVERT(varchar(10),DATEADD(DAY,-1,dbo.fn_HomNay()),23) previous;')).recordset[0].previous;
  t.save('receipt-midnight-fixture.json',{scope:'TEST_ONLY_FIXTURE',order:f.order,operation:'Owned actual UI-paid receipt moved to23:59 of preceding UTC+7 business date; add explicit failed-payment fixture, excluded from cash receipts'});
  try{
   await t.resume('QUAN_LY_RAP');await fill('select[aria-label="Rạp hiện tại"]',f.cinema);await waitText('Đơn đã thanh toán hôm nay: 0');await fill('input[aria-label="Từ ngày doanh thu"]',f.today);await fill('input[aria-label="Đến ngày doanh thu"]',f.today);await click('Lọc doanh thu');await waitText('Không có doanh thu trong khoảng đã chọn.');await fill('input[aria-label="Từ ngày doanh thu"]',day);await fill('input[aria-label="Đến ngày doanh thu"]',day);await click('Lọc doanh thu');await waitText('1175.5');
   await t.resume('ADMIN');await click('Doanh thu');await waitText('Tổng hợp doanh thu');await labeled('Từ ngày',day);await labeled('Đến ngày',day);await click('Lọc doanh thu');await waitText('R82 Journey Movie');assert.ok((await t.visible()).includes('1175.5'));assert.ok(!(await t.visible()).includes('777777'));
   await sqlCheck('SQL-MIDNIGHT-CASH-LEDGER',"SELECT CONVERT(varchar(10),dbo.fn_NgayKinhDoanh(NgayThanhToan),23) businessDate,SoTien receipt FROM dbo.THANHTOAN WHERE DonDatVeID=@Order AND TrangThai=N'Thành công';",{Order:f.order},r=>{assert.equal(r.length,1);assert.equal(r[0].businessDate,day);assert.equal(r[0].receipt,1175.5);});
  }finally{for(const row of originals)await query('UPDATE dbo.THANHTOAN SET NgayThanhToan=CONVERT(datetime2(7),@PaidAt,126) WHERE ThanhToanID=@ID;',{ID:row.id,PaidAt:row.paidAt});}
 });
 await check('CRITICAL-MANAGER-NO-ASSIGNMENTS',['QLR-01'],'REAL_BROWSER_SQL',async()=>{
  const original=(await query('SELECT PhanCongID id,TrangThai status FROM dbo.PHANCONG_RAP WHERE NguoiDungID=@ID;',{ID:f.manager})).recordset;
  await query("UPDATE dbo.PHANCONG_RAP SET TrangThai=N'Đã hủy' WHERE NguoiDungID=@ID;",{ID:f.manager});
  try{await t.resume('QUAN_LY_RAP','Bạn không có phân công rạp còn hiệu lực.');assert.ok(!await evaluate("document.querySelector('form[aria-label=\"Tạo phòng\"]')"));}
  finally{for(const row of original)await query('UPDATE dbo.PHANCONG_RAP SET TrangThai=@Status WHERE PhanCongID=@ID;',{ID:row.id,Status:row.status});}
 });
 await t.resume('KHACH_HANG');
 await check('CRITICAL-REVIEW-INVALID-NO-WRITE',['KH-13'],'REAL_BROWSER_SQL',()=>h.noWrite('review-invalid',async()=>{
  for(const body of [{rating:0},{rating:6},{rating:5,content:'x'.repeat(1001)},{rating:5,ownerId:f.otherCustomer}])await h.deny('POST',`/movies/${f.movie}/reviews`,body,400);
 }));
 await check('CRITICAL-PAYMENT-FAILED-THEN-UI-RETRY',['KH-10'],'REAL_BROWSER_SQL',async()=>{
  const first=await evaluate(`(async()=>{const headers={'Authorization':'Bearer '+sessionStorage.getItem('cinema_access_token'),'Content-Type':'application/json'};const a=await fetch('/api/orders/${f.pendingOrder}/payments',{method:'POST',headers,body:JSON.stringify({paymentMethod:'MOMO'})});if(a.status!==201)throw Error('Payment attempt '+a.status);const p=(await a.json()).payment;const r=await fetch('/api/orders/${f.pendingOrder}/payments/'+p.id+'/result',{method:'POST',headers,body:JSON.stringify({status:'Thất bại'})});if(r.status!==200)throw Error('Failed payment result '+r.status);return {attempt:p.id,status:r.status}})()`);
  t.save('failed-payment-setup.json',{kind:'REAL_BROWSER_SQL',scope:'Actual authorized REST creates failed attempt before testing UI retry; no transport substitution',order:f.pendingOrder,...first});
  await go('/orders/'+f.pendingOrder+'/payment');await waitText('Thất bại');await until("[...document.querySelectorAll('button')].some(n=>n.textContent==='Xác nhận thanh toán'&&!n.disabled)");await click('Xác nhận thanh toán');await waitText('Đã xác nhận thanh toán thành công.');await sqlCheck('SQL-PAYMENT-FAILED-RETRY',"SELECT TrangThai status,SoTien amount FROM dbo.THANHTOAN WHERE DonDatVeID=@ID ORDER BY ThanhToanID;",{ID:f.pendingOrder},r=>{assert.equal(r.length,2);assert.equal(r[0].status,'Thất bại');assert.equal(r[1].status,'Thành công');assert.equal(r[1].amount,1000.25);});
 });
 await check('CRITICAL-FOCUS-AFTER-ERROR',['KH-13'],'REAL_BROWSER_SQL',async()=>{
  await go('/movies/'+f.movie);await until("document.querySelector('section[aria-labelledby=movie-reviews] button[type=submit]')");await waitText('R82 eligible review');await pause(200);await evaluate("document.querySelector('section[aria-labelledby=movie-reviews] button[type=submit]').focus()");assert.ok(await evaluate("document.activeElement===document.querySelector('section[aria-labelledby=movie-reviews] button[type=submit]')"));await t.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',text:'\r',unmodifiedText:'\r',windowsVirtualKeyCode:13});await t.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await waitText('Bạn đã đánh giá phim này.');assert.ok(await evaluate("document.activeElement===document.querySelector('section[aria-labelledby=movie-reviews] [role=alert]')"));assert.ok(await evaluate("[...document.querySelectorAll('button')].every(n=>(n.getAttribute('aria-label')||n.innerText).trim())"));
 });
}
