// Whitelist of stored procedures the application may execute.
// Callers pass a key from PROCEDURES; a procedure name is never accepted from a request.
// Add an entry here only after the procedure exists under database/08_procedures/.
export const PROCEDURES = Object.freeze({
  SYSTEM_HEALTH_CHECK: 'dbo.sp_System_HealthCheck',
  EXPIRE_PENDING_ORDERS: 'dbo.sp_Order_ExpirePending',

  // Authentication: the database returns the bcrypt hash, the backend compares it.
  AUTH_LOGIN: 'dbo.sp_Auth_Login',
  AUTH_REGISTER_CUSTOMER: 'dbo.sp_Auth_RegisterCustomer',
  USER_GET_CURRENT: 'dbo.sp_User_GetCurrent',
  USER_UPDATE_PROFILE: 'dbo.sp_User_UpdateProfile',
  RBAC_GET_PERMISSIONS_BY_USER: 'dbo.sp_RBAC_GetPermissionsByUser',
  MANAGER_LIST_ASSIGNED_CINEMAS: 'dbo.sp_Manager_ListAssignedCinemas',
  MANAGER_ROOM_LIST: 'dbo.sp_Manager_Room_List',
  MANAGER_ROOM_CREATE: 'dbo.sp_Manager_Room_Create',
  MANAGER_ROOM_UPDATE: 'dbo.sp_Manager_Room_Update',
  MANAGER_ROOM_DELETE: 'dbo.sp_Manager_Room_Delete',
  MANAGER_SEAT_LIST_BY_ROOM: 'dbo.sp_Manager_Seat_ListByRoom',
  MANAGER_SEAT_CREATE: 'dbo.sp_Manager_Seat_Create',
  MANAGER_SEAT_UPDATE: 'dbo.sp_Manager_Seat_Update',
  MANAGER_SEAT_DELETE: 'dbo.sp_Manager_Seat_Delete',
  MANAGER_SHOWTIME_LIST: 'dbo.sp_Manager_Showtime_List',
  MANAGER_SHOWTIME_CREATE: 'dbo.sp_Manager_Showtime_Create',
  MANAGER_SHOWTIME_UPDATE: 'dbo.sp_Manager_Showtime_Update',
  MANAGER_SHOWTIME_CANCEL: 'dbo.sp_Manager_Showtime_Cancel',
  MANAGER_PRICING_LIST: 'dbo.sp_Manager_Pricing_List',
  MANAGER_PRICING_CREATE: 'dbo.sp_Manager_Pricing_Create',
  MANAGER_PRICING_UPDATE: 'dbo.sp_Manager_Pricing_Update',
  MANAGER_DASHBOARD: 'dbo.sp_Manager_Dashboard',
  MANAGER_REVENUE: 'dbo.sp_Manager_Revenue',
  ADMIN_USER_LIST: 'dbo.sp_Admin_User_List',
  ADMIN_USER_UPDATE_STATUS: 'dbo.sp_Admin_User_UpdateStatus',
  ADMIN_USER_CREATE: 'dbo.sp_Admin_User_Create',
  ADMIN_ROLE_LIST: 'dbo.sp_Admin_Role_List',
  ADMIN_ROLE_CREATE: 'dbo.sp_Admin_Role_Create',
  ADMIN_ROLE_UPDATE: 'dbo.sp_Admin_Role_Update',
  ADMIN_ROLE_DELETE: 'dbo.sp_Admin_Role_Delete',
  ADMIN_PERMISSION_LIST: 'dbo.sp_Admin_Permission_List',
  ADMIN_PERMISSION_CREATE: 'dbo.sp_Admin_Permission_Create',
  ADMIN_PERMISSION_UPDATE: 'dbo.sp_Admin_Permission_Update',
  ADMIN_PERMISSION_DELETE: 'dbo.sp_Admin_Permission_Delete',
  ADMIN_ROLE_PERMISSION_SET: 'dbo.sp_Admin_RolePermission_Set',
  ADMIN_ASSIGNMENT_LIST: 'dbo.sp_Admin_Assignment_List',
  ADMIN_ASSIGNMENT_CREATE: 'dbo.sp_Admin_Assignment_Create',
  ADMIN_CINEMA_LIST: 'dbo.usp_Admin_Cinema_List',
  ADMIN_CINEMA_CREATE: 'dbo.sp_Admin_Cinema_Create',
  ADMIN_CINEMA_UPDATE: 'dbo.sp_Admin_Cinema_Update',
  ADMIN_CINEMA_DELETE: 'dbo.sp_Admin_Cinema_Delete',
  ADMIN_CINEMA_IMAGE_LIST: 'dbo.usp_Admin_CinemaImage_List',
  ADMIN_CINEMA_IMAGE_CREATE: 'dbo.usp_Admin_CinemaImage_Create',
  ADMIN_CINEMA_IMAGE_UPDATE: 'dbo.usp_Admin_CinemaImage_Update',
  ADMIN_CINEMA_IMAGE_DELETE: 'dbo.usp_Admin_CinemaImage_Delete',
  ADMIN_CINEMA_IMAGE_SET_COVER: 'dbo.usp_Admin_CinemaImage_SetCover',
  ADMIN_MOVIE_LIST: 'dbo.usp_Admin_Movie_List',
  ADMIN_MOVIE_CREATE: 'dbo.sp_Admin_Movie_Create',
  ADMIN_MOVIE_UPDATE: 'dbo.sp_Admin_Movie_Update',
  ADMIN_MOVIE_DELETE: 'dbo.sp_Admin_Movie_Delete',
  ADMIN_MOVIE_ACTOR_SET: 'dbo.sp_Admin_MovieActor_Set',
  ADMIN_GENRE_LIST: 'dbo.sp_Genre_List',
  ADMIN_GENRE_CREATE: 'dbo.sp_Admin_Genre_Create',
  ADMIN_GENRE_UPDATE: 'dbo.sp_Admin_Genre_Update',
  ADMIN_GENRE_DELETE: 'dbo.sp_Admin_Genre_Delete',
  ADMIN_ACTOR_LIST: 'dbo.sp_Admin_Actor_List',
  ADMIN_ACTOR_CREATE: 'dbo.sp_Admin_Actor_Create',
  ADMIN_ACTOR_UPDATE: 'dbo.sp_Admin_Actor_Update',
  ADMIN_ACTOR_DELETE: 'dbo.sp_Admin_Actor_Delete',
  ADMIN_PRODUCT_LIST: 'dbo.usp_Admin_Product_List',
  ADMIN_PRODUCT_CREATE: 'dbo.sp_Admin_Product_Create',
  ADMIN_PRODUCT_UPDATE: 'dbo.sp_Admin_Product_Update',
  ADMIN_PRODUCT_DELETE: 'dbo.sp_Admin_Product_Delete',
  ADMIN_PROMOTION_LIST: 'dbo.sp_Admin_Promotion_List',
  ADMIN_PROMOTION_CREATE: 'dbo.sp_Admin_Promotion_Create',
  ADMIN_PROMOTION_UPDATE: 'dbo.sp_Admin_Promotion_Update',
  ADMIN_PROMOTION_DELETE: 'dbo.sp_Admin_Promotion_Delete',
  ADMIN_REPORT_REVENUE: 'dbo.sp_Admin_Report_Revenue',
  ADMIN_DASHBOARD: 'dbo.sp_Admin_Dashboard',
  ADMIN_ASSIGNMENT_UPDATE: 'dbo.usp_Admin_Assignment_Update',
  ADMIN_ROLE_PERMISSION_LIST: 'dbo.usp_Admin_RolePermission_List',
  ADMIN_ROOM_LIST: 'dbo.usp_Admin_Room_List',
  ADMIN_ROOM_CREATE: 'dbo.usp_Admin_Room_Create',
  ADMIN_ROOM_UPDATE: 'dbo.usp_Admin_Room_Update',
  ADMIN_ROOM_DELETE: 'dbo.usp_Admin_Room_Delete',
  ADMIN_SEAT_LIST: 'dbo.usp_Admin_Seat_List',
  ADMIN_SEAT_CREATE: 'dbo.usp_Admin_Seat_Create',
  ADMIN_SEAT_UPDATE: 'dbo.usp_Admin_Seat_Update',
  ADMIN_SEAT_DELETE: 'dbo.usp_Admin_Seat_Delete',
  ADMIN_PRICING_LIST: 'dbo.usp_Admin_Pricing_List',
  ADMIN_PRICING_CREATE: 'dbo.usp_Admin_Pricing_Create',
  ADMIN_PRICING_UPDATE: 'dbo.usp_Admin_Pricing_Update',
  ADMIN_SHOWTIME_LIST: 'dbo.usp_Admin_Showtime_List',
  ADMIN_SHOWTIME_CREATE: 'dbo.usp_Admin_Showtime_Create',
  ADMIN_SHOWTIME_UPDATE: 'dbo.usp_Admin_Showtime_Update',
  ADMIN_SHOWTIME_CANCEL: 'dbo.usp_Admin_Showtime_Cancel',
  SUPPORT_COMPLAINT_LIST: 'dbo.sp_Support_Complaint_List',
  SUPPORT_COMPLAINT_GET_DETAIL: 'dbo.sp_Support_Complaint_GetDetail',
  SUPPORT_COMPLAINT_GET_ORDER_REFERENCE: 'dbo.sp_Support_Complaint_GetOrderReference',
  SUPPORT_COMPLAINT_ADD_PROCESSING: 'dbo.sp_Support_Complaint_AddProcessing',
  SUPPORT_COMPLAINT_UPDATE_STATUS: 'dbo.sp_Support_Complaint_UpdateStatus',
  USER_GET_PASSWORD_HASH: 'dbo.sp_User_GetPasswordHash',
  USER_CHANGE_PASSWORD: 'dbo.sp_User_ChangePassword',

  // Public catalog: read procedures only.
  GENRE_LIST: 'dbo.sp_Genre_List',
  CINEMA_LIST: 'dbo.sp_Cinema_List',
  CINEMA_GET_IMAGES: 'dbo.sp_Cinema_GetImages',
  MOVIE_LIST: 'dbo.sp_Movie_List',
  MOVIE_GET_DETAIL: 'dbo.sp_Movie_GetDetail',
  SHOWTIME_LIST_BY_MOVIE: 'dbo.sp_Showtime_ListByMovie',
  SHOWTIME_GET_DETAIL: 'dbo.sp_Showtime_GetDetail',

  // Booking core. The database owns availability, pricing, promotion revalidation
  // and the booking transaction.
  SEAT_LIST_BY_SHOWTIME: 'dbo.sp_Seat_ListByShowtime',
  PRODUCT_LIST_ACTIVE: 'dbo.sp_Product_ListActive',
  PROMOTION_VALIDATE: 'dbo.sp_Promotion_Validate',
  BOOKING_CREATE: 'dbo.sp_Booking_Create',

  // Payment and order history. These procedures remain the source of truth for
  // order ownership, amount, payment state and state transitions.
  PAYMENT_CREATE_ATTEMPT: 'dbo.sp_Payment_CreateAttempt',
  PAYMENT_UPDATE_RESULT: 'dbo.sp_Payment_UpdateResult',
  ORDER_LIST_BY_CUSTOMER: 'dbo.sp_Order_ListByCustomer',
  ORDER_GET_DETAIL_BY_CUSTOMER: 'dbo.sp_Order_GetDetailByCustomer',

  // Phase 6 customer feedback. Identity is always passed by the service from
  // the authenticated JWT; these names are never supplied by a client.
  REVIEW_CREATE: 'dbo.sp_Review_Create',
  REVIEW_LIST_BY_MOVIE: 'dbo.sp_Review_ListByMovie',
  COMPLAINT_CREATE: 'dbo.sp_Complaint_Create',
  COMPLAINT_LIST_BY_CUSTOMER: 'dbo.sp_Complaint_ListByCustomer',
  COMPLAINT_GET_BY_CUSTOMER: 'dbo.sp_Complaint_GetByCustomer',

  BOOK_TICKET: 'dbo.sp_DatVe',
  ADD_SHOWTIME: 'dbo.sp_ThemSuatChieu',
  PROCESS_PAYMENT: 'dbo.sp_XuLyThanhToan',
  PROCESS_COMPLAINT: 'dbo.sp_XuLyKhieuNai',
  ASSIGN_CINEMA_MANAGER: 'dbo.sp_PhanCongQuanLyRap',
});

export const isKnownProcedure = (key) =>
  Object.prototype.hasOwnProperty.call(PROCEDURES, key);
