:on error exit
:r ./00_database/002_create_database.sql
:r ./00_database/003_database_options.sql
:r ./01_schema/001_create_schemas.sql
:r ./02_tables/banggia.sql
:r ./02_tables/chitietdoan.sql
:r ./02_tables/chitietve.sql
:r ./02_tables/danhgiaphim.sql
:r ./02_tables/dienvien.sql
:r ./02_tables/dondatve.sql
:r ./02_tables/ghe.sql
:r ./02_tables/hinhanh_rapchieuphim.sql
:r ./02_tables/hosokhachhang.sql
:r ./02_tables/khieunai.sql
:r ./02_tables/khuyenmai.sql
:r ./02_tables/nguoidung.sql
:r ./02_tables/phancong_rap.sql
:r ./02_tables/phim.sql
:r ./02_tables/phim_dienvien.sql
:r ./02_tables/phim_theloai.sql
:r ./02_tables/phongchieu.sql
:r ./02_tables/quyen.sql
:r ./02_tables/rapchieuphim.sql
:r ./02_tables/sanpham.sql
:r ./02_tables/suatchieu.sql
:r ./02_tables/thanhtoan.sql
:r ./02_tables/theloai.sql
:r ./02_tables/vaitro.sql
:r ./02_tables/vaitro_quyen.sql
:r ./02_tables/xuly_khieunai.sql
:r ./03_constraints/001_primary_unique.sql
:r ./03_constraints/002_foreign_keys.sql
:r ./03_constraints/003_check_constraints.sql
:r ./03_constraints/004_defaults.sql
:r ./02_tables/boithuong_huysuat.sql
:r ./04_indexes/banggia.sql
:r ./04_indexes/chitietve.sql
:r ./04_indexes/dondatve.sql
:r ./04_indexes/ghe.sql
:r ./04_indexes/hinhanh_rapchieuphim.sql
:r ./04_indexes/khieunai.sql
:r ./04_indexes/nguoidung.sql
:r ./04_indexes/phancong_rap.sql
:r ./04_indexes/phim.sql
:r ./04_indexes/phongchieu.sql
:r ./04_indexes/suatchieu.sql
:r ./04_indexes/thanhtoan.sql
:r ./04_indexes/xuly_khieunai.sql
:r ./05_functions/fn_BayGio.sql
:r ./05_functions/fn_TinhBoiThuongVe.sql
:r ./05_functions/fn_DonDangGiuGhe.sql
:r ./05_functions/fn_GheCoVeHieuLucSuatTuongLai.sql
:r ./05_functions/fn_GioiHanDonDangGiu.sql
:r ./05_functions/fn_GioiHanGheMoiDon.sql
:r ./05_functions/fn_GioiHanGiamGiaPhanTram.sql
:r ./05_functions/fn_GioiHanSoLuongSanPham.sql
:r ./05_functions/fn_GioRap.sql
:r ./05_functions/fn_UtcTuGioRap.sql
:r ./05_functions/fn_NgayKinhDoanh.sql
:r ./05_functions/fn_HomNay.sql
:r ./05_functions/fn_KiemTraQuanLyRapScope.sql
:r ./05_functions/fn_KiemTraQuyenNguoiDung.sql
:r ./05_functions/fn_TinhGiaVe.sql
:r ./05_functions/fn_TinhTongTienDoAn.sql
:r ./05_functions/fn_TinhTongTienDon.sql
:r ./05_functions/fn_TinhTongTienVe.sql
:r ./05_functions/fn_ThoiGianGiaHanThanhToanPhut.sql
:r ./05_functions/fn_ThoiGianGiuChoPhut.sql
:r ./03_constraints/005_function_defaults.sql
:r ./06_views/vw_ChiTietDonDatVe.sql
:r ./06_views/vw_DanhSachKhieuNai.sql
:r ./06_views/vw_DoanhThuTheoRap.sql
:r ./06_views/vw_LichChieuChiTiet.sql
:r ./05_functions/fn_DanhSachGheSuatChieu.sql
:r ./06_views/vw_LichSuDatVe.sql
:r ./06_views/vw_ThongKePhim.sql
:r ./07_triggers/TRG_BangGia_KiemTraChongLan.sql
:r ./07_triggers/TRG_ChiTietVe_KiemTraGheDungPhong.sql
:r ./07_triggers/TRG_ChiTietVe_KiemTraTrungGhe.sql
:r ./07_triggers/TRG_DanhGia_KiemTraDaXemPhim.sql
:r ./07_triggers/TRG_SuatChieu_KiemTraTrungLich.sql
:r ./07_triggers/TRG_XuLyKhieuNai_CapNhatTrangThaiKhieuNai.sql
:r ./07_triggers/TRG_XuLyKhieuNai_KiemTraVaiTro.sql
:r ./08_procedures/admin/sp_Admin_Actor_Create.sql
:r ./08_procedures/admin/sp_Admin_Actor_Delete.sql
:r ./08_procedures/admin/sp_Admin_Actor_List.sql
:r ./08_procedures/admin/sp_Admin_Actor_Update.sql
:r ./08_procedures/admin/sp_Admin_Assignment_Create.sql
:r ./08_procedures/admin/sp_Admin_Assignment_List.sql
:r ./08_procedures/admin/sp_Admin_Cinema_Create.sql
:r ./08_procedures/admin/sp_Admin_Cinema_Delete.sql
:r ./08_procedures/admin/sp_Admin_Cinema_Update.sql
:r ./08_procedures/admin/sp_Admin_Dashboard.sql
:r ./08_procedures/admin/sp_Admin_Genre_Create.sql
:r ./08_procedures/admin/sp_Admin_Genre_Delete.sql
:r ./08_procedures/admin/sp_Admin_Genre_Update.sql
:r ./08_procedures/admin/sp_Admin_Movie_Create.sql
:r ./08_procedures/admin/sp_Admin_Movie_Delete.sql
:r ./08_procedures/admin/sp_Admin_Movie_Update.sql
:r ./08_procedures/admin/sp_Admin_MovieActor_Set.sql
:r ./08_procedures/admin/sp_Admin_Permission_Create.sql
:r ./08_procedures/admin/sp_Admin_Permission_Delete.sql
:r ./08_procedures/admin/sp_Admin_Permission_List.sql
:r ./08_procedures/admin/sp_Admin_Permission_Update.sql
:r ./08_procedures/admin/sp_Admin_Product_Create.sql
:r ./08_procedures/admin/sp_Admin_Product_Delete.sql
:r ./08_procedures/admin/sp_Admin_Product_Update.sql
:r ./08_procedures/admin/sp_Admin_Promotion_Create.sql
:r ./08_procedures/admin/sp_Admin_Promotion_Delete.sql
:r ./08_procedures/admin/sp_Admin_Promotion_List.sql
:r ./08_procedures/admin/sp_Admin_Promotion_Update.sql
:r ./08_procedures/admin/sp_Admin_Report_Revenue.sql
:r ./08_procedures/admin/sp_Admin_Role_Create.sql
:r ./08_procedures/admin/sp_Admin_Role_Delete.sql
:r ./08_procedures/admin/sp_Admin_Role_List.sql
:r ./08_procedures/admin/sp_Admin_Role_Update.sql
:r ./08_procedures/admin/sp_Admin_RolePermission_Set.sql
:r ./08_procedures/admin/sp_Admin_User_Create.sql
:r ./08_procedures/admin/sp_Admin_User_List.sql
:r ./08_procedures/admin/sp_Admin_User_UpdateStatus.sql
:r ./08_procedures/auth/sp_Auth_Login.sql
:r ./08_procedures/auth/sp_Auth_RegisterCustomer.sql
:r ./08_procedures/booking/sp_Booking_Create.sql
:r ./08_procedures/public/sp_Cinema_GetImages.sql
:r ./08_procedures/public/sp_Cinema_List.sql
:r ./08_procedures/system/sp_Clock_GetNow.sql
:r ./08_procedures/customer/sp_Complaint_Create.sql
:r ./08_procedures/customer/sp_Complaint_GetByCustomer.sql
:r ./08_procedures/customer/sp_Complaint_ListByCustomer.sql
:r ./08_procedures/booking/sp_DatVe.sql
:r ./08_procedures/public/sp_Genre_List.sql
:r ./08_procedures/manager/sp_Manager_Dashboard.sql
:r ./08_procedures/manager/sp_Manager_ListAssignedCinemas.sql
:r ./08_procedures/manager/sp_Manager_Pricing_Create.sql
:r ./08_procedures/manager/sp_Manager_Pricing_List.sql
:r ./08_procedures/manager/sp_Manager_Pricing_Update.sql
:r ./08_procedures/manager/sp_Manager_Revenue.sql
:r ./08_procedures/manager/sp_Manager_Room_Create.sql
:r ./08_procedures/manager/sp_Manager_Room_Delete.sql
:r ./08_procedures/manager/sp_Manager_Room_List.sql
:r ./08_procedures/manager/sp_Manager_Room_Update.sql
:r ./08_procedures/manager/sp_Manager_Seat_BatchCreate.sql
:r ./08_procedures/manager/sp_Manager_Seat_Create.sql
:r ./08_procedures/manager/sp_Manager_Seat_Delete.sql
:r ./08_procedures/manager/sp_Manager_Seat_ListByRoom.sql
:r ./08_procedures/manager/sp_Manager_Seat_Update.sql
:r ./08_procedures/manager/sp_Manager_Showtime_Cancel.sql
:r ./08_procedures/manager/sp_Manager_Showtime_Create.sql
:r ./08_procedures/manager/sp_Manager_Showtime_List.sql
:r ./08_procedures/manager/sp_Manager_Showtime_Update.sql
:r ./08_procedures/public/sp_Movie_GetDetail.sql
:r ./08_procedures/public/sp_Movie_List.sql
:r ./08_procedures/customer/sp_Order_Cancel.sql
:r ./08_procedures/customer/sp_Order_ExpirePending.sql
:r ./08_procedures/customer/sp_Order_GetDetailByCustomer.sql
:r ./08_procedures/customer/sp_Order_ListByCustomer.sql
:r ./08_procedures/payment/sp_Payment_CreateAttempt.sql
:r ./08_procedures/payment/sp_Payment_UpdateResult.sql
:r ./08_procedures/public/sp_Product_ListActive.sql
:r ./08_procedures/public/sp_Promotion_Validate.sql
:r ./08_procedures/system/sp_PhanCongQuanLyRap.sql
:r ./08_procedures/auth/sp_RBAC_GetPermissionsByUser.sql
:r ./08_procedures/customer/sp_Review_Create.sql
:r ./08_procedures/customer/sp_Review_ListByMovie.sql
:r ./08_procedures/public/sp_Seat_ListByShowtime.sql
:r ./08_procedures/system/sp_Showtime_CancelCascade.sql
:r ./08_procedures/public/sp_Showtime_GetDetail.sql
:r ./08_procedures/public/sp_Showtime_ListByMovie.sql
:r ./08_procedures/system/sp_Showtime_ValidateTimes.sql
:r ./08_procedures/support/sp_Support_Complaint_AddProcessing.sql
:r ./08_procedures/support/sp_Support_Complaint_GetDetail.sql
:r ./08_procedures/support/sp_Support_Complaint_GetOrderReference.sql
:r ./08_procedures/support/sp_Support_Complaint_List.sql
:r ./08_procedures/support/sp_Support_Complaint_UpdateStatus.sql
:r ./08_procedures/system/sp_System_HealthCheck.sql
:r ./08_procedures/system/sp_ThemSuatChieu.sql
:r ./08_procedures/auth/sp_User_ChangePassword.sql
:r ./08_procedures/auth/sp_User_GetCurrent.sql
:r ./08_procedures/auth/sp_User_GetPasswordHash.sql
:r ./08_procedures/auth/sp_User_UpdateProfile.sql
:r ./08_procedures/support/sp_XuLyKhieuNai.sql
:r ./08_procedures/payment/sp_XuLyThanhToan.sql
:r ./08_procedures/admin/usp_Admin_Assignment_Update.sql
:r ./08_procedures/admin/usp_Admin_Cinema_List.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_Create.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_Delete.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_List.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_SetCover.sql
:r ./08_procedures/admin/usp_Admin_CinemaImage_Update.sql
:r ./08_procedures/admin/usp_Admin_Movie_List.sql
:r ./08_procedures/admin/usp_Admin_Pricing_Create.sql
:r ./08_procedures/admin/usp_Admin_Pricing_List.sql
:r ./08_procedures/admin/usp_Admin_Pricing_Update.sql
:r ./08_procedures/admin/usp_Admin_Product_List.sql
:r ./08_procedures/admin/usp_Admin_RolePermission_List.sql
:r ./08_procedures/admin/usp_Admin_Room_Create.sql
:r ./08_procedures/admin/usp_Admin_Room_Delete.sql
:r ./08_procedures/admin/usp_Admin_Room_List.sql
:r ./08_procedures/admin/usp_Admin_Room_Update.sql
:r ./08_procedures/admin/usp_Admin_Seat_Create.sql
:r ./08_procedures/admin/usp_Admin_Seat_Delete.sql
:r ./08_procedures/admin/usp_Admin_Seat_List.sql
:r ./08_procedures/admin/usp_Admin_Seat_Update.sql
:r ./08_procedures/admin/usp_Admin_Showtime_Cancel.sql
:r ./08_procedures/admin/usp_Admin_Showtime_Create.sql
:r ./08_procedures/admin/usp_Admin_Showtime_List.sql
:r ./08_procedures/admin/usp_Admin_Showtime_Update.sql
:r ./09_security/001_execute_role.sql

:r ./08_procedures/admin/sp_Admin_Genre_List.sql
