// Audit tooling only. Production source is read; all writes use one disposable SQL fixture.
import os from 'node:os';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {preview} from '../../frontend/node_modules/vite/dist/node/index.js';
import {credentials,walk} from '../db/lib.mjs';
import {root,connect,ask,mainSnapshot,productionHashes,sha} from '../r3a/common.mjs';
const out=path.join(root,'audit/uiux'),evidence=path.join(out,'evidence'),database='CinemaBookingDB_R0_UIUXAudit';
const save=(name,data)=>{const file=path.join(out,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,typeof data==='string'?data:JSON.stringify(data,null,2)+'\n');};
const initialSources=productionHashes(),oldEvidence=Object.fromEntries(walk(path.join(root,'audit/final/r8')).map(f=>[f,sha(fs.readFileSync(f))]));
const main=await connect('CinemaBookingDB'),mainBefore=await mainSnapshot(main);await main.close();
const sourceFiles=walk(path.join(root,'frontend/src')).map(file=>({file:path.relative(root,file).replaceAll('\\','/'),lines:fs.readFileSync(file,'utf8').split('\n').length,bytes:fs.statSync(file).size}));
const lock=JSON.parse(fs.readFileSync(path.join(root,'frontend/package-lock.json'),'utf8'));
const versions=Object.fromEntries(Object.entries(lock.packages).filter(([key])=>/^node_modules\/(react|react-dom|react-router-dom|vite|oxlint|@js-temporal\/polyfill)$/.test(key)).map(([k,v])=>[k.slice(13),v.version]));
save('FRONTEND_INVENTORY.json',{versions,sourceFiles,componentFiles:sourceFiles.filter(f=>f.file.includes('/components/')),pageFiles:sourceFiles.filter(f=>f.file.includes('/pages/')),cssFiles:sourceFiles.filter(f=>f.file.endsWith('.css')),assets:walk(path.join(root,'frontend/public')).map(f=>path.relative(root,f).replaceAll('\\','/')),hasPlaywrightOrAxe:Object.keys(lock.packages).some(k=>/playwright|axe-core/.test(k)),sourceHashes:initialSources,initialMainSnapshot:mainBefore});
assert.notEqual(database,'CinemaBookingDB');const reset=spawnSync(process.execPath,['scripts/db/run.mjs','reset',`--database=${database}`],{cwd:root,encoding:'utf8',windowsHide:true,timeout:180000});save('evidence/fixture-reset.txt',reset.stdout+reset.stderr);assert.equal(reset.status,0,'Disposable reset');
Object.assign(process.env,credentials(),{DB_DATABASE:database});
const {createApp}=await import('../../backend/src/app.js'),{closePool}=await import('../../backend/src/db/pool.js');
const server=createApp().listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const backend=`http://127.0.0.1:${server.address().port}`,tokens={};
const pool=await connect(database);let site,child,ws;const metrics=[],requests=[],errors=[],checks=[];
async function api(route,actor='customer',method='GET',body){const res=await fetch(backend+'/api'+route,{method,headers:{'Content-Type':'application/json',...(tokens[actor]?{Authorization:'Bearer '+tokens[actor]}:{})},body:body?JSON.stringify(body):undefined});const data=await res.json();assert.ok(res.ok,route+' '+res.status+' '+data.error?.code);return data;}
let next=0;const pending=new Map();
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++next;const timer=setTimeout(()=>{pending.delete(id);reject(Error(method+' timeout'));},20000);pending.set(id,{resolve:r=>{clearTimeout(timer);resolve(r);},reject:e=>{clearTimeout(timer);reject(e);}});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.text);return result.result.value;};
const wait=async expression=>{const deadline=Date.now()+15000;while(!await evaluate(expression)){assert.ok(Date.now()<deadline,expression);await new Promise(r=>setTimeout(r,40));}};
let origin;
const go=async route=>{await send('Page.navigate',{url:origin+route});await wait('document.readyState==="complete"&&location.origin==='+JSON.stringify(origin));await new Promise(r=>setTimeout(r,200));};
const switchActor=async actor=>{await go('/login');await evaluate(`sessionStorage.clear();${tokens[actor]?`sessionStorage.setItem('cinema_access_token',${JSON.stringify(tokens[actor])});`:''}`);await send('Page.navigate',{url:'about:blank'});await wait("location.href==='about:blank'");};
const domMetrics=`(()=>{const vw=innerWidth,visible=e=>!!(e.offsetWidth||e.offsetHeight||e.getClientRects().length),label=e=>e.getAttribute('aria-label')||e.labels?.[0]?.textContent.trim()||e.getAttribute('title')||'';const interactive=[...document.querySelectorAll('button,a,input,select,textarea')].filter(visible);return{path:location.pathname,width:vw,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,headings:[...document.querySelectorAll('h1,h2,h3')].map(e=>({level:e.tagName,text:e.textContent.trim().slice(0,90)})),forms:[...document.forms].map(f=>({name:f.getAttribute('aria-label'),controls:f.querySelectorAll('input,select,textarea').length,busyDisabled:f.querySelectorAll(':disabled').length})),unlabelledInputs:interactive.filter(e=>['INPUT','SELECT','TEXTAREA'].includes(e.tagName)&&e.type!=='hidden'&&!label(e)).map(e=>({tag:e.tagName,type:e.type})),smallTargets:interactive.filter(e=>['BUTTON','A'].includes(e.tagName)&&Math.min(e.getBoundingClientRect().width,e.getBoundingClientRect().height)<24).map(e=>({tag:e.tagName,text:e.textContent.trim().slice(0,50),width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})),overflowElements:[...document.querySelectorAll('main *')].filter(visible).filter(e=>{const r=e.getBoundingClientRect();return r.right>vw+1||r.left<-1;}).slice(0,18).map(e=>({tag:e.tagName,class:e.className,text:e.textContent.trim().slice(0,65),right:Math.round(e.getBoundingClientRect().right)})),tables:[...document.querySelectorAll('table')].map(t=>({columns:t.querySelectorAll('thead th').length,width:t.getBoundingClientRect().width,wrapperClient:t.parentElement.clientWidth,wrapperScroll:t.parentElement.scrollWidth,headers:[...t.querySelectorAll('th')].map(e=>e.textContent)})),images:[...document.images].map(e=>({alt:e.getAttribute('alt'),loaded:e.complete&&e.naturalWidth>0})),alerts:[...document.querySelectorAll('[role=alert],[role=status]')].map(e=>e.textContent.trim().slice(0,120)),buttonStyles:[...document.querySelectorAll('button')].filter(visible).slice(0,8).map(e=>{const c=getComputedStyle(e);return{text:e.textContent.trim().slice(0,30),height:e.getBoundingClientRect().height,font:c.fontFamily,size:c.fontSize,background:c.backgroundColor,radius:c.borderRadius};}),errorAssociations:[...document.querySelectorAll('input,select,textarea')].filter(visible).map(e=>({label:label(e),describedby:e.getAttribute('aria-describedby'),invalid:e.getAttribute('aria-invalid'),required:e.required})),landmarks:{main:document.querySelectorAll('main').length,nav:document.querySelectorAll('nav').length,skip:!!document.querySelector('a[href="#main"],a[href="#main-content"]')},bodyFont:{family:getComputedStyle(document.body).fontFamily,size:getComputedStyle(document.body).fontSize,lineHeight:getComputedStyle(document.body).lineHeight}}})()`;
const widths=[360,390,768,1024,1280,1440];
async function capture(key,route,actor,action){
 await switchActor(actor);await go(route);if(action)await action();
 await wait("![...document.querySelectorAll('[role=status]')].some(e=>e.textContent.startsWith('Đang tải'))");
 for(const width of widths){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});await new Promise(r=>setTimeout(r,80));const metric=await evaluate(domMetrics);metrics.push({screen:key,actor,...metric});
  if([390,1440].includes(width)){await send('Runtime.evaluate',{expression:'window.scrollTo(0,0)'});const screenshot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,fromSurface:true});const target=path.join(evidence,'screenshots',`${key}-${width}.png`);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,Buffer.from(screenshot.data,'base64'));}
 }
 const ax=await send('Accessibility.getFullAXTree');save(`evidence/ax/${key}.json`,{nodes:ax.nodes.filter(n=>!n.ignored).map(n=>({role:n.role?.value,name:n.name?.value,properties:n.properties?.filter(p=>['disabled','required','invalid','level'].includes(p.name))}))});
 save('evidence/browser-metrics.json',{status:'RUNNING',widths,metrics,requests,errors,checks});console.log('CAPTURE '+key);
}
try{
 for(const[actor,email]of [['customer','khachhang1@gmail.com'],['manager','manager.q1@cinemadb.vn'],['support','cskh@cinemadb.vn'],['admin','admin@cinemadb.vn']])tokens[actor]=(await api('/auth/login',null,'POST',{Email:email,MatKhau:'123456'})).token;
 const show=(await ask(pool,"SELECT TOP(1) SuatChieuID AS id,PhimID AS movie,RapID AS cinema FROM dbo.SUATCHIEU s JOIN dbo.PHONGCHIEU p ON p.PhongID=s.PhongID WHERE s.ThoiGianBatDau>dbo.fn_BayGio() AND s.TrangThai=N'Mở bán' ORDER BY s.ThoiGianBatDau DESC")).recordset[0];assert.ok(show);
 const seats=(await api(`/showtimes/${show.id}/seats`,null)).seats.filter(s=>s.status==='Trống');assert.ok(seats.length>=2);
 const order=(await api('/bookings','customer','POST',{showtimeId:show.id,seatIds:[seats[0].id],products:[{productId:1,quantity:1}]})).booking.id;
 const pay=(await api(`/orders/${order}/payments`,'customer','POST',{paymentMethod:'MOMO'})).payment.id;await api(`/orders/${order}/payments/${pay}/result`,'customer','POST',{status:'Thành công'});
 const hold=(await api('/bookings','customer','POST',{showtimeId:show.id,seatIds:[seats[1].id],products:[]})).booking.id;
 const complaint=(await api('/complaints','customer','POST',{type:'UIUX audit',title:'Audit giao diện: đơn vé',content:'Nội dung fixture phục vụ kiểm tra đọc giao diện.',orderId:order})).complaint.id;
 save('evidence/fixture-context.json',{database,showtime:show.id,movie:show.movie,cinema:show.cinema,paidOrder:order,heldOrder:hold,complaint,note:'Seed identities and synthetic audit transactions only. No writes to main.'});
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'cinema-uiux-'));
 site=await preview({root:path.join(root,'frontend'),configFile:false,preview:{host:'127.0.0.1',port:0,proxy:{'/api':{target:backend,changeOrigin:true}}}});origin=`http://127.0.0.1:${site.httpServer.address().port}`;
 child=spawn(process.env.R3B_CHROME_PATH??'C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
 const portFile=path.join(profile,'DevToolsActivePort'),deadline=Date.now()+15000;while(!fs.existsSync(portFile)){assert.ok(Date.now()<deadline);await new Promise(r=>setTimeout(r,50));}
 const port=Number(fs.readFileSync(portFile,'utf8').split('\n')[0]),target=await(await fetch(`http://127.0.0.1:${port}/json/new?about:blank`,{method:'PUT'})).json();ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 ws.onmessage=event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p?.reject(Error(m.error.message)):p?.resolve(m.result);}else if(m.method==='Network.responseReceived'){const r=m.params.response;if(r.url.startsWith(origin+'/api/'))requests.push({path:r.url.slice(origin.length),status:r.status});}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);};
 for(const method of ['Page.enable','Runtime.enable','Network.enable','Accessibility.enable'])await send(method);
 const screens=[['home','/',null],['movies','/movies',null],['movie-detail',`/movies/${show.movie}`,'customer'],['cinemas','/cinemas',null],['cinema-detail',`/cinemas/${show.cinema}`,null],['booking',`/booking/${show.id}`,'customer'],['login','/login',null],['register','/register',null],['forbidden','/forbidden',null],['profile','/profile','customer'],['orders','/orders','customer'],['order-detail',`/orders/${order}`,'customer'],['payment',`/orders/${hold}/payment`,'customer'],['complaints','/complaints','customer'],['complaint-detail',`/complaints/${complaint}`,'customer'],['manager','/manager','manager'],['support','/support','support'],['account','/account','customer'],['admin','/admin','admin'],['not-found','/uiux-nonexistent',null]];
 for(const[key,route,actor]of screens)await capture(key,route,actor);
 await capture('support-detail','/support','support',async()=>{await wait("document.querySelector('.catalog-list button')!==null");await evaluate("document.querySelector('.catalog-list button').click()");await wait("document.querySelector('[aria-label=\"Chi tiết đơn tham chiếu\"]')!==null");});
 for(const[label,key]of [['Tài khoản','users'],['Vai trò','roles'],['Quyền','permissions'],['Phân công','assignments'],['Rạp','cinemas'],['Ảnh rạp','images'],['Phòng','rooms'],['Ghế','seats'],['Phim','movies'],['Thể loại','genres'],['Diễn viên','actors'],['Sản phẩm','products'],['Khuyến mãi','promotions'],['Bảng giá','pricing'],['Suất chiếu','showtimes'],['Khiếu nại','complaints'],['Doanh thu','revenue']])await capture('admin-'+key,'/admin','admin',async()=>{await wait("document.querySelector('nav[aria-label=\"Phân hệ quản trị\"]')!==null");await evaluate(`(()=>{const n=[...document.querySelectorAll('nav[aria-label="Phân hệ quản trị"] button')].find(n=>n.textContent===${JSON.stringify(label)});n.click();})()`);await new Promise(r=>setTimeout(r,220));if(key==='images'){await evaluate("(()=>{const s=document.querySelector('select[aria-label=\"Chọn rạp\"]');const set=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set;set.call(s,s.options[1].value);s.dispatchEvent(new Event('change',{bubbles:true}));})()");await new Promise(r=>setTimeout(r,180));}});
 await capture('manager-seats','/manager','manager',async()=>{await wait("[...document.querySelectorAll('button')].some(n=>n.textContent==='Ghế')");await evaluate("[...document.querySelectorAll('button')].find(n=>n.textContent==='Ghế').click()");await wait("document.querySelector('[aria-label=\"Ghế\"]')!==null");});
 await capture('admin-user-edit','/admin','admin',async()=>{await wait("document.querySelector('nav[aria-label=\"Phân hệ quản trị\"]')!==null");await evaluate("[...document.querySelectorAll('nav[aria-label=\"Phân hệ quản trị\"] button')].find(e=>e.textContent==='Tài khoản').click()");await wait("document.querySelector('tbody button')!==null");await evaluate("document.querySelector('tbody button').click()");});
 await capture('admin-movie-edit','/admin','admin',async()=>{await wait("document.querySelector('nav[aria-label=\"Phân hệ quản trị\"]')!==null");await evaluate("[...document.querySelectorAll('nav[aria-label=\"Phân hệ quản trị\"] button')].find(e=>e.textContent==='Phim').click()");await wait("document.querySelector('tbody button')!==null");await evaluate("document.querySelector('tbody button').click()");});
 for(const [key,button]of [['manager-pricing-edit','Sửa giá'],['manager-showtime-edit','Sửa suất']])await capture(key,'/manager','manager',async()=>{await wait("[...document.querySelectorAll('button')].some(e=>e.textContent==='"+button+"')");await evaluate("[...document.querySelectorAll('button')].find(e=>e.textContent==='"+button+"').click()");});
 await capture('movies-empty','/movies',null,async()=>{await wait("document.querySelector('input[type=search]')!==null");await evaluate("(()=>{const n=document.querySelector('input[type=search]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(n,'uiux-no-match-unique');n.dispatchEvent(new Event('input',{bubbles:true}));})()");await wait("document.body.innerText.includes('Không tìm thấy phim phù hợp.')");});
 // Keyboard/focus audit of the actual production page, without application changes.
 await switchActor(null);await go('/login');await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});
 checks.push({name:'First Tab focus',observed:await evaluate("(()=>{const e=document.activeElement,c=getComputedStyle(e);return{tag:e.tagName,text:e.textContent,outline:c.outlineStyle,width:c.outlineWidth};})()")});
 const a11yCSS=await evaluate("[...document.styleSheets].flatMap(s=>{try{return [...s.cssRules].map(r=>r.cssText);}catch{return[];}}).filter(r=>r.includes(':focus')||r.includes(':hover'))");checks.push({name:'Authored focus/hover styles',rules:a11yCSS});
 // Real 401 UX; invalid fixture credentials produce no business write.
 await evaluate(`(async()=>{for(const[type,value]of [['email','nobody-uiux@example.invalid'],['password','invalid-uiux-input']]){const n=document.querySelector('input[type='+type+']');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(n,value);n.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));}document.querySelector('form button').click();})()`);await wait("document.querySelector('[role=alert]')!==null");checks.push({name:'Real invalid login 401 recovery',alert:await evaluate("document.querySelector('[role=alert]').textContent"),fieldAssociations:await evaluate("[...document.querySelectorAll('input')].map(e=>({type:e.type,invalid:e.getAttribute('aria-invalid'),describedby:e.getAttribute('aria-describedby')}))")});
 save('evidence/browser-metrics.json',{status:'PASS',productionBuild:true,isolatedRealBackendSQL:true,widths,capturedViews:new Set(metrics.map(m=>m.screen)).size,routeScreens:20,metrics,requests,errors,checks});
 console.log('PASS browser capture '+metrics.length+' measurements; '+errors.length+' runtime exceptions.');
}catch(error){save('evidence/browser-error.json',{error:error.message});throw error;}
finally{
 ws?.close();child?.kill();if(site)await site.close();await new Promise(resolve=>server.close(resolve));await closePool();await pool.close();
 const verifyMain=await connect('CinemaBookingDB');try{assert.deepEqual(await mainSnapshot(verifyMain),mainBefore);}finally{await verifyMain.close();}
 assert.deepEqual(productionHashes(),initialSources);for(const[f,hash]of Object.entries(oldEvidence))assert.equal(sha(fs.readFileSync(f)),hash,'R8 evidence changed');
 const master=await connect('master');try{assert.equal(database,'CinemaBookingDB_R0_UIUXAudit');await ask(master,`ALTER DATABASE [${database}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [${database}];`);save('evidence/preservation-cleanup.json',{status:'PASS',mainUnchanged:true,productionSourcesUnchanged:true,r8EvidenceUnchanged:true,removed:[database],at:new Date().toISOString()});}finally{await master.close();}
 const auditDir=path.resolve(root,'database/_audit');for(const prefix of ['verify','backend-smoke','concurrency']){const file=path.resolve(auditDir,`${prefix}-${database}.json`);assert.equal(path.dirname(file),auditDir);if(fs.existsSync(file))fs.unlinkSync(file);}
}
