-- No account/password/contact data is exported. JSON retains datetime2(7) precision.
SELECT (SELECT * FROM dbo.DONDATVE ORDER BY DonDatVeID FOR JSON PATH,INCLUDE_NULL_VALUES) orders,
(SELECT * FROM dbo.CHITIETVE ORDER BY VeID FOR JSON PATH,INCLUDE_NULL_VALUES) tickets,
(SELECT * FROM dbo.CHITIETDOAN ORDER BY ChiTietDoAnID FOR JSON PATH,INCLUDE_NULL_VALUES) foods,
(SELECT * FROM dbo.THANHTOAN ORDER BY ThanhToanID FOR JSON PATH,INCLUDE_NULL_VALUES) payments,
(SELECT KhuyenMaiID,MaCode,SoLuong,SoLuongDaDung,TrangThai FROM dbo.KHUYENMAI ORDER BY KhuyenMaiID FOR JSON PATH,INCLUDE_NULL_VALUES) promotions,
(SELECT NguoiDungID,DiemTichLuy FROM dbo.HOSOKHACHHANG ORDER BY NguoiDungID FOR JSON PATH,INCLUDE_NULL_VALUES) points;
