import { Router } from 'express';
import * as admin from '../controllers/adminController.js';
import { authenticate } from '../middleware/authenticate.js';
import { requireAdmin } from '../middleware/requireAdmin.js';
import { requirePermission } from '../middleware/requirePermission.js';
import * as validators from '../validators/supportValidator.js';
import { supportService } from '../services/supportService.js';

const router = Router();
router.use(authenticate, requireAdmin);
router.get('/dashboard', requirePermission('XEM_BAO_CAO_TOANHE'), admin.dashboard);
router.get('/users', requirePermission('QL_NGUOIDUNG'), admin.users);
router.post('/users', requirePermission('QL_NGUOIDUNG'), admin.createUser);
router.put('/users/:userId/status', requirePermission('QL_NGUOIDUNG'), admin.updateUserStatus);
router.get('/roles', requirePermission('QL_VAITRO'), admin.roles);
router.get('/roles/:roleId/permissions', requirePermission('QL_QUYEN'), admin.rolePermissions);
router.post('/roles', requirePermission('QL_VAITRO'), admin.createRole);
router.put('/roles/:roleId', requirePermission('QL_VAITRO'), admin.updateRole);
router.delete('/roles/:roleId', requirePermission('QL_VAITRO'), admin.deleteRole);
router.get('/permissions', requirePermission('QL_QUYEN'), admin.permissions);
router.post('/permissions', requirePermission('QL_QUYEN'), admin.createPermission);
router.put('/permissions/:permissionId', requirePermission('QL_QUYEN'), admin.updatePermission);
router.delete('/permissions/:permissionId', requirePermission('QL_QUYEN'), admin.deletePermission);
router.put('/roles/:roleId/permissions', requirePermission('QL_QUYEN'), admin.setRolePermissions);
router.get('/assignments', requirePermission('PHANCONG_RAP'), admin.assignments);
router.post('/assignments', requirePermission('PHANCONG_RAP'), admin.createAssignment);
router.put('/assignments/:assignmentId', requirePermission('PHANCONG_RAP'), admin.updateAssignment);
router.get('/cinemas', requirePermission('QL_RAP'), admin.cinemas);
router.post('/cinemas', requirePermission('QL_RAP'), admin.createCinema);
router.put('/cinemas/:cinemaId', requirePermission('QL_RAP'), admin.updateCinema);
router.delete('/cinemas/:cinemaId', requirePermission('QL_RAP'), admin.deleteCinema);
router.get('/cinemas/:cinemaId/images', requirePermission('QL_RAP'), admin.cinemaImages);
router.post('/cinemas/:cinemaId/images', requirePermission('QL_RAP'), admin.createCinemaImage);
router.put('/cinemas/:cinemaId/images/:imageId', requirePermission('QL_RAP'), admin.updateCinemaImage);
router.delete('/cinemas/:cinemaId/images/:imageId', requirePermission('QL_RAP'), admin.deleteCinemaImage);
router.patch('/cinemas/:cinemaId/images/:imageId/cover', requirePermission('QL_RAP'), admin.setCinemaImageCover);
router.get('/rooms', requirePermission('QL_PHONG'), admin.rooms);
router.post('/rooms', requirePermission('QL_PHONG'), admin.createRoom);
router.put('/rooms/:roomId', requirePermission('QL_PHONG'), admin.updateRoom);
router.delete('/rooms/:roomId', requirePermission('QL_PHONG'), admin.deleteRoom);
router.get('/seats', requirePermission('QL_GHE'), admin.seats);
router.post('/seats', requirePermission('QL_GHE'), admin.createSeat);
router.put('/seats/:seatId', requirePermission('QL_GHE'), admin.updateSeat);
router.delete('/seats/:seatId', requirePermission('QL_GHE'), admin.deleteSeat);
router.get('/pricing', requirePermission('QL_BANG_GIA'), admin.pricing);
router.post('/pricing', requirePermission('QL_BANG_GIA'), admin.createPricing);
router.put('/pricing/:pricingId', requirePermission('QL_BANG_GIA'), admin.updatePricing);
router.get('/showtimes', requirePermission('QL_SUAT_CHIEU'), admin.showtimes);
router.post('/showtimes', requirePermission('QL_SUAT_CHIEU'), admin.createShowtime);
router.put('/showtimes/:showtimeId', requirePermission('QL_SUAT_CHIEU'), admin.updateShowtime);
router.post('/showtimes/:showtimeId/cancel', requirePermission('QL_SUAT_CHIEU'), admin.cancelShowtime);
router.get('/movies', requirePermission('QL_DANHMUC_PHIM'), admin.movies);
router.post('/movies', requirePermission('QL_DANHMUC_PHIM'), admin.createMovie);
router.put('/movies/:movieId', requirePermission('QL_DANHMUC_PHIM'), admin.updateMovie);
router.delete('/movies/:movieId', requirePermission('QL_DANHMUC_PHIM'), admin.deleteMovie);
router.put('/movies/:movieId/actors', requirePermission('QL_DANHMUC_PHIM'), admin.setMovieActors);
router.get('/genres', requirePermission('QL_THELOAI'), admin.genres);
router.post('/genres', requirePermission('QL_THELOAI'), admin.createGenre);
router.put('/genres/:genreId', requirePermission('QL_THELOAI'), admin.updateGenre);
router.delete('/genres/:genreId', requirePermission('QL_THELOAI'), admin.deleteGenre);
router.get('/actors', requirePermission('QL_DANHMUC_PHIM'), admin.actors);
router.post('/actors', requirePermission('QL_DANHMUC_PHIM'), admin.createActor);
router.put('/actors/:actorId', requirePermission('QL_DANHMUC_PHIM'), admin.updateActor);
router.delete('/actors/:actorId', requirePermission('QL_DANHMUC_PHIM'), admin.deleteActor);
router.get('/products', requirePermission('QL_SANPHAM'), admin.products);
router.post('/products', requirePermission('QL_SANPHAM'), admin.createProduct);
router.put('/products/:productId', requirePermission('QL_SANPHAM'), admin.updateProduct);
router.delete('/products/:productId', requirePermission('QL_SANPHAM'), admin.deleteProduct);
router.get('/promotions', requirePermission('QL_KHUYENMAI'), admin.promotions);
router.post('/promotions', requirePermission('QL_KHUYENMAI'), admin.createPromotion);
router.put('/promotions/:promotionId', requirePermission('QL_KHUYENMAI'), admin.updatePromotion);
router.delete('/promotions/:promotionId', requirePermission('QL_KHUYENMAI'), admin.deletePromotion);
router.get('/reports/revenue', requirePermission('XEM_BAO_CAO_TOANHE'), admin.revenue);

// Admin uses the same append-only complaint history procedures and role checks as CSKH.
const complaintId = (req) => validators.complaintId(req.params.complaintId);
const wrapSupport = (action) => async (req, res, next) => {
  try { res.json(await action(req)); } catch (error) { next(error); }
};
router.get('/complaints', requirePermission('QL_KHIEUNAI'), wrapSupport(async (req) => ({ complaints: await supportService.list(req.user.userId, validators.listFilters(req.query)) })));
router.get('/complaints/:complaintId', requirePermission('QL_KHIEUNAI'), wrapSupport(async (req) => ({ complaint: await supportService.detail(req.user.userId, complaintId(req)) })));
router.get('/complaints/:complaintId/order-reference', requirePermission('QL_KHIEUNAI'), wrapSupport(async (req) => supportService.orderReference(req.user.userId, complaintId(req))));
router.post('/complaints/:complaintId/processings', requirePermission('XULY_KHIEUNAI'), wrapSupport(async (req) => ({ processing: await supportService.addProcessing(req.user.userId, complaintId(req), validators.processing(req.body)) })));
router.put('/complaints/:complaintId/status', requirePermission('XULY_KHIEUNAI'), wrapSupport(async (req) => ({ complaint: await supportService.updateStatus(req.user.userId, complaintId(req), validators.statusUpdate(req.body)) })));

export default router;
