import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { root,evidenceRoot,read,write,env } from './common.mjs';
import { walk } from '../db/lib.mjs';
const r=n=>JSON.parse(read(path.join(evidenceRoot,n+'.json'))),sha=s=>crypto.createHash('sha256').update(s.replace(/\r\n/g,'\n')).digest('hex');
const freeze=r('preserved-before');for(const x of freeze.files)assert.equal(sha(fs.readFileSync(path.join(root,x.file),'utf8')),x.sha256,x.file);
const checks=r('checks'),database=checks.database;assert.equal(checks.status,'PASS');assert.equal(checks.checks.length,17);assert.ok(checks.checks.every(x=>x.status==='PASS'&&(x.skipped??0)===0));
for(const name of ['sql-tests','api-tests','historical-concurrency','transaction-tests','r1-regression','r21-regression','r22-regression','r31-regression','r11-sql','r11-concurrency','r12-sql','r12-nested','r12-concurrency','r21-sql','r21-api','r21-parents','r22-sql','r22-api','r22-promotion','r31-sql','r31-api','r31-concurrency','migration-replay']){assert.equal(r(name).status,'PASS',name);assert.equal(r(name).database,database,name);}
for(const name of ['browser','r22-browser','r31-browser','source-parity','main-test-isolation','main-migration','main-readonly','current-audit-status','changed-files'])assert.equal(r(name).status,'PASS',name);
const sql=r('sql-tests'),api=r('api-tests'),races=r('historical-concurrency'),transactions=r('transaction-tests'),migration=r('main-migration');assert.equal(sql.cases.length,108);assert.equal(api.cases.length,82);assert.equal(api.requests.length,240);assert.equal(sql.monetary.length,2);assert.equal(api.monetary.length,2);assert.equal(sql.rollback.length,4);assert.equal(transactions.cases.length,8);assert.equal(races.cases.length,20);
for(const role of ['manager','admin']){
 for(const field of ['movie','start','end','format','price'])for(const status of ['Đã hủy','Hết hạn'])assert.ok(sql.cases.some(x=>x.role===role&&x.name===`history-${status}-${field}-mixed-status`&&x.sqlError===50120&&x.status==='PASS'));
 for(const name of ['unused-time','unused-format','unused-price','unused-movie','history-Đã hủy-unchanged','history-Đã hủy-close-sale','unused-seat-type','used-ticket-unchanged-type'])assert.ok(sql.cases.some(x=>x.role===role&&x.name===name&&!x.sqlError&&x.status==='PASS'));
 assert.ok(sql.cases.some(x=>x.role===role&&x.name==='room-transfer-not-supported'&&[8144,8145].includes(x.sqlError)));
 for(const name of ['seat-history-Đã hủy-mixed-type-status','seat-history-Hoàn thành-mixed-type-status','active-future-ticket-unchanged-still-operationally-blocked'])assert.ok(sql.cases.some(x=>x.role===role&&x.name===name&&x.sqlError===50207));
 for(const status of ['Hoạt động','Bảo trì','Hỏng'])assert.ok(sql.cases.some(x=>x.role===role&&x.name==='historical-canceled-seat-status-'+status&&!x.sqlError));
 for(const x of sql.cases.filter(x=>x.role===role&&x.sqlError&&x.initial)){assert.deepEqual(x.final,x.initial);}
 for(const x of [...sql.rollback,...transactions.cases].filter(x=>x.role===role&&x.initial))assert.deepEqual(x.final,x.initial);
}
for(const x of races.cases){assert.match(x.blocking.wait_type,/^LCK_M_/);assert.notEqual(x.spids.a,x.spids.b);assert.ok(x.blocking.locks.some(l=>l.request_status==='WAIT'));for(const session of Object.values(x.sessions)){assert.equal(session.trancount,0);assert.equal(session.xactState,0);}assert.equal(x.status,'PASS');}
assert.equal(sql.precision.status,'PASS');assert.deepEqual(sql.outerTransaction.outer,{trancount:1,xactState:1});assert.ok(sql.monetary.every(x=>x.currentCatalog.ticketPrice===125000&&x.detail[1][0].GiaVe===95000&&x.detail[2][0].DonGia===10000&&x.detail[3][0].SoTien===199000));
assert.ok(api.monetary.every(x=>x.detail.products[0].name==='R32 renamed product'&&x.detail.products[0].unitPrice===10000&&x.detail.payments[0].amount===199000));
assert.equal(r('r11-sql').cases.length,20);assert.equal(r('r11-concurrency').cases.length,10);assert.equal(r('r12-sql').cases.length,49);assert.equal(r('r12-nested').cases.length,14);assert.equal(r('r12-concurrency').stressRaces,125);
assert.equal(r('r21-sql').cases.length,30);assert.equal(r('r21-api').requests.length,107);assert.equal(r('r21-api').concurrency.length,2);assert.equal(r('r21-parents').cases.length,14);
assert.equal(r('r22-sql').cases.length,28);assert.equal(r('r22-sql').constraintCases.length,6);assert.equal(r('r22-api').requests.length,54);assert.equal(r('r22-api').concurrency.length,2);assert.equal(r('r22-promotion').lastQuota.length,2);assert.equal(r('r22-promotion').adminRaces.length,12);
assert.equal(r('r31-sql').positive.length,9);assert.equal(r('r31-sql').negative.length,30);assert.equal(r('r31-api').requests.length,59);assert.equal(r('r31-concurrency').replacements.length,4);assert.equal(r('r31-concurrency').actorDelete.length,4);assert.equal(r('r31-concurrency').movieDelete.length,2);
assert.equal(r('browser').result.checks.length,24);assert.equal(r('r22-browser').result.checks.length,10);assert.equal(r('r31-browser').result.checks.length,8);
assert.equal(migration.sourceParity.modules,159);assert.equal(migration.backup.restoreVerifyOnly,'PASS');assert.ok(migration.backup.copyOnly&&migration.backup.checksum);assert.deepEqual(migration.before.data,migration.after.data);assert.deepEqual(migration.after.data,r('main-before-tests').state.data);assert.deepEqual([...migration.changedModules].sort(),['sp_Manager_Seat_Update','sp_Manager_Showtime_Update','usp_Admin_Seat_Update','usp_Admin_Showtime_Update'].sort());assert.equal(migration.after.data.length,27);assert.equal(r('main-readonly').finalCommittedOverlapCount,0);
const oldAudit=JSON.parse(read(path.join(root,'docs/evidence/r31/current-audit-status.json'))),audit=r('current-audit-status');assert.equal(audit.findings.issues.find(x=>x.id==='I-09').status,'RESOLVED R3.2');assert.deepEqual(audit.matrix.rows.map(x=>[x.uc,x.status]),oldAudit.matrix.rows.map(x=>[x.uc,x.status]));for(const id of ['I-02','I-03','I-06','I-07','I-08'])assert.equal(audit.findings.issues.find(x=>x.id===id).status,oldAudit.findings.issues.find(x=>x.id===id).status);
for(const file of walk(path.join(root,'backend/src')))if(/\.(js|mjs)$/.test(file))assert.ok(!/new\s+(?:sql\.)?Transaction\b|\.transaction\s*\(|new\s+Mutex\b|scripts\/r32/.test(read(file)),file);
for(const file of walk(evidenceRoot))if(/\.(json|txt|md|patch|sql|js|jsx)$/.test(file)){const content=read(file);if(env.DB_PASSWORD)assert.ok(!content.includes(env.DB_PASSWORD),'Configured password in '+file);assert.ok(!/"token"\s*:\s*"eyJ/.test(content),'JWT in '+file);}
execFileSync('git',['-c','core.safecrlf=false','diff','--check'],{cwd:root,encoding:'utf8'});
const criteria=[
 ['Đã trace mọi relevant writer','trace-before.md'],['Historical data policy chính xác','../R3_HISTORICAL_METADATA.md'],['Monetary snapshots giữ nguyên','sql-tests.json'],['Show history xét mọi DONDATVE','sql-tests.json'],['Historical PhimID bất biến','sql-tests.json'],['PhongID bất biến; contract không hỗ trợ chuyển phòng','sql-tests.json'],['Historical ThoiGianBatDau bất biến','sql-tests.json'],['Historical ThoiGianKetThuc bất biến','sql-tests.json'],['Historical DinhDang bất biến','sql-tests.json'],['Historical GiaVeCoBan bất biến','sql-tests.json'],['Unused showtime vẫn cập nhật hợp lệ','api-tests.json'],['Giá trị giữ nguyên không false reject','sql-tests.json'],['State transition/canonical Cancel giữ policy','sql-tests.json'],['Seat history xét mọi CHITIETVE','sql-tests.json'],['Historical LoaiGhe bất biến','sql-tests.json'],['Unused seat đổi type hợp lệ','api-tests.json'],['Operational seat status giữ existing policy','sql-tests.json'],['Mixed invalid update rollback toàn bộ','api-tests.json'],['Historical GiaVe không đổi khi sửa BANGGIA','sql-tests.json'],['Historical food DonGia không đổi khi sửa catalog','api-tests.json'],['Order/payment snapshots không đổi','api-tests.json'],['Booking vs Showtime Update concurrency PASS','historical-concurrency.json'],['Booking vs Seat Type Update concurrency PASS','historical-concurrency.json'],['Manager/Admin cùng enforce SQL rules','sql-tests.json'],['API errors đúng và không lộ SQL','api-tests.json'],['SQL positive/negative PASS','sql-tests.json'],['API integration PASS','api-tests.json'],['R1 regression PASS','r1-regression.json'],['R2 regression PASS','r22-regression.json'],['R3.1 regression PASS','r31-regression.json'],['Backend regression PASS','checks.json'],['No-SQL Backend PASS','no-sql.txt'],['Source/schema parity PASS','source-parity.json'],['Không thêm bảng/columns/history snapshots','main-migration.json'],['Không redesign Frontend','source-changes.patch'],['Raw evidence và final DB states','historical-concurrency.json'],['I-09 RESOLVED bằng evidence thật','current-audit-status.json']
].map(([criterion,evidence],i)=>({id:i+1,criterion,evidence,status:'PASS'}));assert.equal(criteria.length,37);
const report=read(path.join(root,'docs/evidence/R3_HISTORICAL_METADATA.md'));assert.equal((report.match(/^## \d+\./gm)??[]).length,28);assert.ok(report.includes('R3.2 DONE')&&report.includes('R3.3'));
write(path.join(evidenceRoot,'final-checks.json'),{at:new Date().toISOString(),database,status:'PASS',acceptedArtifactsPreserved:freeze.files.length,checkGroups:checks.checks.length,sqlCases:sql.cases.length,sqlPositives:sql.cases.filter(x=>!x.sqlError).length,sqlNegatives:sql.cases.filter(x=>x.sqlError).length,apiRequests:api.requests.length,apiCases:api.cases.length,monetarySqlCases:2,monetaryApiCases:2,bookingUpdateRaces:20,writeRollbackCases:4,callerTransactionCases:8,browserChecks:24,backendTests:checks.checks.find(x=>x.name==='backend').tests,frontendTests:checks.checks.find(x=>x.name==='frontend').tests,skipCount:0,r1Regression:'PASS',r21Regression:'PASS',r22Regression:'PASS',r31Regression:'PASS',sourceParityModules:159,tablesPreserved:27,mainDataPreserved:'PASS',credentialsScan:'PASS',runtimeTransactionScan:'PASS',diffWhitespace:'PASS',exitCriteria:criteria});
write(path.join(evidenceRoot,'exit-criteria.md'),'| # | Exit criterion | Result | Evidence |\n|---|---|---|---|\n'+criteria.map(x=>`| ${x.id} | ${x.criterion} | PASS | [raw](${x.evidence}) |`).join('\n')+'\n');
console.log(`PASS final R3.2: ${freeze.files.length} prior files preserved;37/37 criteria;real SQL/API/caller/races;data27/modules159;stop before R3.3.`);
