import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {root,read,write,evidenceRoot} from './common.mjs';
const json=name=>JSON.parse(read(path.join(evidenceRoot,name+'.json')));
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');
for(const name of ['audit-before','test-deployment','profile-tests','browser','checks','main-test-isolation','main-deployment','main-readonly'])assert.equal(json(name).status,'PASS',name);
assert.equal(json('profile-before').status,'REPRODUCED');assert.equal(json('frontend-before').status,'REPRODUCED');
const checks=json('checks'),profile=json('profile-tests'),browser=json('browser'),deploy=json('main-deployment'),main=json('main-readonly'),before=json('audit-before');
assert.ok(checks.checks.every(row=>row.status==='PASS'&&row.exitCode===0));
for(const row of checks.checks.filter(row=>row.tests)){assert.equal(row.pass,row.tests);for(const key of ['fail','cancelled','skipped','todo'])assert.equal(row[key],0);}
assert.equal(checks.r41Reproducibility.status,'PASS');assert.equal(checks.r41Reproducibility.runs,3);
assert.equal(checks.testDatabaseCleanup,'PASS');assert.equal(checks.sourceInputsUnchanged,'PASS');assert.deepEqual(checks.testDatabaseBefore,checks.testDatabaseAfter);
assert.equal(profile.cleanup,'PASS');assert.deepEqual(profile.before,profile.after);assert.ok(profile.cases.every(row=>row.status==='PASS'));assert.equal(profile.races.length,4);assert.ok(profile.races.every(row=>row.status==='PASS'&&row.observedBlocking.wait_type.startsWith('LCK')));
assert.equal(browser.cleanup,'PASS');assert.deepEqual(browser.before,browser.after);assert.ok(browser.checks.every(row=>row.status==='PASS'));
assert.deepEqual(deploy.changedModules,['sp_User_UpdateProfile']);assert.equal(deploy.otherModulesPreserved,158);assert.deepEqual(deploy.before.data,deploy.after.data);assert.equal(deploy.backup.verifyOnly,'PASS');assert.deepEqual(deploy.before,before.main);assert.deepEqual(main.before,deploy.after);assert.deepEqual(main.after,main.before);assert.equal(main.allModuleSourceParity.modules,159);assert.equal(main.allParameterParity,'PASS');assert.equal(main.abnormalNonCustomerProfiles,before.abnormalNonCustomerProfiles);assert.equal(main.http.length,4);
for(const [phase,file] of [['r45','auth-tests'],['r32','sql-tests']]){const r=json('regression/'+phase+'/'+file);assert.equal(r.status,'PASS');assert.equal(r.cleanup,'PASS');assert.deepEqual(r.before,r.after);}
const protectedBefore=json('preserved-before'),allowed=['database/08_procedures/auth/sp_User_UpdateProfile.sql','frontend/src/pages/auth/Profile.jsx','docs/FULL_SYSTEM_AUDIT.md'],changed=[];
for(const [file,hash] of Object.entries(protectedBefore)){assert.ok(fs.existsSync(path.join(root,file)),file);if(sha(file)!==hash){assert.ok(allowed.includes(file),'Out-of-scope modified '+file);changed.push(file);}}
assert.deepEqual(changed.sort(),allowed.sort());
const all=execFileSync('git',['ls-files','-z','--cached','--others','--exclude-standard'],{cwd:root,encoding:'utf8'}).split('\0').filter(Boolean),added=all.filter(file=>!Object.hasOwn(protectedBefore,file));
const newFiles=['backend/tests/roleAwareProfile.test.js','frontend/tests/role-aware-profile.test.js','frontend/tests/r46-browser-fixture.jsx','database/11_tests/profile/update_rollback.sql','docs/contracts/ROLE_AWARE_PROFILE_UPDATE.md','docs/evidence/R4_ROLE_AWARE_PROFILE_UPDATE.md'];
for(const file of added)assert.ok(file.startsWith('scripts/r46/')||file.startsWith('docs/evidence/r46/')||newFiles.includes(file),'Out-of-scope new '+file);
for(const [file,hash] of Object.entries(checks.sourceInputs))assert.equal(sha(file),hash,'Current differs from tested '+file);
const normalize=s=>s.replaceAll('\r\n','\n');assert.ok(normalize(read(path.join(root,'docs/FULL_SYSTEM_AUDIT.md'))).endsWith(normalize(read(path.join(evidenceRoot,'before-source/docs/FULL_SYSTEM_AUDIT.md'))).replace(/^# FULL SYSTEM AUDIT\n\n/,'')));
const previous=JSON.parse(read(path.join(root,'docs/evidence/r45/current-audit-status.json'))),status=structuredClone(previous);
Object.assign(status,{at:new Date().toISOString(),phase:'R4.6',status:'PASS',base:'Frozen accepted working state after Task 13, including pending Tasks 9-13',resolvedIssues:['I-20'],changedUseCases:[]});
const issue=status.findings.issues.find(r=>r.id==='I-20');assert.equal(issue.status,'ACTIVE');
Object.assign(issue,{status:'RESOLVED R4.6',evidence:'docs/contracts/ROLE_AWARE_PROFILE_UPDATE.md; docs/evidence/R4_ROLE_AWARE_PROFILE_UPDATE.md; docs/evidence/r46/{profile-before,profile-tests,browser,checks,main-deployment,main-readonly,final-checks}.json',resolution:'Existing SP locks current DB user/role; Customer-only profile branch; non-Customer common-only, reject non-null Customer-specific fields using existing50301, preserve abnormal profiles. Own transaction/savepoint/rollback and actual concurrent creation verified. Existing five-parameter API signature and Backend unchanged; minimal role-appropriate existing form.',impact:'I-20 resolved with real SQL/HTTP/four-role browser and regression proof. Broader UC acceptance grades and other findings unchanged; no cleanup or R4.7 work.'});
status.findings.baseline.active=status.findings.issues.filter(r=>r.status==='ACTIVE').length;status.findings.baseline.resolved=status.findings.issues.filter(r=>r.status.startsWith('RESOLVED')).length;
status.findings.severity={CRITICAL:0,HIGH:0,MEDIUM:0,LOW:0};for(const row of status.findings.issues.filter(r=>r.status==='ACTIVE'))status.findings.severity[row.severity]++;
assert.deepEqual(status.matrix,previous.matrix);assert.deepEqual(status.findings.issues.filter(r=>r.id!=='I-20'),previous.findings.issues.filter(r=>r.id!=='I-20'));write(path.join(evidenceRoot,'current-audit-status.json'),status);
execFileSync('git',['diff','--check'],{cwd:root});for(const file of all.filter(f=>f.startsWith('scripts/r46/')&&f.endsWith('.mjs')))execFileSync(process.execPath,['--check',path.join(root,file)]);
const patch=changed.map(file=>{try{return execFileSync('git',['diff','--no-index','--',path.join(evidenceRoot,'before-source',file),path.join(root,file)],{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']});}catch(e){assert.equal(e.status,1);return String(e.stdout);}}).join('\n');write(path.join(evidenceRoot,'source-changes.patch'),patch);
for(const file of ['docs/evidence/R4_ROLE_AWARE_PROFILE_UPDATE.md','docs/contracts/ROLE_AWARE_PROFILE_UPDATE.md'])for(const match of read(path.join(root,file)).matchAll(/\]\(([^)]+)\)/g)){const target=path.resolve(root,path.dirname(file),match[1]);assert.ok(target===path.join(evidenceRoot,'final-checks.json')||fs.existsSync(target),'Broken link '+match[1]);}
const result={phase:'R4.6',status:'PASS',at:new Date().toISOString(),changedOriginalFiles:changed,addedFiles:added,preservedOriginalFiles:Object.keys(protectedBefore).length-changed.length,priorTasks9To13Preserved:'PASS',testedSourceMatchesCurrent:'PASS',backendTests:checks.r41Reproducibility.tests,backendRuns:3,authFocusedTests:checks.checks.find(r=>r.name==='auth-focused').tests,frontendTests:checks.checks.find(r=>r.name==='frontend-test').tests,sqlHttpCases:profile.cases.length,httpRequests:profile.requests.length,realRaces:profile.races.length,browserChecks:browser.checks.length,authRegressionCases:json('regression/r45/auth-tests').cases.length,historyRegressionCases:json('regression/r32/sql-tests').cases.length,mainModules:159,changedModules:deploy.changedModules,mainTables:27,mainDataSchemaRolesPermissionsPreserved:'PASS',testCleanup:'PASS',useCaseGradesUnchanged:status.matrix.rows.length,onlyResolvedFinding:'I-20',scope:'Only R4.6; stop before R4.7/R5-R9',gitDiffCheck:'PASS',syntax:'PASS'};
write(path.join(evidenceRoot,'final-checks.json'),result);console.log(`PASS final R4.6: ${result.backendTests} Backend x3; ${result.sqlHttpCases} SQL/HTTP, ${result.httpRequests} HTTP, ${result.realRaces} actual races, ${result.browserChecks} browser; ${result.preservedOriginalFiles} existing files preserved.`);
