import os from 'node:os';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { preview } from '../../frontend/node_modules/vite/dist/node/index.js';
import { assert,fs,path,root,save } from './common.mjs';
export async function browserAcceptance({backend,ids,prefix,password,prepareReview}){
 const chrome=process.env.R3B_CHROME_PATH??'C:/Program Files/Google/Chrome/Application/chrome.exe';assert.ok(fs.existsSync(chrome));
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'cinema-r8-browser-'));
 const site=await preview({root:path.join(root,'frontend'),configFile:false,preview:{host:'127.0.0.1',port:0,proxy:{'/api':{target:backend,changeOrigin:true}}}});
 const origin=`http://127.0.0.1:${site.httpServer.address().port}`;
 const child=spawn(chrome,['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
 let ws,next=0;const pending=new Map(),checks=[],requests=[],runtimeErrors=[];
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++next;const timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout: '+method));},30000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.text);return result.result.value;};
 const wait=async expression=>{const deadline=Date.now()+18000;while(!await evaluate(expression)){if(Date.now()>deadline)throw Error('Browser wait: '+expression);await new Promise(resolve=>setTimeout(resolve,40));}};
 const go=async route=>{await send('Page.navigate',{url:origin+route});await wait("document.readyState==='complete'&&location.origin==="+JSON.stringify(origin));};
 const text=()=>evaluate('document.body.innerText');
 const check=async(uc,name,condition=true)=>{assert.ok(await condition,name);checks.push({uc,name,status:'PASS',route:await evaluate('location.pathname')});save('browser-tests.json',{status:'RUNNING',productionBuild:true,engine:'Headless Chrome; real Backend/SQL fixture',checks,requests,runtimeErrors});};
 const fill=async(selector,value)=>evaluate(`(async()=>{const node=document.querySelector(${JSON.stringify(selector)});if(!node)throw Error('Missing input');const proto=node.tagName==='SELECT'?HTMLSelectElement.prototype:node.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(node,${JSON.stringify(String(value))});node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));})()`);
 const setLabel=async(label,value,scope='document')=>{const selector=await evaluate(`(()=>{const parent=${scope};const label=[...parent.querySelectorAll('label')].find(node=>node.textContent.trim().startsWith(${JSON.stringify(label)}));const input=label?.querySelector('input,textarea,select');if(!input)throw Error('Missing label');input.setAttribute('data-r8-field','target');return '[data-r8-field="target"]';})()`);await fill(selector,value);await evaluate("document.querySelector('[data-r8-field=target]').removeAttribute('data-r8-field')");};
 const click=async(label,scope='document')=>evaluate(`(()=>{const parent=${scope};const nodes=[...parent.querySelectorAll('button'),...parent.querySelectorAll('a')];const button=nodes.find(node=>node.textContent.trim()===${JSON.stringify(label)});if(!button||button.disabled)throw Error('Missing/disabled action: '+${JSON.stringify(label)});button.click();})()`);
 const apiSeen=async(route,start=0)=>{const deadline=Date.now()+18000;while(!requests.slice(start).some(r=>r.path.split('?')[0]===route&&r.status===200)){if(Date.now()>deadline)throw Error('Browser API not loaded: '+route);await new Promise(resolve=>setTimeout(resolve,40));}};
 const login=async(email,secret,uc,expected)=>{await go('/login');await evaluate('sessionStorage.clear()');await send('Page.navigate',{url:'about:blank'});await wait("location.href==='about:blank'");await go('/login');await wait("document.querySelector('input[type=password]')!==null");await fill('input[type=email]',email);await fill('input[type=password]',secret);await click('Đăng nhập');await wait(`location.pathname===${JSON.stringify(expected)}`);await check(uc,'Login navigates to eligible actor area');};
 try{
  const portFile=path.join(profile,'DevToolsActivePort');let deadline=Date.now()+12000;while(!fs.existsSync(portFile)){assert.ok(Date.now()<deadline,'Chrome startup');await new Promise(resolve=>setTimeout(resolve,50));}
  const port=Number(fs.readFileSync(portFile,'utf8').split('\n')[0]);const target=await(await fetch(`http://127.0.0.1:${port}/json/new?about:blank`,{method:'PUT'})).json();
  ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
  ws.onmessage=event=>{const message=JSON.parse(event.data);if(message.id){const callback=pending.get(message.id);pending.delete(message.id);if(message.error)callback?.reject(Error(message.error.message));else callback?.resolve(message.result);}else if(message.method==='Network.responseReceived'){const response=message.params.response;if(response.url.startsWith(origin+'/api/'))requests.push({path:response.url.slice(origin.length),status:response.status});}else if(message.method==='Runtime.exceptionThrown')runtimeErrors.push({text:message.params.exceptionDetails.text});};
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');
  await go('/register');await wait("document.querySelector('input[type=password]')!==null");const email=prefix+'-'+crypto.randomUUID().slice(0,8)+'-browser@example.invalid';
  await setLabel('Họ tên',prefix+' Browser');await fill('input[type=email]',email);await fill('input[type=password]',password);await click('Tạo tài khoản');await wait("location.pathname==='/login'");await check('KH-01','Register actual account and redirect login');
  await login(email,password,'KH-02','/');const userID=await evaluate("fetch('/api/auth/me',{headers:{Authorization:'Bearer '+sessionStorage.getItem('cinema_access_token')}}).then(r=>r.json()).then(data=>data.user.userId)");await prepareReview(userID);
  await go('/profile');await wait("document.body.innerText.includes('Hồ sơ cá nhân')");await setLabel('Họ tên',prefix+' Browser Edited');await click('Lưu hồ sơ');await wait("document.body.innerText.includes('Đã cập nhật hồ sơ.')");await check('KH-03','Profile save and reload');await send('Page.reload');await wait(`document.querySelector('input[autocomplete]')||[...document.querySelectorAll('input')].some(input=>input.value===${JSON.stringify(prefix+' Browser Edited')})`);
  await go('/movies');await apiSeen('/api/movies');await check('KH-04','Public movie list production screen');await go(`/movies/${ids.movie}`);await apiSeen(`/api/movies/${ids.movie}`);await wait(`document.body.innerText.includes(${JSON.stringify(prefix+' Movie')})`);await check('KH-04','Movie detail and actors/genres rendered');
  await setLabel('Nội dung (không bắt buộc)','R8 browser review');await click('Gửi đánh giá');await wait("document.body.innerText.includes('Đã gửi đánh giá.')");await check('KH-13','Watched customer review persisted through UI');
  await check('KH-05','Showtime browser rendered',await evaluate("document.body.innerText.includes('Lịch chiếu')||document.querySelector('input[type=date]')!==null"));
  await go(`/booking/${ids.show}`);await wait("document.querySelector('.seat-button:not(:disabled)')!==null");await check('KH-06','Real seat map shows selectable seats');await evaluate("document.querySelector('.seat-button:not(:disabled)').click()");await setLabel(prefix+' Snack',1);await check('KH-08','Food quantity selected on booking page');await setLabel('Mã khuyến mãi',ids.promotionCode);await click('Áp dụng');await wait("document.body.innerText.includes('Giảm tạm tính')");await check('KH-09','Promotion preview through real API');await click('Đặt vé');await wait("document.body.innerText.includes('Đặt vé thành công.')");await check('KH-07','Booking created from seat/food/promotion UI');
  const paymentPath=await evaluate("[...document.querySelectorAll('a')].find(node=>node.textContent==='Thanh toán đơn này').getAttribute('href')");ids.browserOrder=Number(paymentPath.split('/')[2]);await go(paymentPath);await wait("[...document.querySelectorAll('button')].some(node=>node.textContent==='Xác nhận thanh toán'&&!node.disabled)");await click('Xác nhận thanh toán');await wait("document.body.innerText.includes('Đã xác nhận thanh toán thành công.')");await check('KH-10','Simulated payment and history rendered');
  await go('/orders');await apiSeen('/api/orders');await wait(`document.body.innerText.includes('#${ids.browserOrder}')`);await check('KH-11','Own paid order in history');await go(`/orders/${ids.browserOrder}`);await apiSeen(`/api/orders/${ids.browserOrder}`);await wait("document.body.innerText.includes('Thành công')");await check('KH-12','Deep link order details/tickets/food/payment');await send('Page.reload');await apiSeen(`/api/orders/${ids.browserOrder}`);await check('KH-12','Refresh retains authenticated own-order deep link');
  await go('/complaints');await wait("document.querySelector('textarea')!==null");await setLabel('Loại khiếu nại','R8 browser');await setLabel('Tiêu đề',prefix+' Browser Complaint');await setLabel('Nội dung','R8 browser complaint detail');await setLabel('Đơn liên quan',ids.browserOrder);await click('Gửi khiếu nại');await wait("document.body.innerText.includes('Đã gửi khiếu nại.')");await check('KH-14','Create own linked complaint UI');
  const complaintLink=await evaluate(`(()=>{const card=[...document.querySelectorAll('article')].find(node=>node.textContent.includes(${JSON.stringify(prefix+' Browser Complaint')}));return card.querySelector('a').getAttribute('href');})()`);ids.browserComplaint=Number(complaintLink.split('/')[2]);await go(complaintLink);await apiSeen('/api'+complaintLink);await check('KH-14','Own complaint detail deep link');
  await go(`/cinemas/${ids.cinema}`);await wait("document.querySelector('figure img')!==null");for(const width of [360,1280]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width===360});await check('PUBLIC-GALLERY','Gallery responsive '+width,await evaluate('document.documentElement.scrollWidth<=innerWidth'));}
  await go('/admin');await wait("location.pathname==='/forbidden'");await check('SECURITY','Wrong actor shows forbidden UX');await go('/movies/2147483647');await wait("document.querySelector('[role=alert]')!==null");await check('SECURITY','Public missing resource 404 UX');
  await login('manager.q1@cinemadb.vn','123456','QLR-01','/manager');await wait("document.querySelector('select[aria-label=\"Rạp hiện tại\"]')!==null");await fill('select[aria-label="Rạp hiện tại"]',ids.cinema);await wait(`document.body.innerText.includes(${JSON.stringify(prefix+' Room Edited')})`);await check('QLR-01','Assigned cinema scope switch');
  await evaluate(`(()=>{const row=[...document.querySelectorAll('li')].find(node=>node.textContent.includes(${JSON.stringify(prefix+' Room Edited')}));[...row.querySelectorAll('button')].find(node=>node.textContent==='Sửa phòng').click();})()`);await setLabel('Tên phòng',prefix+' Browser Room',"document.querySelector('form[aria-label=\"Sửa phòng\"]')");await click('Lưu',"document.querySelector('form[aria-label=\"Sửa phòng\"]')");await wait(`document.body.innerText.includes(${JSON.stringify(prefix+' Browser Room')})`);await check('QLR-02','Full room edit persists UI');
  await evaluate(`(()=>{const row=[...document.querySelectorAll('li')].find(node=>node.textContent.includes(${JSON.stringify(prefix+' Browser Room')}));[...row.querySelectorAll('button')].find(node=>node.textContent==='Ghế').click();})()`);await wait("[...document.querySelectorAll('button')].some(node=>node.textContent==='Sửa ghế')");await evaluate("(()=>{const rows=[...document.querySelector('[aria-label=\"Ghế\"]').querySelectorAll('li')];const row=rows.at(-1);[...row.querySelectorAll('button')].find(node=>node.textContent==='Sửa ghế').click();})()");await click('Lưu',"document.querySelector('form[aria-label=\"Sửa ghế\"]')");await wait("document.querySelector('form[aria-label=\"Sửa ghế\"]')===null");await check('QLR-03','Unused seat edit save/reload; booked-seat history protection covered separately');
  const localDate=new Date(Date.now()+70*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'});const form="document.querySelector('form[aria-label=\"Tạo suất\"]')";
  for(const [label,value]of [['Movie ID',ids.movie],['Mã phòng suất chiếu',ids.room],['Bắt đầu',localDate+'T10:00'],['Kết thúc',localDate+'T11:30'],['Giá vé cơ bản',99999]])await setLabel(label,value,form);await click('Tạo suất',form);await wait("document.body.innerText.includes('99999')");await check('QLR-04','Create showtime from production form');
  const selectShow=price=>evaluate(`(()=>{const row=[...document.querySelectorAll('li')].find(node=>node.textContent.includes(${JSON.stringify(String(price))}));[...row.querySelectorAll('button')].find(node=>node.textContent==='Sửa suất').click();})()`);
  await selectShow(99999);await setLabel('Giá vé cơ bản',100123,"document.querySelector('form[aria-label=\"Sửa suất\"]')");await click('Lưu',"document.querySelector('form[aria-label=\"Sửa suất\"]')");await wait("document.querySelector('form[aria-label=\"Sửa suất\"]')===null&&[...document.querySelectorAll('li')].some(node=>node.textContent.includes('100123')&&!node.textContent.includes('Đã hủy'))");await check('QLR-05','Edit showtime hydrated/save UTC contract');
  await evaluate("(()=>{const row=[...document.querySelectorAll('li')].find(node=>node.textContent.includes('100123')&&!node.textContent.includes('Đã hủy'));[...row.querySelectorAll('button')].find(node=>node.textContent==='Hủy').click();})()");await wait("document.body.innerText.includes('Đã hủy suất chiếu.')");await check('QLR-06','Cancel empty showtime real UI');
  await click('Sửa giá');await setLabel('Phụ thu',2345,"document.querySelector('form[aria-label=\"Sửa giá\"]')");await click('Lưu',"document.querySelector('form[aria-label=\"Sửa giá\"]')");await wait("document.querySelector('form[aria-label=\"Sửa giá\"]')===null&&document.body.innerText.includes('2345')");await check('QLR-07','Full pricing hydrate/edit/save');await check('QLR-08','Dashboard real metrics rendered',await evaluate("document.body.innerText.includes('Đơn đã thanh toán hôm nay')"));await setLabel('Từ ngày',new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}));await setLabel('Đến ngày',new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}));await click('Lọc doanh thu');await check('QLR-09','Revenue DATE_ONLY range request');
  await login('cskh@cinemadb.vn','123456','CSKH-01','/support');await wait(`document.body.innerText.includes(${JSON.stringify(prefix+' Browser Complaint')})`);await check('CSKH-02','Complaint queue includes customer-created item');await evaluate(`[...document.querySelectorAll('button')].find(node=>node.textContent.includes(${JSON.stringify(prefix+' Browser Complaint')})).click()`);await wait("document.body.innerText.includes('Timeline xử lý')");await check('CSKH-03','Complaint detail/timeline');await wait("document.querySelector('[aria-label=\"Chi tiết đơn tham chiếu\"]')!==null");await check('CSKH-04','Full reference includes payment/tickets/food');await fill('textarea[aria-label="Nội dung xử lý"]','R8 browser processing');await click('Ghi diễn biến');await wait("document.body.innerText.includes('R8 browser processing')");await check('CSKH-05','Processing event recorded and reloaded');await fill('select[aria-label="Trạng thái mới"]','Đã giải quyết');await click('Cập nhật trạng thái');await wait("[...document.querySelectorAll('.catalog-section p')].some(node=>node.textContent.includes('R8 browser')&&node.textContent.includes('Đã giải quyết'))");await check('CSKH-06','Status update persisted and visible in complaint summary/timeline');
  await login('admin@cinemadb.vn','123456','ADM-01','/admin');await wait("document.querySelector('nav[aria-label=\"Phân hệ quản trị\"]')!==null");
  for(const [uc,label,route]of [['ADM-02','Tài khoản','/api/admin/users'],['ADM-03','Vai trò','/api/admin/roles'],['ADM-04','Quyền','/api/admin/permissions'],['ADM-06','Phân công','/api/admin/assignments'],['ADM-07','Rạp','/api/admin/cinemas'],['ADM-08','Phòng','/api/admin/rooms'],['ADM-08','Ghế','/api/admin/seats'],['ADM-09','Phim','/api/admin/movies'],['ADM-09','Diễn viên','/api/admin/actors'],['ADM-10','Thể loại','/api/admin/genres'],['ADM-11','Sản phẩm','/api/admin/products'],['ADM-12','Khuyến mãi','/api/admin/promotions'],['ADM-13','Bảng giá','/api/admin/pricing'],['ADM-14','Suất chiếu','/api/admin/showtimes'],['ADM-15','Khiếu nại','/api/admin/complaints'],['ADM-16','Doanh thu','/api/admin/reports/revenue']]){const start=requests.length;await click(label,"document.querySelector('nav[aria-label=\"Phân hệ quản trị\"]')");await apiSeen(route,start);await check(uc,'Admin '+label+' actual API section');}
  await click('Quyền',"document.querySelector('nav[aria-label=\"Phân hệ quản trị\"]')");await wait("document.querySelector('input[aria-label=\"Mã vai trò nhận quyền\"]')!==null");await fill('input[aria-label="Mã vai trò nhận quyền"]',ids.role);const grantStart=requests.length;await click('Đọc quyền hiện tại');await apiSeen(`/api/admin/roles/${ids.role}/permissions`,grantStart);await setLabel('QuyenID (phân cách dấu phẩy)','');await click('Lưu quyền vai trò');await wait("document.body.innerText.includes('Đã cập nhật quyền của vai trò.')");await check('ADM-05','Separate permission assignment form reads/saves empty grant set');
  await check('RELEASE','No console-breaking runtime exception',runtimeErrors.length===0);
  save('browser-tests.json',{status:'PASS',productionBuild:true,engine:'Headless Chrome; real Backend/SQL fixture',checks,requests,runtimeErrors});console.log(`PASS production browser: ${checks.length} assertions across four actors.`);
 }catch(error){const diagnostics=ws?await evaluate("({path:location.pathname,fields:[...document.querySelectorAll('input')].map(input=>({type:input.type,length:input.value.length,valid:input.checkValidity()})),alerts:[...document.querySelectorAll('[role=alert]')].map(node=>node.textContent)})").catch(()=>null):null;save('browser-tests.json',{status:'FAIL',productionBuild:true,checks,requests,runtimeErrors,error:error.message,diagnostics});throw error;}
 finally{ws?.close();child.kill();await site.httpServer.close();}
}
