// Actual HTTP actor flows and browser against one explicit disposable database.
import crypto from 'node:crypto';
import { credentials } from '../db/lib.mjs';
import { assert,path,root,out,connect,ask,sql,fixture,fixtures,save,run } from './common.mjs';
const database=fixture(process.argv.find(arg=>arg.startsWith('--database='))?.slice(11)??fixtures[1]);
if(!process.argv.includes('--skip-r7'))run('r7-integration',['scripts/r7/integration.mjs',`--database=${database}`],{legacy:[path.join(root,'audit/remediation/r7/evidence/integration.json')]});
Object.assign(process.env,credentials(),{DB_DATABASE:database});process.chdir(path.join(root,'backend'));
const {createApp}=await import('../../backend/src/app.js');
const {closePool}=await import('../../backend/src/db/pool.js');
const server=createApp().listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
const base=`http://127.0.0.1:${server.address().port}/api`,pool=await connect(database);
const requests=[],checks=[],tokens={},users={},ids={},prefix='R8-'+crypto.randomUUID().slice(0,8);
const report={status:'RUNNING',database,requests,checks};
const persist=()=>save('actor-flows.json',report);
const check=(uc,name,condition)=>{assert.ok(condition,name);checks.push({uc,name,status:'PASS'});persist();};
async function api(uc,route,{actor='admin',method='GET',body,status=200}={}){
 const started=performance.now();
 const response=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(tokens[actor]?{Authorization:'Bearer '+tokens[actor]}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000)});
 const data=await response.json();requests.push({uc,route,method,actor,status:response.status,expected:status,ms:Math.round((performance.now()-started)*100)/100,error:data.error?.code});persist();
 assert.equal(response.status,status,`${uc} ${method} ${route}: ${data.error?.code??response.status}`);return data.data??data;
}
const post=(uc,route,body,actor='admin')=>api(uc,route,{actor,method:'POST',body,status:route.startsWith('/admin/')&&!route.endsWith('/images')&&!['/admin/movies','/admin/products','/admin/promotions'].includes(route)?200:201});
const put=(uc,route,body,actor='admin')=>api(uc,route,{actor,method:'PUT',body});
const query=async(source,values={})=>{const req=pool.request();for(const [key,value]of Object.entries(values))req.input(key,typeof value==='number'?sql.Int:sql.NVarChar(sql.MAX),value);return(await req.query(source)).recordset;};
const date=days=>new Date(Date.now()+days*86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Ho_Chi_Minh'});
const idOf=(value,...keys)=>{for(const row of [value,...(value?.recordset??[]),...(value?.recordsets?.flat()??[])])for(const key of keys){if(row?.[key]!=null)return row[key];}throw Error('Missing resource ID: '+keys.join(','));};
const login=async(actor,email,password,uc)=>{const data=await api(uc,'/auth/login',{actor:'public',method:'POST',body:{Email:email,MatKhau:password}});tokens[actor]=data.token;users[actor]=data.user;assert.ok(data.token&&data.user.userId);return data;};
try{
 await login('admin','admin@cinemadb.vn','123456','ADM-01');await login('manager','manager.q1@cinemadb.vn','123456','QLR-01');await login('support','cskh@cinemadb.vn','123456','CSKH-01');
 const email=prefix+'@example.invalid',password='R8FixturePass!123';
 await post('KH-01','/auth/register',{HoTen:prefix,Email:email,MatKhau:password,NgaySinh:'2000-01-01'},'public');
 await login('customer',email,password,'KH-02');
 await put('KH-03','/auth/me',{HoTen:prefix+' Updated',SoDienThoai:null,NgaySinh:'2000-01-01',GioiTinh:'Khác'},'customer');
 check('KH-03','Profile DB/API persisted',(await api('KH-03','/auth/me',{actor:'customer'})).user.name===prefix+' Updated');
 for(const [route,actor,status]of [['/admin/users','public',401],['/admin/users','customer',403],['/orders','admin',403],['/support/complaints','manager',403]])await api('SECURITY',route,{actor,status});
 await api('KH-01','/auth/register',{actor:'public',method:'POST',body:{HoTen:prefix,Email:email,MatKhau:password},status:409});
 await api('KH-02','/auth/login',{actor:'public',method:'POST',body:{Email:email,MatKhau:'IncorrectFixture!'},status:401});
 const roles=(await api('ADM-03','/admin/roles')).roles, permissions=(await api('ADM-04','/admin/permissions')).permissions;
 ids.role=idOf((await post('ADM-03','/admin/roles',{code:prefix.toUpperCase(),name:prefix})).role,'VaiTroID');
 await put('ADM-03',`/admin/roles/${ids.role}`,{name:prefix+' Renamed'});
 ids.permission=idOf((await post('ADM-04','/admin/permissions',{code:prefix.toUpperCase()+'_PERM',name:prefix})).permission,'QuyenID');
 await put('ADM-04',`/admin/permissions/${ids.permission}`,{name:prefix+' Permission'});
 await put('ADM-05',`/admin/roles/${ids.role}/permissions`,{permissionIds:[permissions[0].QuyenID]});
 check('ADM-05','Role grant list persists',(await api('ADM-05',`/admin/roles/${ids.role}/permissions`)).permissions.length===1);
 await put('ADM-05',`/admin/roles/${ids.role}/permissions`,{permissionIds:[]});
 check('ADM-05','Empty grants persisted',(await api('ADM-05',`/admin/roles/${ids.role}/permissions`)).permissions.length===0);
 const createdUser=(await post('ADM-02','/admin/users',{name:prefix,email:prefix+'-managed@example.invalid',password,roleId:roles.find(r=>r.MaVaiTro==='KHACH_HANG').VaiTroID})).user;
 ids.managedUser=idOf(createdUser,'NguoiDungID','userId');
 await put('ADM-02',`/admin/users/${ids.managedUser}/status`,{status:'Bị khóa'});await put('ADM-02',`/admin/users/${ids.managedUser}/status`,{status:'Hoạt động'});
 await api('ADM-02','/admin/users');
 const cinemaBody={name:prefix+' Cinema',address:'Disposable R8 cinema',city:'R8 City',description:'R8 fixture'};
 ids.cinema=idOf((await post('ADM-07','/admin/cinemas',cinemaBody)).cinema,'RapID');
 await put('ADM-07',`/admin/cinemas/${ids.cinema}`,{...cinemaBody,status:'Hoạt động'});await api('ADM-07','/admin/cinemas');
 ids.assignment=idOf((await post('ADM-06','/admin/assignments',{userId:users.manager.userId,cinemaId:ids.cinema,startsOn:date(-1),endsOn:null})).assignment,'PhanCongID');
 await put('ADM-06',`/admin/assignments/${ids.assignment}`,{userId:users.manager.userId,cinemaId:ids.cinema,startsOn:date(-1),endsOn:null,status:'Hiệu lực'});await api('ADM-06','/admin/assignments');
 check('QLR-01','Current assignment is visible with prior JWT',(await api('QLR-01','/manager/cinemas',{actor:'manager'})).cinemas.some(c=>c.id===ids.cinema));
 ids.room=(await post('QLR-02',`/manager/cinemas/${ids.cinema}/rooms`,{name:prefix+' Room',type:'2D'},'manager')).room.id;
 await put('QLR-02',`/manager/rooms/${ids.room}`,{name:prefix+' Room Edited',type:'2D',status:'Hoạt động'},'manager');await api('QLR-02',`/manager/cinemas/${ids.cinema}/rooms`,{actor:'manager'});
 ids.seats=[];for(let number=1;number<=16;number++)ids.seats.push((await post('QLR-03',`/manager/rooms/${ids.room}/seats`,{row:'A',number,type:'Thường'},'manager')).seat.id);
 await put('QLR-03',`/manager/seats/${ids.seats[15]}`,{type:'VIP',status:'Hoạt động'},'manager');await api('QLR-03',`/manager/rooms/${ids.room}/seats`,{actor:'manager'});
 ids.genre=idOf((await post('ADM-10','/admin/genres',{name:prefix+' Genre'})).genre,'TheLoaiID');await put('ADM-10',`/admin/genres/${ids.genre}`,{name:prefix+' Genre Edited'});await api('ADM-10','/admin/genres');
 ids.actor=idOf((await post('ADM-09','/admin/actors',{name:prefix+' Actor',nationality:'Việt Nam'})).actor,'DienVienID');await put('ADM-09',`/admin/actors/${ids.actor}`,{name:prefix+' Actor Edited',nationality:'Việt Nam'});await api('ADM-09','/admin/actors');
 const movieBody={title:prefix+' Movie',durationMinutes:90,releaseDate:date(-20),endDate:date(365),genreIds:[ids.genre],posterUrl:'/vite.svg'};
 ids.movie=idOf((await post('ADM-09','/admin/movies',movieBody)).movie,'movieId','PhimID');await put('ADM-09',`/admin/movies/${ids.movie}`,{...movieBody,status:'Đang chiếu'});
 await put('ADM-09',`/admin/movies/${ids.movie}/actors`,{cast:[{actorId:ids.actor,role:'R8 role'}]});await api('ADM-09','/admin/movies');
 await api('KH-04','/movies',{actor:'public'});check('KH-04','Movie detail includes assigned genre/cast',(await api('KH-04',`/movies/${ids.movie}`,{actor:'public'})).actors.some(a=>a.id===ids.actor));
 const productBody={name:prefix+' Snack',type:'Snack',price:25000,description:'R8 product'};ids.product=idOf((await post('ADM-11','/admin/products',productBody)).product,'SanPhamID');await put('ADM-11',`/admin/products/${ids.product}`,{...productBody,status:'Đang bán'});await api('ADM-11','/admin/products');await api('KH-08','/products',{actor:'public'});
 const promotionBody={code:prefix.toUpperCase(),description:'R8 promo',discountType:'Phần trăm',discountValue:10,minimumOrder:0,startsAt:new Date(Date.now()-86400000).toISOString(),endsAt:new Date(Date.now()+86400000*60).toISOString(),quantity:100};
 ids.promotion=idOf((await post('ADM-12','/admin/promotions',promotionBody)).promotion,'KhuyenMaiID');const {code,...promotionEdit}=promotionBody;await put('ADM-12',`/admin/promotions/${ids.promotion}`,{...promotionEdit,status:'Hoạt động'});await api('ADM-12','/admin/promotions');ids.promotionCode=code;
 const imageBody={url:'/vite.svg',description:'R8 cover',displayOrder:10,status:'Hoạt động'};ids.image=idOf((await post('ADM-07',`/admin/cinemas/${ids.cinema}/images`,{...imageBody,cover:true})).image,'HinhAnhRapID','id');await put('ADM-07',`/admin/cinemas/${ids.cinema}/images/${ids.image}`,{...imageBody,description:'R8 edited cover'});await api('ADM-07',`/admin/cinemas/${ids.cinema}/images/${ids.image}/cover`,{method:'PATCH',body:{cover:true}});await api('ADM-07',`/admin/cinemas/${ids.cinema}/images`);await api('PUBLIC-GALLERY',`/cinemas/${ids.cinema}/images`,{actor:'public'});
 let showIndex=0;const makeShow=async()=>{const starts=new Date(Date.now()+(40+showIndex++)*86400000);const input={movieId:ids.movie,roomId:ids.room,startsAt:starts.toISOString(),endsAt:new Date(+starts+90*60000).toISOString(),format:'2D',basePrice:90000};return{input,id:(await post('QLR-04','/manager/showtimes',input,'manager')).showtime.id};};
 const show=await makeShow();ids.show=show.id;const {roomId,...showEdit}=show.input;
 await put('QLR-05',`/manager/showtimes/${ids.show}`,{...showEdit,basePrice:95000,status:'Mở bán'},'manager');await api('QLR-05',`/manager/cinemas/${ids.cinema}/showtimes`,{actor:'manager'});
 await api('KH-05',`/movies/${ids.movie}/showtimes`,{actor:'public'});await api('KH-06',`/showtimes/${ids.show}/seats`,{actor:'public'});await api('KH-05',`/showtimes/${ids.show}`,{actor:'public'});
 const pricingBody={seatType:'Thường',dayType:'Tất cả',format:'2D',surcharge:1000,startsOn:date(-1),endsOn:null};ids.pricing=(await post('QLR-07',`/manager/cinemas/${ids.cinema}/pricing`,pricingBody,'manager')).pricing.id;
 await put('QLR-07',`/manager/pricing/${ids.pricing}`,{...pricingBody,surcharge:2000,status:'Áp dụng'},'manager');await api('QLR-07',`/manager/cinemas/${ids.cinema}/pricing`,{actor:'manager'});
 const bookingBody={showtimeId:ids.show,seatIds:[ids.seats[0]],products:[{productId:ids.product,quantity:2}],promotionCode:code};await api('KH-09','/promotions/validate',{actor:'customer',method:'POST',body:bookingBody});
 ids.order=(await post('KH-07','/bookings',bookingBody,'customer')).booking.id;
 const payment=(await post('KH-10',`/orders/${ids.order}/payments`,{paymentMethod:'MOMO'},'customer')).payment;
 await api('KH-10',`/orders/${ids.order}/payments/${payment.id}/result`,{actor:'customer',method:'POST',body:{status:'Thành công'}});
 check('KH-12','Order totals, tickets, foods, payment history',(await api('KH-12',`/orders/${ids.order}`,{actor:'customer'})).order.payments.length===1);await api('KH-11','/orders',{actor:'customer'});
 await api('KH-12',`/orders/${ids.order}`,{actor:'manager',status:403});await api('KH-06',`/showtimes/${ids.show}/seats`,{actor:'public'});
 ids.complaint=(await post('KH-14','/complaints',{type:'R8',title:prefix+' Complaint',content:'R8 acceptance',orderId:ids.order},'customer')).complaint.id;await api('KH-14','/complaints',{actor:'customer'});await api('KH-14',`/complaints/${ids.complaint}`,{actor:'customer'});
 await api('CSKH-02','/support/complaints',{actor:'support'});await api('CSKH-03',`/support/complaints/${ids.complaint}`,{actor:'support'});check('CSKH-04','Reference resolves full order',(await api('CSKH-04',`/support/complaints/${ids.complaint}/order-reference`,{actor:'support'})).order.id===ids.order);
 await post('CSKH-05',`/support/complaints/${ids.complaint}/processings`,{content:'R8 support processing',nextStatus:'Đang xử lý'},'support');await put('CSKH-06',`/support/complaints/${ids.complaint}/status`,{status:'Đã giải quyết'},'support');
 await api('ADM-15','/admin/complaints');await api('ADM-15',`/admin/complaints/${ids.complaint}`);await api('ADM-15',`/admin/complaints/${ids.complaint}/order-reference`);await post('ADM-15',`/admin/complaints/${ids.complaint}/processings`,{content:'R8 admin processing',nextStatus:'Đang xử lý'});await put('ADM-15',`/admin/complaints/${ids.complaint}/status`,{status:'Đã giải quyết'});
 await api('QLR-08',`/manager/cinemas/${ids.cinema}/dashboard`,{actor:'manager'});await api('QLR-09',`/manager/cinemas/${ids.cinema}/revenue?fromDate=${date(0)}&toDate=${date(0)}`,{actor:'manager'});await api('ADM-16',`/admin/reports/revenue?fromDate=${date(-1)}&toDate=${date(1)}`);
 const adminRoom=idOf((await post('ADM-08','/admin/rooms',{cinemaId:ids.cinema,name:prefix+' Admin Room',type:'2D'})).room,'PhongID');const adminSeat=idOf((await post('ADM-08','/admin/seats',{roomId:adminRoom,row:'Z',number:1,type:'VIP'})).seat,'GheID');await put('ADM-08',`/admin/rooms/${adminRoom}`,{name:prefix+' Admin Edited',type:'2D',status:'Hoạt động'});await put('ADM-08',`/admin/seats/${adminSeat}`,{type:'Thường',status:'Hoạt động'});await api('ADM-08','/admin/rooms');await api('ADM-08','/admin/seats');
 const adminPrice=idOf((await post('ADM-13','/admin/pricing',{...pricingBody,cinemaId:ids.cinema,seatType:'VIP',surcharge:3000})).pricing,'GiaID');await put('ADM-13',`/admin/pricing/${adminPrice}`,{surcharge:3500,status:'Áp dụng'});await api('ADM-13','/admin/pricing');
 const spare=await makeShow();await put('ADM-14',`/admin/showtimes/${spare.id}`,{...spare.input,roomId:undefined,status:'Đóng bán'});await api('ADM-14','/admin/showtimes');await api('QLR-06',`/manager/showtimes/${spare.id}/cancel`,{actor:'manager',method:'POST',body:{reason:'R8 cancel fixture'}});
 const thirdStart=new Date(Date.now()+60*86400000);const adminShow=idOf((await post('ADM-14','/admin/showtimes',{...show.input,startsAt:thirdStart.toISOString(),endsAt:new Date(+thirdStart+90*60000).toISOString()})).showtime,'SuatChieuID','id');await api('ADM-14',`/admin/showtimes/${adminShow}/cancel`,{method:'POST',body:{reason:'R8 admin cancel'}});
 const spareRoom=(await post('QLR-02',`/manager/cinemas/${ids.cinema}/rooms`,{name:prefix+' Disposable',type:'2D'},'manager')).room.id;const spareSeat=(await post('QLR-03',`/manager/rooms/${spareRoom}/seats`,{row:'Z',number:1,type:'Thường'},'manager')).seat.id;await api('QLR-03',`/manager/seats/${spareSeat}`,{actor:'manager',method:'DELETE'});await api('QLR-02',`/manager/rooms/${spareRoom}`,{actor:'manager',method:'DELETE'});
 await api('ADM-08',`/admin/seats/${adminSeat}`,{method:'DELETE'});await api('ADM-08',`/admin/rooms/${adminRoom}`,{method:'DELETE'});
 // Explicit synthetic watched-history fixture, identical to the R5 eligibility setup.
 const past=(await query(`INSERT dbo.SUATCHIEU(PhimID,PhongID,ThoiGianBatDau,ThoiGianKetThuc,DinhDang,GiaVeCoBan,TrangThai) VALUES(@Movie,@Room,DATEADD(DAY,-10,dbo.fn_BayGio()),DATEADD(MINUTE,90,DATEADD(DAY,-10,dbo.fn_BayGio())),N'2D',95000,N'Hoàn thành'); SELECT CONVERT(INT,SCOPE_IDENTITY()) AS ID;`,{Movie:ids.movie,Room:ids.room}))[0].ID;
 const prepareReview=async userID=>query("INSERT dbo.DONDATVE(NguoiDungID,SuatChieuID,TongTienVe,TongTienDoAn,TienGiamGia,TrangThai) VALUES(@User,@Show,95000,0,0,N'Đã thanh toán');",{User:userID,Show:past});
 await api('KH-13',`/movies/${ids.movie}/reviews`,{actor:'customer',method:'POST',body:{rating:5,content:'Not watched yet'},status:403});await prepareReview(users.customer.userId);await post('KH-13',`/movies/${ids.movie}/reviews`,{rating:5,content:'R8 reviewed'},'customer');await api('KH-13',`/movies/${ids.movie}/reviews`,{actor:'public'});
 report.status='PASS';report.fixtureIDs=ids;persist();
 const {browserAcceptance}=await import('./browser.mjs');await browserAcceptance({backend:base.slice(0,-4),ids,prefix,password,prepareReview});
 save('performance-summary.json',{status:'PASS',environment:'Local disposable fixture; HTTP timings include application/DB/auth overhead',samples:requests.filter(r=>r.status<300&&!r.route.includes('/auth/')).map(({uc,route,method,ms})=>({uc,route,method,ms})),optimization:'NO CHANGE',note:'Sanity measurements only; not an enterprise load benchmark.'});
 console.log(`PASS actor flows: ${requests.length} requests; browser E2E complete.`);
}catch(error){report.status='FAIL';report.error=error.message;persist();throw error;}
finally{await new Promise(resolve=>server.close(resolve));await closePool();await pool.close();}
