import {assert,fs,path,root,dbRoot,out,read,load,save} from './common.mjs';
const browser=load('browser-tests.json'),api=load('actor-flows.json'),routes=load('API_ROUTE_INVENTORY.json'),manifest=JSON.parse(read(path.join(dbRoot,'baseline-manifest.json')));
for(const name of ['final-replay.json','main-final.json','cleanup.json','security-final.json','concurrency-final.json','rollback-final.json','migration-upgrade.json','clean-build.json','restore-test.json','backup-verify.json','performance-summary.json'])assert.equal(load(name).status,'PASS',name);
assert.equal(api.status,'PASS');assert.equal(browser.status,'PASS');assert.deepEqual(browser.runtimeErrors,[]);
const original=read(path.join(root,'docs/audit-full-20261003/TRACEABILITY_45_UC.md'));
const ucRows=original.split('\n').filter(line=>/^\| (?:KH|QLR|CSKH|ADM)-\d\d \|/.test(line)).map(line=>line.split('|').slice(1,-1).map(x=>x.trim()));assert.equal(ucRows.length,45);
const dependency=name=>{const seen=new Set(),visit=n=>{if(seen.has(n))return;seen.add(n);for(const ref of manifest.expected.dependencies.filter(d=>d.objectName===n))if(ref.referenced_entity_name)visit(ref.referenced_entity_name);};visit(name);return[...seen].sort();};
const trace=ucRows.map(([uc,name,frontend])=>{
 const actor=uc.startsWith('KH-')?'KHACH_HANG':uc.startsWith('QLR-')?'QUAN_LY_RAP':uc.startsWith('CSKH-')?'CSKH':'ADMIN';
 let endpoints=routes.endpoints.filter(e=>e.useCase.includes(uc));if(['QLR-01','CSKH-01','ADM-01'].includes(uc))endpoints=routes.endpoints.filter(e=>e.route==='/api/auth/login');assert.ok(endpoints.length,uc+' route trace');
 const apiEvidence=api.requests.map((r,index)=>({index,...r})).filter(r=>r.uc===uc&&r.status===r.expected&&r.status<300),browserEvidence=browser.checks.map((r,index)=>({index,...r})).filter(r=>r.uc===uc&&r.status==='PASS');assert.ok(apiEvidence.length,uc+' actual positive API');assert.ok(browserEvidence.length,uc+' actual browser');
 const screenPaths=[...frontend.matchAll(/\]\((?:\.\.\/\.\.\/)([^)#]+)(?:#[^)]*)?\)/g)].map(m=>m[1]);for(const file of screenPaths)assert.ok(fs.existsSync(path.join(root,file)),file);
 const details=endpoints.map(e=>{
  const controllerService=new Set();
  for(const source of e.sourceReferences){const file=source.replace(/:\d+$/,'');if(file.startsWith('backend/')){const text=read(path.join(root,file));for(const m of text.matchAll(/['"]\.\.\/controllers\/([^'"]+)['"]/g)){const controller='backend/src/controllers/'+m[1];controllerService.add(controller);for(const service of read(path.join(root,controller)).matchAll(/['"]\.\.\/services\/([^'"]+)['"]/g))controllerService.add('backend/src/services/'+service[1]);}}}
  const statuses=[...new Set(apiEvidence.filter(r=>r.method===e.method&&new RegExp('^'+e.route.replace('/api','').replace(/:[^/]+/g,'[^/]+')+'(?:\\?.*)?$').test(r.route)).map(r=>r.status))];
  return{method:e.method,path:e.route,authentication:e.authenticated?'Bearer JWT; live active identity/role/grants loaded per request':'Public',actorEligibility:e.actor,exactPermissionsAND:e.permissions,ownership:e.ownership,managerScope:e.scope,roleGuard:e.role,controllerService:[...controllerService],operation:e.useCase.match(/\[([^\]]+)\]/)?.[1],procedures:e.procedures,transitiveDBObjects:[...new Set(e.procedures.flatMap(p=>dependency(p.split('.').at(-1))))],sourceReferences:e.sourceReferences.map(s=>s.startsWith('08_')?'database/'+s:s),dbGuards:e.db,expectedResponse:{observedHappyPathStatuses:statuses,responseContract:'JSON DTO/result envelope as defined by linked controller/service; validated actual requests in actor-flows.json. Other operation variants use R3/R4/R5 regression evidence.',errors:'Central {error:{code,message}}; malformed400, no JWT401, actor/permission/scope403, safe private foreign/not-found404, business conflict409'}};
 });
 return{uc,actor,name:name.split(';')[0],frontendScreenAction:frontend,frontendSources:screenPaths,endpoints:details,evidence:{integration:'actor-flows.json',apiRequestIndexes:apiEvidence.map(r=>r.index),browser:'browser-tests.json',browserCheckIndexes:browserEvidence.map(r=>r.index),authorization:'r3/probes.json',sourceParity:'source-parity.json',regression:['regressions.json','r4/functional-api.json','legacy-reruns/r5-integration.json','legacy-reruns/integration.json']},DB:'PASS',BE:'PASS',FE:'PASS',INT:'PASS',Browser:'PASS',Result:'PASS'};
});
assert.equal(new Set(trace.map(r=>r.uc)).size,45);assert.equal(trace.filter(r=>r.uc.startsWith('ADM-')).length,16);
save('UC_TRACEABILITY_FINAL.json',{status:'PASS',scope:45,pass:45,partial:0,fail:0,blocked:0,note:'Actual real API and production browser per UC plus negative/boundary phase regressions. This is finite regression coverage, not an exhaustive input proof.',useCases:trace});
save('UC_TRACEABILITY_FINAL.md','# Final traceability — 45 UC\n\n45/45 PASS; 0 PARTIAL/FAIL/BLOCKED. Actor: 14 KH, 9 QLR, 6 CSKH, 16 ADM.\n\n[Detailed JSON](UC_TRACEABILITY_FINAL.json) traces each screen/action, method/path, current authentication/exact AND permissions, ownership/scope, controller/service, SP and transitive DB objects, response contract and exact API/browser evidence indexes. Negative authorization, input/business boundaries and partial grants are in the linked phase regressions; PASS is based on real HTTP/SQL/browser, not unit tests alone.\n\n| UC | Actor | DB | BE | FE | INT | Browser | Result |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n'+trace.map(r=>`| ${r.uc} | ${r.actor} | PASS | PASS | PASS | PASS | PASS | PASS |`).join('\n')+'\n');
save('API_ROUTE_INVENTORY.md','# Current API routes\n\n[Exact permission/SQL matrix](PERMISSION_MATRIX.md), [structured route inventory](API_ROUTE_INVENTORY.json). 118 endpoints: 104 protected, 14 public. Source route and SQL guards revalidated in R8; no routes changed.\n\n| Method | Path | Actor | Auth | Permissions AND |\n| --- | --- | --- | --- | --- |\n'+routes.endpoints.map(e=>`| ${e.method} | ${e.route} | ${e.actor} | ${e.authenticated?'JWT/current identity':'PUBLIC'} | ${e.permissions.join(' + ')||'Identity/role/ownership/scope where applicable'} |`).join('\n')+'\n');
const classification=JSON.parse(read(path.join(root,'audit/remediation/r6a/CLASSIFICATION.json'))).findings;
const findingsText=read(path.join(root,'docs/audit-full-20261003/FINDINGS.md'));
const bugPhase={1:'R1',2:'R5',3:'R5',4:'R4',5:'R4',6:'R4',7:'R4',8:'R5',9:'R5',10:'R5',11:'R5',12:'R5',13:'R5',14:'R4',15:'R5',16:'R5',17:'R5',18:'R5',19:'R3B',20:'R3B'};
const findings=[...findingsText.matchAll(/^## ((?:BUG|DATA|GAP|CONFLICT)-\d{3})\r?\n([\s\S]*?)(?=^## |$(?![\s\S]))/gm)].map(([,id,body])=>{
 const index=Number(id.slice(-3)),kind=id.split('-')[0];const originalStatus=body.match(/\*\*Confidence:\*\* ([^\r\n]+)/)?.[1]??body.match(/\*\*Severity \/ Confidence:\*\* [^/]+\/ ([^\r\n]+)/)?.[1];assert.ok(originalStatus,id+' original status');
 let phase,finalStatus='RESOLVED',evidence,note='';
 if(kind==='BUG'){phase=bugPhase[index];evidence=phase==='R1'?['r1-r2/checks.json']:phase==='R4'?['r4/functional-api.json','r4/functional-browser.json']:phase==='R3B'?['r3/probes.json','r3/partial-grants-browser.json','PERMISSION_MATRIX.md']:['legacy-reruns/r5-integration.json','legacy-reruns/supplemental.json'];}
 if(kind==='DATA'){phase='R6A / R8 preservation';finalStatus='NO CHANGE';const item=classification.find(r=>r.id===id);assert.ok(item);note=item.proposedR6BAction+' Classification: '+item.classification.join(', ');evidence=['../../remediation/r6a/CLASSIFICATION.json','main-final.json'];}
 if(kind==='GAP'){phase=index===7?'R7 (ALREADY_RESOLVED retested)':'R7';evidence=['legacy-reruns/integration.json','r7/browser.json','browser-tests.json'];}
 if(kind==='CONFLICT'){phase=({1:'R2 / R2-FIX',2:'R2',3:'R0–R7 / R8',4:'R8 documentation',5:'R3B'})[index];evidence=({1:['r1-r2/checks.json','concurrency-final.json'],2:['r1-r2/checks.json'],3:['source-parity.json','db-inventory.json'],4:['../../../docs/RELEASE_READINESS.md','UC_TRACEABILITY_FINAL.md'],5:['r3/probes.json','security-final.json']})[index];if(index<3){finalStatus='DOCUMENTED_HISTORICAL_DOC_CONFLICT';note=index===1?'Current approved policy: no refund; retain payment history; ticket compensation points. Earlier refund narrative is historical.':'Current approved policy: success only during live hold; late success is rejected. Earlier late-payment narrative is historical.';}}
 return{id,title:body.match(/\*\*(?:Title|Required feature|Rule):\*\* ([^\r\n]+)/)?.[1]??id,originalStatus,remediationPhase:phase,finalStatus,evidence,note};
});
assert.equal(findings.length,41);for(const[k,n]of Object.entries({BUG:20,DATA:9,GAP:7,CONFLICT:5}))assert.equal(findings.filter(f=>f.id.startsWith(k+'-')).length,n);
save('FINAL_FINDINGS_STATUS.json',{status:'PASS',originalCounts:{BUG:20,DATA:9,GAP:7,CONFLICT:5},unresolvedBugs:0,unresolvedRequiredGaps:0,newApplicationRegressions:[],findings});
save('FINAL_FINDINGS_STATUS.md','# Final reconciliation — 41 findings\n\nOriginal Status preserves the original audit confidence label. All 20 BUG and 7 required GAP are resolved/retested. R6 DATA decisions remain NO CHANGE; absence of old records is not attributed to an R8 repair. Two policy conflicts are documented historical narratives superseded by the approved R2 policy. Original audit files remain byte-identical.\n\n| ID | Original Status | Remediation Phase | Final Status | Evidence |\n| --- | --- | --- | --- | --- |\n'+findings.map(f=>`| ${f.id} | ${f.originalStatus} | ${f.remediationPhase} | ${f.finalStatus} | ${f.evidence.map(e=>`[${e}](${e})`).join(', ')} |`).join('\n')+'\n\nDetailed R6 actions/classifications and policy notes: [JSON](FINAL_FINDINGS_STATUS.json).\n');
const main=load('main-final.json'),counts=load('db-inventory.json').after,clean=load('cleanup.json'),perf=load('performance-summary.json'),commit=load('main-before.json').commit;
const lines=[
 ['Executive Summary','**R8 PASS — RELEASE READY.** 45/45 UC PASS; 0 PARTIAL/FAIL/BLOCKED. No application regression or required gap remains in this tested scope. R8 changes documentation/test tooling/evidence only; no new table, source business change, policy change or historical-data remediation.'],
 ['Release candidate / commit',`Application/SQL candidate: \`${commit}\`. R8 test/doc/evidence changes are in the working tree and have not been committed. [Source fingerprints](main-before.json) and [final unchanged proof](main-final.json) bind this run to the tested application/SQL source.`],
 ['DB inventory',`${Object.entries(counts).map(([k,v])=>`${v} ${k}`).join('; ')}. Before/after identical; no manifest modification. [Inventory](db-inventory.json).`],
 ['45 UC results','[Matrix](UC_TRACEABILITY_FINAL.md), [full traces/evidence indexes](UC_TRACEABILITY_FINAL.json). Real API happy paths for all 45 UC, production Chrome 56 checks covering all 45 UC, four actors. Phase suites supply permission/ownership/scope/negative/boundary and CRUD contracts.'],
 ['R1–R7 regression results','[Final fresh replay](final-replay.json) PASS. R1 UTC/Vietnam/Los_Angeles HTTP/browser, DATE_ONLY/business boundaries; R2 hold/payment/cancel/3NF points/history; R3 current grants/revocation/scope/partial FE grants; R4 forms and bcrypt; R5 validation/atomicity/integrity; R6 all 27 main data hashes identical to R6A; R7 required features. [Regression tasks](regressions.json), [16 core checks](r1-r2/checks.json), [R3](r3/probes.json), [R4](r4/functional-api.json), [R5](legacy-reruns/r5-integration.json), [R7 actual integration](legacy-reruns/integration.json).'],
 ['Security results','[Security](security-final.json) PASS: production restricted Backend, identity-only JWT, 401, configured CORS/Helmet, payload413, missing auth env503, DB failure503, no unhandled rejection or credential logging. Source no raw SQL/ORM; .env untracked. Development login/config left unchanged.'],
 ['Authorization matrix results','[118 route source/SQL guards](PERMISSION_MATRIX.md): 104 protected, 14 public. Exact permission AND, actor eligibility, own-only safe deny and current Manager assignments enforced; no Admin bypass. [Revocation/partial grants](r3/probes.json), [browser negatives](r3/partial-grants-browser.json).'],
 ['Concurrency results','[Final races](concurrency-final.json) PASS. Seat/overlapping sets/hold limit, promo last unit, cancel/compensation/payment retry, pricing overlap, one image cover, assignment create/update and complaint event retention all prove final DB invariants. Existing policy permits the losing promotion booking without discount; payment same-result retries are idempotent.'],
 ['Transaction rollback results','[Nine final rollback paths](rollback-final.json) PASS: booking, profile registration, payment, cancellation ledger/points/order/show, assignment, complaint, pricing, showtime and outer caller rollback. All 27 table data fingerprints identical after injected failure. Additional R2/R5 caller/invalid-product/promo checks retained. Injection only on fixture.'],
 ['Database clean-build results','[Source-only zero build](clean-build.json) and [reset](db-reset.txt) PASS; schema/seed/grants/FK/index/constraints and CHECKDB verified. Exact npm reset invocation also PASS on R8Clean (npm-db-reset.txt). Workload structural checks exclude demo-only seed assertions, which ran on clean baseline.'],
 ['Migration results','[Upgrade/reapply](migration-upgrade.json) PASS: two pending R7 modules, failure atomicity, caller rollback, idempotence, source parity159 and exact data/schema/grants preservation. [Pre-R7 upgrade](legacy-reruns/migration-upgrade.json). Schema-bound unchanged functions verified, not blindly ALTERed. No main delta required in R8.'],
 ['Backup/restore results','[COPY_ONLY/CHECKSUM + VERIFYONLY](backup-verify.json) PASS. [Real clone restore](restore-test.json) PASS: exact data/schema/modules/grants, inventory, CHECKDB and Backend smoke. Backup retained; recovery location is local ignored artifact, no credentials exported. Main never restored/reset.'],
 ['Performance results',`[Repeated sanity](performance-summary.json) PASS: public lists/detail/show/seats, booking/detail, Manager dashboard/revenue, support queue/reference, Admin report. Local HTTP p50 ${perf.p50Ms} ms, p95 ${perf.p95Ms} ms, max ${perf.maxMs} ms. [Actual public SP plan](performance-actual-plan.xml), [logical reads](performance-logical-reads.txt). Three repetitions; no significant local bottleneck; **NO CHANGE** to DB/indexes. No enterprise SLA inferred.`],
 ['Frontend release results','40/40 unit tests, lint, production build PASS; [56 real production browser checks](browser-tests.json), runtimeErrors=[]; route/deep-link/refresh, mobile gallery, actor portals, forms/partial permissions and error UX verified with the final/phase browser suites. [Tests](frontend-tests.txt), [build](frontend-build.txt), [lint](frontend-lint.txt), [R4 UI](r4/functional-browser.json), [R7 UI](r7/browser.json).'],
 ['Backend release results','112/112 tests PASS, procedure contracts/no raw SQL PASS. Production process with restricted SQL login, healthy DB and unavailable DB paths tested. [Tests](backend-tests.txt), [procedure contracts](procedure-contracts.txt), [no SQL](no-raw-sql.txt), [security/runtime](security-final.json).'],
 ['Documentation synchronization','[README](../../../README.md), [architecture/diagram](../../../docs/architecture.md), [release guide](../../../docs/RELEASE_READINESS.md), [database workflows](../../../database/README.md), API manager/catalog and both env examples synchronized. Setup/run/reset/migration/backup/restore/security/test/demo/limits are documented. Historical audit evidence byte-identical.'],
 ['Final finding reconciliation','[41 findings](FINAL_FINDINGS_STATUS.md): 20 BUG RESOLVED, 7 GAP RESOLVED/retested; 9 DATA NO CHANGE with exact R6 classification retained; 5 CONFLICT resolved or documented historical policy narrative. Zero unresolved P0/P1/P2 application bugs or required gaps in audited scope; no new R8 application finding.'],
 ['Main DB / historical preservation','[Main read-only smoke](main-smoke.json), [source parity159](source-parity.json), CHECKDB PASS. [Final fingerprints](main-final.json): all 27 tables, modules, schema and execution grants equal before/R6A as applicable. No main fixtures/booking/seed/reset or historical edits.'],
 ['Cleanup',`[Cleanup](cleanup.json) PASS: ${clean.removed.length} exact owned R8 fixture/restore DBs removed, zero R8 DB/login remains; main preserved and backup retained. Other databases untouched.`],
 ['Known limitations','Production bundle 525.65 KB/gzip154.26 KB retains >500 KB advisory accepted by R8. Simulated payment; local fixture performance only. Main/restore safe smoke skips two future-show dependent branches where main has no eligible future data; those branches pass on fixtures. DEV credential unchanged; restricted production path proven separately. Earlier harness status/selector/timing assumptions were corrected against existing source contracts, without application/policy changes; final fresh replay PASS.'],
 ['Final verdict','**PASS — RELEASE READY.** Acceptance gates met on this candidate/environment; no code/SQL deployment is needed for R8. Retain the verified backup and configure the documented restricted SQL login/origin/private environment when deploying to a new environment.']
];
save('FINAL_ACCEPTANCE_REPORT.md','# R8 — Final Full Regression & Release Readiness\n\n'+lines.map(([title,body],i)=>`## ${i+1}. ${title}\n\n${body}\n`).join('\n'));
save('STATUS.json',{status:'PASS',release:'RELEASE READY',commit,UC:{pass:45,partial:0,fail:0,blocked:0},backendTests:112,frontendTests:40,productionBrowserChecks:browser.checks.length,inventory:counts,newApplicationRegressions:0,mainPreserved:true,r6Preserved:true,cleanup:'PASS',report:'FINAL_ACCEPTANCE_REPORT.md',at:new Date().toISOString()});
console.log('PASS final report: 45 UC, 41 findings, 21 acceptance items; RELEASE READY.');
