import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {root,read,write,evidenceRoot} from './common.mjs';
const json=name=>JSON.parse(read(path.join(evidenceRoot,name+'.json')));
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');
for(const name of ['audit-before','test-deployment','detail-tests','checks','main-test-isolation','main-deployment','main-readonly'])assert.equal(json(name).status,'PASS',name);
assert.equal(json('detail-before').status,'REPRODUCED');
const checks=json('checks'),profile=json('detail-tests'),deploy=json('main-deployment'),main=json('main-readonly'),before=json('audit-before');
assert.ok(checks.checks.every(row=>row.status==='PASS'&&row.exitCode===0));
for(const row of checks.checks.filter(row=>row.tests)){assert.equal(row.pass,row.tests);for(const key of ['fail','cancelled','skipped','todo'])assert.equal(row[key],0);}
assert.equal(checks.r41Reproducibility.status,'PASS');assert.equal(checks.r41Reproducibility.runs,3);
assert.equal(checks.testDatabaseCleanup,'PASS');assert.equal(checks.sourceInputsUnchanged,'PASS');assert.deepEqual(checks.testDatabaseBefore,checks.testDatabaseAfter);
assert.equal(profile.cleanup,'PASS');assert.deepEqual(profile.before,profile.after);assert.ok(profile.cases.every(row=>row.status==='PASS'));assert.equal(profile.races.length,5);assert.ok(profile.races.every(row=>row.status==='PASS'));assert.ok(profile.races.filter(row=>row.name!=='expiry-before-read').every(row=>row.blocking.wait_type.startsWith('LCK')));assert.equal(profile.races.find(row=>row.name==='expiry-before-read').snapshotRead.completedBeforeWriterCommit,true);assert.equal(profile.isolation.is_read_committed_snapshot_on,true);assert.equal(profile.boundary.rows.length,8);assert.equal(profile.job[0].defaultTypedClient,true);assert.equal(profile.job[0].noGetRequests,true);for(const row of profile.nonMutation){assert.deepEqual(row.before,row.after);assert.equal(row.tables,27);}
assert.deepEqual(deploy.changedModules,['sp_Order_GetDetailByCustomer']);assert.equal(deploy.otherModulesPreserved,158);assert.deepEqual(deploy.before.data,deploy.after.data);assert.equal(deploy.backup.verifyOnly,'PASS');assert.deepEqual(deploy.before,before.main);assert.deepEqual(main.before,deploy.after);assert.deepEqual(main.after,main.before);assert.equal(main.allModuleSourceParity.modules,159);assert.equal(main.allParameterParity,'PASS');assert.equal(main.detailGet.status,404);assert.equal(main.detailGet.code,'ORDER_NOT_FOUND');assert.equal(main.http.length,4);
for(const [phase,file] of [['r45','auth-tests'],['r32','sql-tests'],['r21','sql-tests'],['r21','parent-concurrency'],['r22','sql-tests'],['r22','promotion-concurrency'],['r44','ownership-tests']]){const r=json('regression/'+phase+'/'+file);assert.equal(r.status,'PASS');assert.equal(r.cleanup,'PASS');assert.deepEqual(r.before,r.after);}
const protectedBefore=json('preserved-before'),allowed=['database/08_procedures/customer/sp_Order_GetDetailByCustomer.sql','docs/FULL_SYSTEM_AUDIT.md'],changed=[];
for(const [file,hash] of Object.entries(protectedBefore)){assert.ok(fs.existsSync(path.join(root,file)),file);if(sha(file)!==hash){assert.ok(allowed.includes(file),'Out-of-scope modified '+file);changed.push(file);}}
assert.deepEqual(changed.sort(),allowed.sort());
const all=execFileSync('git',['ls-files','-z','--cached','--others','--exclude-standard'],{cwd:root,encoding:'utf8'}).split('\0').filter(Boolean),added=all.filter(file=>!Object.hasOwn(protectedBefore,file));
const newFiles=['backend/tests/orderDetailReadOnly.test.js','database/11_tests/orders/expiry_rollback.sql','docs/contracts/ORDER_DETAIL_READ_ONLY.md','docs/evidence/R4_ORDER_DETAIL_READ_ONLY.md'];
for(const file of added)assert.ok(file.startsWith('scripts/r47/')||file.startsWith('docs/evidence/r47/')||newFiles.includes(file),'Out-of-scope new '+file);
for(const [file,hash] of Object.entries(checks.sourceInputs))assert.equal(sha(file),hash,'Current differs from tested '+file);
const normalize=s=>s.replaceAll('\r\n','\n');assert.ok(normalize(read(path.join(root,'docs/FULL_SYSTEM_AUDIT.md'))).endsWith(normalize(read(path.join(evidenceRoot,'before-source/docs/FULL_SYSTEM_AUDIT.md'))).replace(/^# FULL SYSTEM AUDIT\n\n/,'')));
const previous=JSON.parse(read(path.join(root,'docs/evidence/r46/current-audit-status.json'))),status=structuredClone(previous);
Object.assign(status,{at:new Date().toISOString(),phase:'R4.7',status:'PASS',base:'Frozen accepted working state after Task 14, including pending Tasks 9-14',resolvedIssues:['I-22'],changedUseCases:[]});
const issue=status.findings.issues.find(r=>r.id==='I-22');assert.equal(issue.status,'ACTIVE');
Object.assign(issue,{status:'RESOLVED R4.7',evidence:'docs/contracts/ORDER_DETAIL_READ_ONLY.md; docs/evidence/R4_ORDER_DETAIL_READ_ONLY.md; docs/evidence/r47/{detail-before,detail-tests,checks,main-deployment,main-readonly,final-checks}.json',resolution:'Remove nested expiry and unused lookup from existing Detail SP only. Existing view/DTO effective status, four sets/signature/ownership preserved. Real SQL/HTTP full fingerprints prove no mutation; unchanged timer/typed expiry job runs independently, rollback/idempotency/payment/booking races verified.',impact:'Only I-22 resolved; all other findings and 45 UC acceptance grades preserved. Backend/Auth/job/Frontend/view/expiry/payment/booking production unchanged; R5 not started.'});
status.findings.baseline.active=status.findings.issues.filter(r=>r.status==='ACTIVE').length;status.findings.baseline.resolved=status.findings.issues.filter(r=>r.status.startsWith('RESOLVED')).length;
status.findings.severity={CRITICAL:0,HIGH:0,MEDIUM:0,LOW:0};for(const row of status.findings.issues.filter(r=>r.status==='ACTIVE'))status.findings.severity[row.severity]++;
assert.deepEqual(status.matrix,previous.matrix);assert.deepEqual(status.findings.issues.filter(r=>r.id!=='I-22'),previous.findings.issues.filter(r=>r.id!=='I-22'));write(path.join(evidenceRoot,'current-audit-status.json'),status);
const sqlFile='database/08_procedures/customer/sp_Order_GetDetailByCustomer.sql',oldSql=normalize(read(path.join(evidenceRoot,'before-source',sqlFile)));
const expected=oldSql.split('\n').filter(line=>!line.includes('DECLARE @SuatID INT =')&&!line.includes('EXEC dbo.sp_Order_ExpirePending')).join('\n');assert.equal(normalize(read(path.join(root,sqlFile))),expected,'Production SQL change exceeds removing the write path');
execFileSync('git',['diff','--check'],{cwd:root});for(const file of all.filter(f=>f.startsWith('scripts/r47/')&&f.endsWith('.mjs')))execFileSync(process.execPath,['--check',path.join(root,file)]);
const patch=changed.map(file=>{try{return execFileSync('git',['diff','--no-index','--',path.join(evidenceRoot,'before-source',file),path.join(root,file)],{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']});}catch(e){assert.equal(e.status,1);return String(e.stdout);}}).join('\n');write(path.join(evidenceRoot,'source-changes.patch'),patch);
for(const file of ['docs/evidence/R4_ORDER_DETAIL_READ_ONLY.md','docs/contracts/ORDER_DETAIL_READ_ONLY.md'])for(const match of read(path.join(root,file)).matchAll(/\]\(([^)]+)\)/g)){const target=path.resolve(root,path.dirname(file),match[1]);assert.ok(target===path.join(evidenceRoot,'final-checks.json')||fs.existsSync(target),'Broken link '+match[1]);}
const result={phase:'R4.7',status:'PASS',at:new Date().toISOString(),changedOriginalFiles:changed,addedFiles:added,preservedOriginalFiles:Object.keys(protectedBefore).length-changed.length,priorTasks9To14Preserved:'PASS',testedSourceMatchesCurrent:'PASS',backendTests:checks.r41Reproducibility.tests,backendRuns:3,orderFocusedTests:checks.checks.find(r=>r.name==='order-focused').tests,frontendTests:checks.checks.find(r=>r.name==='frontend-test').tests,sqlHttpCases:profile.cases.length,httpRequests:profile.requests.length,realRaces:profile.races.length,nonMutationChecks:profile.nonMutation.length,authRegressionCases:json('regression/r45/auth-tests').cases.length,historyRegressionCases:json('regression/r32/sql-tests').cases.length,mainModules:159,changedModules:deploy.changedModules,mainTables:27,mainDataSchemaRolesPermissionsPreserved:'PASS',testCleanup:'PASS',useCaseGradesUnchanged:status.matrix.rows.length,onlyResolvedFinding:'I-22',scope:'Only R4.7; stop before R5-R9',gitDiffCheck:'PASS',syntax:'PASS'};
const phases=[];for(const [dir,phase] of [['r41','R4.1'],['r42','R4.2'],['r43','R4.3'],['r44','R4.4'],['r45','R4.5'],['r46','R4.6']]){const file='docs/evidence/'+dir+'/final-checks.json',r=JSON.parse(read(path.join(root,file)));assert.equal(r.status,'PASS');assert.equal(r.phase,phase);assert.equal(sha(file),protectedBefore[file]);phases.push({phase,status:'DONE',evidence:file,sha256:sha(file),preserved:true});}
phases.push({phase:'R4.7',status:'DONE',evidence:'docs/evidence/r47/final-checks.json'});write(path.join(evidenceRoot,'r4-acceptance.json'),{status:'PASS',phase:'R4',decision:'Eligible for aggregate acceptance based on seven completed scoped tasks; not full 45-UC acceptance',tasks:phases,priorEvidencePreserved:'PASS',currentFullBackendRegression:'PASS',currentRelatedLifecycleRegression:'PASS',R5:'NOT STARTED',useCaseGradesUnchanged:45});
write(path.join(evidenceRoot,'final-checks.json'),result);console.log(`PASS final R4.7: ${result.backendTests} Backend x3; ${result.sqlHttpCases} SQL/HTTP, ${result.httpRequests} HTTP, ${result.realRaces} actual races, ${result.nonMutationChecks} non-mutation checks; ${result.preservedOriginalFiles} existing files preserved.`);
