SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
CREATE OR ALTER TRIGGER dbo.TRG_XuLyKhieuNai_CapNhatTrangThaiKhieuNai
ON dbo.XULY_KHIEUNAI
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE kn
    SET kn.TrangThai = i.TrangThaiSauXuLy
    FROM dbo.KHIEUNAI kn
    INNER JOIN INSERTED i ON kn.KhieuNaiID = i.KhieuNaiID;
END;
GO
